### ISSUE TITLE
可以实现折线图和柱状图的组合吗

### ISSUE THREAD

**Issue by sweetXiaoyan** [ElemeFE/v-charts#101]
采用v-charts可以实现折线图和柱状图的组合吗，如何实现？

**Comment by xiguaxigua** [comment]
文档中有一个这种方式的示例可以参考一下

![image](https://user-images.githubusercontent.com/9931685/33540934-22f7d266-d908-11e7-8c5a-93caca421452.png)

**Comment by sweetXiaoyan** [comment]
好的，谢谢
