### ISSUE TITLE
列名标题过多过长,导致与折线重叠,请问该如何解决

### ISSUE THREAD

**Issue by reesechou2014** [ElemeFE/v-charts#105]
![image](https://user-images.githubusercontent.com/8568508/33697298-420c83b4-db41-11e7-89fa-c6a25c8f869c.png)

如图所示

**Comment by xiguaxigua** [comment]
如果图例的数目可控，即 legend 的高度是已知的，可以通过设置 `grid` 属性的top。https://jsfiddle.net/vue_echarts/jepw6dy2/109/

如果图例的数目不可控，并且很容易造成覆盖，可以将图例隐藏。https://jsfiddle.net/vue_echarts/jepw6dy2/110/

**Comment by reesechou2014** [comment]
看了下grid属性能改变图例的位置么,比如我想把图例放在图表的下面或者右侧

**Comment by xiguaxigua** [comment]
也是可以的。https://jsfiddle.net/vue_echarts/jepw6dy2/111/

**Comment by reesechou2014** [comment]
好的,谢谢,另外向问一句,如果把legend放到下边能支持滚动条就好了,类似于grafana那样子

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/33698529-2aa3b0ec-db48-11e7-9d12-5ab88578c9ba.png)

可以实现上面这种类型的翻页

**Comment by reesechou2014** [comment]
nice, 感谢

**Comment by PLQin** [comment]
nice !~
