### ISSUE TITLE
你们这个legend怎么设置左边，没效果啊

### ISSUE THREAD

**Issue by pannysp** [ElemeFE/v-charts#106]
legend={
x: 'left'
}

默认legend是居中的，
左边不就是这样设置吗，结果连legend都不显示了

**Comment by pannysp** [comment]
发现只能在设置extend配置项，这样才能生效

**Comment by pannysp** [comment]
你们也兼容echarts3.0的API吗？
怎么2.X和3.0的配置都有效果：
legend={
x: 100
}
或3.0
legend={
left: 100
}

**Comment by xiguaxigua** [comment]
1. 直接设置属性到组件上，相当于将配置项中的这个属性整个替换成了设置的内容，如果只是想要修改该属性的某些配置的话，推荐使用 extend 来实现。
2. v-charts 面向的是 echarts3.x，3.x 的文档中，对于 legend 的位置设置是 通过`left`,`right`,`top`,`bottom`等属性实现，使用 `x` 依然可以生效，是 echarts3.x 内部对属性做了兼容，不过这些并没有写在文档上，所以保险起见，推荐使用`left`实现居左。

**Comment by pannysp** [comment]
谢谢回复xiguaxigua。

v-charts 面向的是 echarts3.x，非常好！
