### ISSUE TITLE
官方文档现在不显示了，应该是里面包含的Echarts.js的文件位置改变了

### ISSUE THREAD

**Issue by stjava** [ElemeFE/v-charts#108]

**Comment by stjava** [comment]
![image](https://user-images.githubusercontent.com/20898173/33705562-bcfcd130-db6b-11e7-9926-fd2b0ade73d2.png)

**Comment by xiguaxigua** [comment]
缓存问题？我这边是可以正常显示的。

**Comment by xiguaxigua** [comment]
是整个文档不显示了，还是某个页面不显示了，或是页面中的 demo 显示有问题？

**Comment by stjava** [comment]
demo不显示，缓存也清理了。

**Comment by stjava** [comment]
![image](https://user-images.githubusercontent.com/20898173/33706873-79aabd84-db70-11e7-93f8-fc7ac691b09c.png)

**Comment by stjava** [comment]
可以了，感谢！
