### ISSUE TITLE
heatmap 笛卡尔坐标系自定义tooltip

### ISSUE THREAD

**Issue by lazywhite** [ElemeFE/v-charts#111]
鼠标移动到某个格子的时候, 显示的内容能自定义吗? 
或者格子默认显示信息, 点击可跳转

**Comment by xiguaxigua** [comment]
两种方案都是可以做到的：
1. 鼠标移动到某个格子的时候，显示的内容自定义，可以通过 extend 属性，修改 tooltip 的 formatter，在 formatter 函数内拿到格子内的数据信息，然后做响应的显示。
2. 格子默认显示信息，点击可跳转，这个可以使用 events 属性，通过绑定点击事件来实现。

https://jsfiddle.net/vue_echarts/mfagszmL/4/

https://jsfiddle.net/vue_echarts/mfagszmL/2/

**Comment by lazywhite** [comment]
jsfiddle link is broken, 能放在bpaste.net上面吗

**Comment by xiguaxigua** [comment]
https://codepen.io/quietcoder/pen/PEYbPr

https://codepen.io/quietcoder/pen/ypBVeV

这个链接可以看到吗？

**Comment by lazywhite** [comment]
第四个属性是一个ip地址， 比如  'ip':'127.0.0.1',  让其在grid里面就显示ip， tooltip显示 ip的内容， 
第五个属性是一个url ， 比如 'url’： ‘/server/10101/' 用于显示其详细地址

**Comment by xiguaxigua** [comment]
当前版本不支持这个功能，稍等晚上发个版本可以把这个补上

**Comment by xiguaxigua** [comment]
https://codepen.io/quietcoder/pen/PEYbPr

v1.13.1 版本增加了对额外指标展示在提示框中的支持，在定义指标的时候，columns 中前两项为x 轴和 y 轴的维度，第三项为 热力图指标，其余项的数据展示在提示框中。

**Comment by lazywhite** [comment]
wonderful!
最后一个问题， 怎么让grid默认显示某一个属性呢？ 比如第5个属性

**Comment by xiguaxigua** [comment]
gird ?

**Comment by lazywhite** [comment]
就是那个小格子， 默认是不显示信息的， 只有颜色， 现在能让他显示自定义属性的值吗？

**Comment by lazywhite** [comment]
http://echarts.baidu.com/demo.html#heatmap-cartesian   百度的这个图， 每个小格子上是显示数值的，能不能咱们的也显示值， 并且支持显示规定的属性

**Comment by xiguaxigua** [comment]
可以实现，需要使用 extend 属性修改内部的值 https://codepen.io/quietcoder/pen/PEYbPr

**Comment by lazywhite** [comment]
还有tooltip， 能不能让 作为标准的值放在最后一行显示， 这样格式看起来更好一些

**Comment by lazywhite** [comment]
亲， extend之后， tooltip里面的属性和值都变成undefined了

**Comment by xiguaxigua** [comment]
这个功能需要发个版本支持一下

**Comment by lazywhite** [comment]
我交作业， 能不能现在先告诉我

**Comment by xiguaxigua** [comment]
稍等发个版本，坐标轴的信息在组件内部，外面获取不到

**Comment by xiguaxigua** [comment]
https://codepen.io/quietcoder/pen/PEYbPr 现在应该没问题了

**Comment by lazywhite** [comment]
兄弟真给力， 这支持力度， 给钱都不一定找得到。

**Comment by wangcch** [comment]
同问，给力
