### ISSUE TITLE
legend的字体颜色怎么修改

### ISSUE THREAD

**Issue by wangzhiwei3919** [ElemeFE/v-charts#118]
看了半天文档，只有显示和隐藏。。

**Comment by xiguaxigua** [comment]
字体颜色没有提供专门的属性来修改，需要使用 extend 来附加 echarts 配置项实现，可以参看下面的示例。
https://jsfiddle.net/vue_echarts/jepw6dy2/113/

**Comment by wangzhiwei3919** [comment]
收到，看你after-config属性也能实现这个。

**Comment by xiguaxigua** [comment]
是的，两种方式都可以实现。
