### ISSUE TITLE
v-charts使用手册部分好几个图片无法显示

### ISSUE THREAD

**Issue by lhard66** [ElemeFE/v-charts#119]
例如：安装部分的示例图片无法显示。

**Comment by xiguaxigua** [comment]
页面上展示的成什么样子？是 jsfiddle 加载失败吗？还是有别的报错？

最近 jsfiddle 不是很稳定，接下来可能会把所有例子在文档自身的层面实现，然后额外加一个 jsfiddle 或者codepen的链接在旁边。

**Comment by lhard66** [comment]
例如安装部分：https://elemefe.github.io/v-charts/#/，此页面图片展示如下图：
http://img.jgrm.net/FkO0CVEOC0cSVdv54e5WmeOUaVLl_banner

**Comment by xiguaxigua** [comment]
多谢反馈，看起来是 jsfiddle 的链接在有些地方访问不到了，近期文档会被重新处理一遍，避免出现这样的问题。示例的话可以看具体图的，如果有别的需要的 demo 找不到的话，可以在下面留言，我会直接写一份样例提供给你。
