### ISSUE TITLE
https://elemefe.github.io/v-charts 打不开

### ISSUE THREAD

**Issue by muzixinly** [ElemeFE/v-charts#12]
https://elemefe.github.io/v-charts 打不开

**Comment by xiguaxigua** [comment]
可能是运营商搞的鬼🐶全局科学上网试试.....

![wx20170703-110009](https://user-images.githubusercontent.com/9931685/27776626-f39aba6c-5fde-11e7-9955-bbf956d260e5.png)

**Comment by xiguaxigua** [comment]
@muzixinly
