### ISSUE TITLE
如何去掉legend

### ISSUE THREAD

**Issue by hainuo** [ElemeFE/v-charts#121]
![image](https://user-images.githubusercontent.com/421861/34037636-8a663c70-e1c4-11e7-9aaa-7ce062bd4c0e.png)

想去掉顶部的 图例   怎么设置？

**Comment by xiguaxigua** [comment]
legend-visible 属性可以实现这个功能。
![image](https://user-images.githubusercontent.com/9931685/34037804-13366534-e1c5-11e7-870f-4fd6b3e17685.png)

**Comment by hainuo** [comment]
ok  我在环图中没看到   多谢 @xiguaxigua

**Comment by wty8023** [comment]
这个怎么配置的啊 我配置不成功
