### ISSUE TITLE
v-bar x label显示不全

### ISSUE THREAD

**Issue by lazywhite** [ElemeFE/v-charts#125]
https://pan.baidu.com/s/1cM20Wm

右下角数字应为5000, 但是显示不全

**Comment by xiguaxigua** [comment]
#115 这个问题应该可以用同样的方法解决

**Comment by lazywhite** [comment]
两个问题不一样， #115 是被省略的问题， 这个是显示了一半
不能让图大一点让数字全显示出来吗？是被什么元素遮挡了吧？

**Comment by xiguaxigua** [comment]
可以使用 extend 的方法，通过设置 grid 的 right 属性，增大右侧内边距。

**Comment by lazywhite** [comment]
然而没有文档啊, 你们官博也没有啊, 给个code样例吧

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/m1hdcmf4/17/
