### ISSUE TITLE
折线图堆叠，但是有的一条数据不全，怎样让他用直线连接？

### ISSUE THREAD

**Issue by ZjVirus** [ElemeFE/v-charts#127]
如图
![image](https://user-images.githubusercontent.com/21301648/34202868-0891f1c8-e5b4-11e7-8e35-22821898ba4c.png)

或者可不可以拿到每一条的数据集合？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/114/

是这种效果吗？

**Comment by ZjVirus** [comment]
@xiguaxigua 是的，谢谢了
