### ISSUE TITLE
legend 设置为right，显示不正常呀

### ISSUE THREAD

**Issue by ZjVirus** [ElemeFE/v-charts#128]
![image](https://user-images.githubusercontent.com/21301648/34239217-d14eebde-e640-11e7-8b78-75548b9156d6.png)
如图，有遇到这种问题吗？

**Comment by xiguaxigua** [comment]
这种显示是符合预期配置的：echarts的 legend 模块和图的位置是分开设置的，图例 通过直接设置在 legend 属性上的 `left,right,top,bottom` 等实现位置的改变，而趋势图是通过 grid 属性的`left,right,top,bottom` 等  来控制位置，两者在位置设置上并不会互相影响。所以，如果想要把图例放在右侧，可以通过使用 extend 属性，设置 grid.right，让图的右边距大一些就可以了。

**Comment by ZjVirus** [comment]
@xiguaxigua 好的，谢谢
