### ISSUE TITLE
条形图纵轴

### ISSUE THREAD

**Issue by WarrenJones** [ElemeFE/v-charts#129]
条形图纵轴显示数据不全怎么解决呢？求指教
![image](https://user-images.githubusercontent.com/8704779/34287889-02ddb9ac-e725-11e7-9220-7e5412144e7e.png)

**Comment by xiguaxigua** [comment]
没太看懂，方便提供一个例子吗？

**Comment by WarrenJones** [comment]
![image](https://user-images.githubusercontent.com/8704779/34289259-9e8b3f12-e72c-11e7-8d22-3fc03dd1280f.png)
你好，就是我这里有89条数据的，出来的柱子是对的，但是现在名字不全。
![image](https://user-images.githubusercontent.com/8704779/34289302-d7ba7dd4-e72c-11e7-9274-6513a230f64d.png)
帮忙看看，十分感谢。

**Comment by xiguaxigua** [comment]
数据显示不全是指 纵轴 没有显示89个名字吗？
如果是这样的话，如果想要显示全完整的就只能增加高度了，纵轴显示的时候，echarts 会做调整，在排满了的情况下会省略掉一些部分。

**Comment by WarrenJones** [comment]
![image](https://user-images.githubusercontent.com/8704779/34289772-02113af8-e72f-11e7-8020-2349e41bf42d.png)
你看，我把高度调了，他还是显示不全名字

**Comment by xiguaxigua** [comment]
实测了一下，写了一了小例子，你可以基于这个例子看看是不是你的那个项目里设置了什么属性，导致的高度增加还是不能显示全内容；或者是把你所用的数据写成在线的例子，这样比较好针对的处理。

**Comment by WarrenJones** [comment]
十分感谢作者，你真的很好。
![image](https://user-images.githubusercontent.com/8704779/34303830-299fd348-e772-11e7-9437-b9f8bccd26e4.png)
![image](https://user-images.githubusercontent.com/8704779/34303836-31b5ba66-e772-11e7-985a-e3657e765bf9.png)
![image](https://user-images.githubusercontent.com/8704779/34303843-37ae7dc2-e772-11e7-9a20-31767de6b2e9.png)
你好，我这边还没配置什么的。
这是我的接口
http://www.chenlinallen.com/api/team/findTaskIntensityForPerson?currentPageNumber=1&pageSize=10000&openId=dev-chenlin&teamId=2&startTime=2000-01-01&endTime=2018-01-07
这是我的代码https://github.com/WarrenJones/WechatPM不过设计的其他比较多。
![image](https://user-images.githubusercontent.com/8704779/34303917-8912f0da-e772-11e7-8483-a7e0bece951f.png)
![image](https://user-images.githubusercontent.com/8704779/34303926-9212b364-e772-11e7-8aee-65dc605594a4.png)

**Comment by xiguaxigua** [comment]
参考图片上的代码修改一下，看看是否能够满足需求。

![image](https://user-images.githubusercontent.com/9931685/34324349-0c32a3f0-e8ab-11e7-8115-60bb375b8b2f.png)

**Comment by WarrenJones** [comment]
真的ok了，谢谢您，非常感谢，主要是yAxis这个吧？
![image](https://user-images.githubusercontent.com/8704779/34324502-6247511e-e8b0-11e7-9ba9-00fd5dc483b6.png)
没试过这种写法，这个可以写在data的return里面吗？
再次十分感谢

**Comment by xiguaxigua** [comment]
可以

**Comment by WarrenJones** [comment]
感谢，Respect！
