### ISSUE TITLE
折线图纵轴数值过小而横轴显示信息单个过长会显示不全

### ISSUE THREAD

**Issue by yakey** [ElemeFE/v-charts#132]
![image](https://user-images.githubusercontent.com/13793868/34334738-0bc652ca-e984-11e7-9661-2c113836112d.png)
RT，这种怎么设置呢

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/116/ 可以对 x 轴的文字做一定的旋转

**Comment by yakey** [comment]
![image](https://user-images.githubusercontent.com/13793868/34335453-a04b25ba-e989-11e7-9f51-296d9fd1047f.png)
哦，能否旋转的同时把下面单位中心对准那个圆圈呢

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/117/ 这样？
![image](https://user-images.githubusercontent.com/9931685/34335521-59072770-e98a-11e7-82f8-a5af56913805.png)

**Comment by yakey** [comment]
谢谢大神！
试了下只要align: 'left' 就满足需求了
![image](https://user-images.githubusercontent.com/13793868/34335617-1c949682-e98b-11e7-957a-7d87f25b45be.png)

**Comment by yakey** [comment]
OK，这样应该满足需求了，谢谢
![image](https://user-images.githubusercontent.com/13793868/34335693-bf54381e-e98b-11e7-84aa-727dc4792287.png)
