### ISSUE TITLE
监听legend  select 事件，然后修改yAxis 的名称，无效

### ISSUE THREAD

**Issue by ZjVirus** [ElemeFE/v-charts#133]
这个例子https://jsfiddle.net/ZengJin/a0bf8h2b/2/

怎么解决这个问题呢？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/a0bf8h2b/3/

**Comment by ZjVirus** [comment]
@xiguaxigua 
![image](https://user-images.githubusercontent.com/21301648/34348694-5f69a42c-ea47-11e7-8c24-40c7e657b2a0.png)
y轴名称是变了，但是legend 不变，曲线也不变

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/a0bf8h2b/4/ 试试现在这个例子

**Comment by ZjVirus** [comment]
@xiguaxigua ok, 解决了，谢谢
