### ISSUE TITLE
能提供一个手动刷新图表 的 api 么

### ISSUE THREAD

**Issue by dreamkidd** [ElemeFE/v-charts#134]
如题...DataBind 可以提供自动的结果变化...
但是当我想观察初始数据--结果数据中间的过程变量的时候发现没有特别好的办法...想请问能提供一个手动刷新的 api 么

**Comment by xiguaxigua** [comment]
没怎么听明白，手动刷新图表时用在什么场景已经如何使用呢？详细描述一下吧

**Comment by dreamkidd** [comment]
https://jsfiddle.net/dreamkidd/vusum633/
现在当我点击排序的时候...只能看到排序的结果的图...
而我其实想做的是在 selectionSort() 这个方法中...在 for 循环中...每迭代一次...就刷新一次刷新一次图标

**Comment by xiguaxigua** [comment]
是这种效果吗？ https://jsfiddle.net/vusum633/1/

**Comment by dreamkidd** [comment]
em...效果是达到了...本来的想法是在排序中通过 setTimeout 来解决计算过快的问题...即在每次交换后暂停然后手动刷新图标...
您的解决方案需要多加入中间变量...本来是在没有手动刷新图表的 api 后想采用的方案...麻烦您了
