### ISSUE TITLE
我能改变里面字体的颜色吗，没看到有这属性

### ISSUE THREAD

**Issue by ZJN-Bc** [ElemeFE/v-charts#139]
背景色黑白时，需要展示到的字体颜色不一样，想知道怎么设置

**Comment by xiguaxigua** [comment]
两种方式：一种通过设置主题实现，一种通过 extend 方法，修改 echarts options 实现，具体的参考下面的例子。

https://jsfiddle.net/jepw6dy2/120/
https://jsfiddle.net/jepw6dy2/119/

**Comment by zaxlct** [comment]
@xiguaxigua 
上面第二个例子里有一个拼写错误
24行，axisLabe 少了一个字母 l
