### ISSUE TITLE
bug?fix? line 提供的data为null时希望像echarts为断线 而不是0

### ISSUE THREAD

**Issue by chenjiev1** [ElemeFE/v-charts#14]
bug?fix? line 提供的data为null时希望像echarts为断线 而不是0

**Comment by chenjiev1** [comment]
![snip20170703_1](https://user-images.githubusercontent.com/14901546/27786250-027e03de-6013-11e7-8bcf-126f33df858f.png)

**Comment by xiguaxigua** [comment]
@chenjiev1  在 v1.2.5 中修复了这个问题

之前之所以会做补0的逻辑是因为有些情况下，后端在表中取数据时取不到，根本原因是某一天对应的某一项没有这个数据，此时由后端去做补0会显得略有冗余，所以将补0的操作放到了表格组件中。现在，默认是不做这一步操作，如果有需要的话，可以配置折线图配置项中的 nullAddZero 为 true 实现。

**Comment by chenjiev1** [comment]
3Q
