### ISSUE TITLE
echarts里的某些属性怎么使用，例如柱宽和间隔

### ISSUE THREAD

**Issue by ZJN-Bc** [ElemeFE/v-charts#141]
例如我想修改柱状图的 柱宽和间隔，在echarts上能看到barWidth和barGap这些属性，但要怎么使用，谢谢了

**Comment by xiguaxigua** [comment]
v-charts 代理了 options 生成的过程，生成之后的 options，可以通过 extend 的方法，修改某个配置项中的属性，具体的使用可以参考示例： https://jsfiddle.net/vue_echarts/1Le0wps5/63/
