### ISSUE TITLE
我想修改背景线的颜色或样式，要怎么修改

### ISSUE THREAD

**Issue by ZJN-Bc** [ElemeFE/v-charts#142]
看了echarts也没找到，只能修改边框的颜色， 例如我想把背景的线改成虚线和红色， 还有柱状图上好像多了一条粗的白线？边框颜色也改不了
![ba1c18f9-cc36-4d60-8fb3-c3675cd15667](https://user-images.githubusercontent.com/17996964/34428909-14632fbc-ec17-11e7-8583-da1a12526d51.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/jepw6dy2/121/ 是这种效果吗？
