### ISSUE TITLE
ring的高度设置无效，会被遮掉

### ISSUE THREAD

**Issue by areyouse7en** [ElemeFE/v-charts#143]
https://codepen.io/areyouse7en/pen/aEJeYb

```html
ve-ring(:data="chartData" :settings="chartSettings" height="100px")
```
高度设置以后会被遮掉

**Comment by xiguaxigua** [comment]
https://codepen.io/quietcoder/pen/JMWgBY

环图的高度，通过容器高度、y方向偏移和内外半径共同决定。其中，容器高度决定图所占的位置，内外半径决定环的大小，y方向偏移决定环的位置。
