### ISSUE TITLE
能不能多个图表，共用一个图例呢？

### ISSUE THREAD

**Issue by ZjVirus** [ElemeFE/v-charts#144]
如题

**Comment by xiguaxigua** [comment]
可以，但是在当前版本上实现这个会很麻烦，下一个版本会实现这个功能。

在当前版本下可以这样做：比如要实现一个饼图加折线图，先按饼图的配置生成一个饼图，通过 afterConfig 方法，对生成好的 options 进行操作，在 series 中增加数据，在 grid 中限制图的位置，这样就能实现多个图公用一个图例了。可能会比较麻烦，在下一个版本中会解决这个问题。

**Comment by ZjVirus** [comment]
@xiguaxigua 好的，辛苦了
