### ISSUE TITLE
折线图多个stack颜色设置不太友好

### ISSUE THREAD

**Issue by Ex-Caliburn** [ElemeFE/v-charts#145]
![image](https://user-images.githubusercontent.com/24788764/34548055-83b2060e-f13a-11e7-9b4c-f31c9bd7ef18.png)

**Comment by Ex-Caliburn** [comment]
第二图,设置线lineStyle和areaStyle样式比较麻烦

**Comment by xiguaxigua** [comment]
目前单独设置两个指标的样式，可以通过 afterConfig 或 extend 的方式实现，当前版本没有支持指标样式的单独设置，在下一个版本中会处理这个问题。

**Comment by lijiye2018** [comment]
好的，谢谢

**Comment by acmeid** [comment]
@Ex-Caliburn 请教下你，我这么设置线条样式没有生效，是不是我哪里写错了？
```
chartSettings: {
    lineStyle: {
        type: 'dashed',
        color: '#000',
        width: 5
    }
}
```
