### ISSUE TITLE
怎么减小柱状图底部高度？

### ISSUE THREAD

**Issue by roy-lau** [ElemeFE/v-charts#149]
![default](https://user-images.githubusercontent.com/22829291/34768028-ad480f82-f634-11e7-9b3c-84f5f4c5a3be.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/1Le0wps5/66/

**Comment by roy-lau** [comment]
谢谢，回复速度666666666

**Comment by roy-lau** [comment]
还有个**loding**的问题，需要请教您一下。

https://jsfiddle.net/1Le0wps5/68/
想让每次接口没有返回时，显示loding 我这个样子为什么不行呢？

_jsfiddle的只是表达下意思_

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/1Le0wps5/72/
是这样吗？
