### ISSUE TITLE
vue 组件销毁

### ISSUE THREAD

**Issue by yanlibo2013** [ElemeFE/v-charts#150]
最近做了一个项目,技术栈vuejs,vue2.0,vuex,v-echarts,elementui,但是遇到的问题是，页面在切换的时候，耗时比较长，路由值会马上变过去，但是页面差不多需要差不多4秒，才可以切换过来，我仔细排查了一下，发现从使用v-echarts的页面，切换到不使用图表的页面时，才会出现这样的情况，并且这段时间间隔是出现在组件生命周期，beforeDestroy，destroyed，也就是组件在销毁开始，销毁结束会这个时间段回话3到4秒的时间，仅在使用v-echarts的页面会出现这样的情况,因此页面在切换的时候体验不是很好，我尝试解决的办法是给页面添加loading,具体做法是,在组件beforeDestroy这个函数开启loading,在下一个页面组件的mounted之后，关闭，但是我发现并没有出现自己想要的效果,具体是beforeDestroy，destroyed这两个函数期间，及时acion调用开启loading,也没有效果，这段时间仍无任何响应，请问这样的情况如何处理，有那些比较好的解决方案

**Comment by xiguaxigua** [comment]
https://rj5rvvvmkp.codesandbox.io/

测试了一下，如果只是有很多图的情况下，跳出不会有卡顿的情况，反而进入的时候因为渲染起来比较慢会卡一下，具体为什么在 beforeDestroy，destroyed 之间需要花费那么长时间不大好找原因，如果方便的话最好是能看下项目，或者在 codesandbox.io 上写个小例子。

**Comment by yanlibo2013** [comment]
可以，但是现在的项目确实有这样的问题，你的邮箱多少我可以把项目发你看一下

发自我的 iPhone

**Comment by xiguaxigua** [comment]
admin@daxigua.me

**Comment by yanlibo2013** [comment]
好的，稍后，我会详细的写一下，并且把详细的数据提供一下

发自我的 iPhone

**Comment by xiguaxigua** [comment]
图没有展示出来
