### ISSUE TITLE
怎么获取环图的百分比？

### ISSUE THREAD

**Issue by roy-lau** [ElemeFE/v-charts#151]
![default](https://user-images.githubusercontent.com/22829291/34816872-35197b50-f6f1-11e7-97bb-556f8c581046.png)

我想在别的地方使用环图出来的百分比，怎么才能获取呢？

![default](https://user-images.githubusercontent.com/22829291/34817051-bffb1aa8-f6f1-11e7-947e-2979e41819e2.png)

我算的也不是动态的，还是需要用到v-charts传来的百分比

**Comment by xiguaxigua** [comment]
这个值是由 echarts 动态生成的，没有存在某个地方，所以似乎只能动态去计算了。至于13.51还是13.52，可以把具体的数据贴出来看下。

**Comment by roy-lau** [comment]
https://jsfiddle.net/1Le0wps5/65/   数据这样的

我又算了下，echarts生成的应该是对的。正好100%
我自己算的有些问题，您能告诉我echarts是怎么算吗？

**Comment by xiguaxigua** [comment]
获取百分比的函数在这里 https://github.com/ecomfe/echarts/blob/master/src/util/number.js#L192-L241

**Comment by roy-lau** [comment]
谢谢，需求不合理（获取的百分比我不会动态计算），不做了！
