### ISSUE TITLE
grid 设置 图例组件离容器的距离 无效

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#152]
增加属性:  `grid`,  希望是的canvas里的图表实例填充整个canvas; 

但是并没有效果,

在线访问: https://jsfiddle.net/tecfxdg9/46/

**Comment by xiguaxigua** [comment]
饼图中 饼 大小由半径决定， 设置方式参考示例 https://jsfiddle.net/tecfxdg9/47/

**Comment by PLQin** [comment]
好烦啊, 时隔半年, 又遇到这个问题, 但是 jsfiddle已经无法访问了, 求大佬给个关键词, 我再去搜一下 @xiguaxigua
