### ISSUE TITLE
折线图底部 title 过多, 无法完全显示

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#153]
![image](https://user-images.githubusercontent.com/24371471/34972958-ed9906d8-fabf-11e7-822a-791aba996de3.png)

底部只有部分 `门店` 能正常显示;

能否斜着显示;

![image](https://user-images.githubusercontent.com/24371471/34972982-05b160f8-fac0-11e7-8abe-b9ce1f97fe69.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/116/
