### ISSUE TITLE
使用<ve-chart>组件,chartSetting里面的type类型都有哪些

### ISSUE THREAD

**Issue by guardLtw** [ElemeFE/v-charts#155]
我用line，bar之类的图表能出来，用map，heatmap图表就出不来，是不是不叫这个名字？

**Comment by xiguaxigua** [comment]
<ve-chart> 是用来处理折线图，饼图，柱状图这三个规则相同的图所定制的，其他的图还是要专门引入对应的模块

**Comment by guardLtw** [comment]
好的，给点建议文档可以明确点，这样就不会误认为是适用全部图表了

**Comment by guardLtw** [comment]
好的，谢谢，给点建议文档可以明确点，这样就不会误认为是适用全部图表了

**Comment by Creative6** [comment]
好的，谢谢

**Comment by hfc1994** [comment]
实测histogram，line，pie，radar，funnel，bar，ring，waterfall几种可支持，像map，heatmap，wordcloud，gaguescatter都不支持，还有几种模型没用到没测。
官方文档里没明确写“未支持全部”，这个是有点误导人了......

**Comment by maxy612** [comment]
当前版本只有这几种支持：bar, histogram, line, pie, ring, funnel, radar, waterfall

**Comment by 150148313** [comment]
现在支持heatmap 类型吗
