### ISSUE TITLE
数据显示的详细表示 

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#157]
![wyg mi199 9zpa 491 8fc](https://user-images.githubusercontent.com/24371471/35078107-94c4e4f0-fc3b-11e7-9298-c2accb29ea4c.png)
![5567afjxhsftvw wp y5s v](https://user-images.githubusercontent.com/24371471/35078109-95dbfedc-fc3b-11e7-9650-0e6da0970f39.png)

能否直接 (即:未hover的状态下) 显示详细的数据?

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/tecfxdg9/48/ 
设置 `percentShow` 属性可以达到这个效果

**Comment by PLQin** [comment]
:+1: :+1: :+1: 

666
