### ISSUE TITLE
关于 v-charts 的loading样式展现

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#158]
目前在项目中给与 `v-charts`  添加的 loading状态使用的是你们 `element-ui` 的
![image](https://user-images.githubusercontent.com/24371471/35079073-4969bd0a-fc40-11e7-9b11-4a0b2c5b8910.png)

`v-charts` 好像内置了 `loading` 组件 , 默认为 `默认为false` ;

但实践无法显示;

**Comment by xiguaxigua** [comment]
没有引入 loading 的样式？
`import 'v-charts/lib/style.css'`

**Comment by PLQin** [comment]
是如此引用的

```html

<script src="//unpkg.com/vue/dist/vue.js?v=0.00.01"></script>
<script src="//unpkg.com/echarts/dist/echarts.min.js?v=0.00.01"></script>
<script src="//unpkg.com/v-charts/lib/index.min.js?v=0.00.01"></script>
```

**Comment by xiguaxigua** [comment]
增加

```html
<link rel="stylesheet" href="//unpkg.com/v-charts/lib/style.css">
```

试试看

**Comment by PLQin** [comment]
:+1: 

ok!

那我只需要在数据加载完毕后使得loading隐藏即可
