### ISSUE TITLE
饼图数据展示紊乱

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#159]
![image](https://user-images.githubusercontent.com/24371471/35081505-86ccd966-fc4f-11e7-90aa-96b845943fc2.png)

这种情况是否有人遇到过? 

目前无法重现;

**Comment by xiguaxigua** [comment]
之前没有发现有这种问题，如果再次遇到的话可以把重现的代码贴出来看看。

**Comment by PLQin** [comment]
好的 ,如果再重现此类情况 , 我会纪录
