### ISSUE TITLE
在移动端引入图表，好多图标无法显示

### ISSUE THREAD

**Issue by danielmlc** [ElemeFE/v-charts#16]
在移动端引入图表，好多图表无法显示
注入 折线图 柱状图 等一些图表无法在uc浏览器，QQ浏览器等安卓手机上的浏览器上无法显示

**Comment by xiguaxigua** [comment]
更新一下版本试试（v1.2.9）
貌似是由于某些浏览器对 object.assign 不支持导致的。
如果还是不能显示出来的话，麻烦补充一下设备的型号和浏览器版本。

**Comment by step-city** [comment]
浏览器已是最新版本，QQ浏览器（7.6.1.3350），vivo浏览器（5.1.6），折线图、柱状图等还是无法在手机浏览器显示。
程序打包后，安装到手机上也是无法显示。

**Comment by xiguaxigua** [comment]
@step-city 这个图在手机上可以显示出来吗？
https://jsfiddle.net/vue_echarts/x5sn06th/3/

**Comment by step-city** [comment]
@xiguaxigua 这个可以正常显示，上面提到的问题有办法解决吗？

**Comment by xiguaxigua** [comment]
@step-city 
我在这个图表的版本上加了object.assign的polyfill，之前的版本写的demo在安卓qq浏览器上看也是看不了的，确定一下你现在使用的v-charts版本是不是最新的，使用的是lib下的那个包，如果只留下图表的逻辑是不是还会重现这个问题，如果是的话，能否在jsfiddle上写一个重现的最小版本，这样会更方便我调试。

**Comment by step-city** [comment]
@xiguaxigua 刚更新了新的版本，试了下可以正常显示了，thanks！
