### ISSUE TITLE
饼图和环图高度自适应不了

### ISSUE THREAD

**Issue by Creative6** [ElemeFE/v-charts#160]
我把高度设置成100%了，其他图表可以，饼图和环图还是小的
![image](https://user-images.githubusercontent.com/20942162/35085427-a8dc6864-fc63-11e7-8c39-df95afad391e.png)
![image](https://user-images.githubusercontent.com/20942162/35085438-b448e588-fc63-11e7-93eb-444fa089acb8.png)
![image](https://user-images.githubusercontent.com/20942162/35085447-bc4f88cc-fc63-11e7-9bf7-8aa26c61a887.png)

**Comment by Creative6** [comment]
![11m08tqb wpk5 c1z 5tf9m](https://user-images.githubusercontent.com/20942162/35092972-e985267c-fc7b-11e7-9868-b54f5ed643e6.png)
好像还是不能适配父容器的大小

**Comment by xiguaxigua** [comment]
写个重现的例子吧，父容器是如何变化的呢？如果只是改变浏览器视口的变化的话，上面的例子应该是没问题的

**Comment by Creative6** [comment]
您好，我写了个例子，您看一下，我拿了个线图做对比 （理想情况pie应该是在中间？）http://www.creative6.cn/vechart-test.html

**Comment by xiguaxigua** [comment]
哦，我大概了解意思了， https://jsfiddle.net/tecfxdg9/63/ 看下这个例子能否解决问题。

**Comment by Creative6** [comment]
您好，目前可以解决问题，不过ring图这样会变成pie图，我试了一下，ring图这样可以
`            chartSettings: {
              radius: ['50%', '60%'],
              offsetY: '50%'
            }
            // chartExtend: {
            //   series: {
            //     radius: '100%'
            //   }
            // }`

**Comment by Creative6** [comment]
还有个问题问一下，怎么手动resize图表？我把图表放在gridlayout里面，那个拉伸变化的时候，我想resize图表

**Comment by xiguaxigua** [comment]
https://elemefe.github.io/v-charts/#/skill-demo?id=%e5%ae%b9%e5%99%a8%e7%9a%84%e5%88%9d%e5%a7%8b%e5%ae%bd%e5%ba%a6%e6%9c%aa%e7%9f%a5

可以通过直接调用 chartRef.echarts.resize()。

**Comment by Creative6** [comment]
好的，谢谢

**Comment by laura233** [comment]
这个问题怎么解决的，看了评论链接打不开了 @xiguaxigua @Creative6 麻烦提供一下解决方案，多谢
