### ISSUE TITLE
顶部 `label` 分别设置应该如何操作?

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#161]
![image](https://user-images.githubusercontent.com/24371471/35093963-d3523d9c-fc7e-11e7-8957-5c5d6fca13d3.png)

如此, 左侧的数值的 `label` 显示的是数值(这是我要的)

右侧的 比例, 显示的却是小数点, 如何显示为 `%` 呢?

比如最右上角的 `0.99151`; 其实我要的应该是 `99.15%`

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/35095906-32cb6e82-fc85-11e7-8111-cac452352cf0.png)

可以在设置 label 时增加一个 formatter

**Comment by PLQin** [comment]
但是
- 左边的数值也会变成 `%`
```
https://jsfiddle.net/qingguipeng/1Le0wps5/76/
```

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/1Le0wps5/77/

**Comment by PLQin** [comment]
/强

:+1:  

厉害了,   只是像  `yAxisIndex` 这种 字段我应去哪里寻找呢,  有什么规律呢(即我要寻找某个功能, 寻找的关键词出发点应该是什么)?

**Comment by xiguaxigua** [comment]
v-charts 主要做的工作是将数据加配置转为 echarts 的配置，在生成配置项之后，可以通过 extend 方法进行单配置项修改，也可以通过 afterConfig 方法修改。所以，要想修改某个功能，可以到 echarts 的[官方文档](echarts.baidu.com/option.html)上查找对应的属性，然后再通过上述的两种方法来修改对应的内容。

**Comment by PLQin** [comment]
:100:
