### ISSUE TITLE
We need English Documentation :(

### ISSUE THREAD

**Issue by ofebles** [ElemeFE/v-charts#163]

**Comment by xiguaxigua** [comment]
English Doc is being prepared, please wait for a while.

**Comment by altinselimi** [comment]
@xiguaxigua do you have any approximate date as the furthest one we could count on english doc being available?

**Comment by xiguaxigua** [comment]
In the middle of Feb, English doc will be published.

**Comment by thearabbit** [comment]
I can't wait
