### ISSUE TITLE
折线图的点击事件只能点击到每个点上才能触发吗？

### ISSUE THREAD

**Issue by lvvlan** [ElemeFE/v-charts#164]
如题，折线图的点击事件必须要点到每个点上面才能触发吗？ 点击同一列上的那条线不能触发吗？ 或者可以点击图标上的任意位置都可以触发吗？如果我想获取x轴上的数据，有什么更好的事件能代替呢？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/132/

 按照 echarts 提供的文档，点击事件只能够监听具体的echarts 组件，比如折线上的点，比如 legend，不包括空白区域的点；不过有一种替代的方案，原理是在每一行上增加一根透明的柱子，这样，再点击空白区域时就点到了柱子上，可以间接实现这个需求。

**Comment by lvvlan** [comment]
解决了，完美，不过有个要注意的地方，就是每个柱子间如果有空隙的话，点击事件还是不会被触发，这时候只要根据整个图表的宽度计算出每个柱子对应的宽度，让他们之间不再有空隙，就可以完美解决了~  多谢解答~~

**Comment by RoiSoleil520** [comment]
![image](https://user-images.githubusercontent.com/17526611/59584123-d1afb100-910f-11e9-9520-b3d9062099f8.png)
我给zh折线设置的样式柱状图也应用到了，chartSettings 的 opacity 设置好像因为我设置自定义样式然后无效，而且点击也只对折线图有效，有什么办法可以解决吗？ 跪求大佬能帮忙解答 谢谢
![image](https://user-images.githubusercontent.com/17526611/59584329-4125a080-9110-11e9-8f6b-d73dc2fa5093.png)

**Comment by guopz** [comment]
https://jsfiddle.net/jepw6dy2/132/ 
打不开了，还有其他工具吗
