### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by roy-lau** [ElemeFE/v-charts#165]
![default](https://user-images.githubusercontent.com/22829291/35202580-7d8d4cf2-ff5e-11e7-8336-f1707d5c3537.png)

https://jsfiddle.net/jepw6dy2/130/

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/131/ 参考示例

**Comment by roy-lau** [comment]
非常感谢！
