### ISSUE TITLE
The charts will displays confusion in mobile, when I set the height from px to rem

### ISSUE THREAD

**Issue by amyhuangxbd** [ElemeFE/v-charts#17]
The code is:
`<ve-line 
      :data="chartData"
      :height="height" 
      :colors="chartColors" 
      :settings="chartSettings" tooltip-visible 
      :legend-visible="legendVisible" 
      :init-options="initOptions" 
      :after-config="afterConfig"></ve-line>`
set the height to be 4rem:
`this.height = '4rem'`
Then the charts displays confusion in mobile, The inner line chart should not display like this.
![image](https://user-images.githubusercontent.com/4026511/27856723-83c78f34-61a1-11e7-8e94-b91127519189.png)
Here is my research:
1. the canvas is 4rem, 171px in iphone 5, but the top blank area and the bottom blank area have taken 100px, so the inner line chart's height is 71px. 
2. I don't know how to cut the top blank area and the bottom blank area.
![rem](https://user-images.githubusercontent.com/4026511/27857070-e15f780e-61a2-11e7-9248-08928ea1bb94.png)

**Comment by xiguaxigua** [comment]
OK, I will confirm it. @amyhuangxbd

**Comment by xiguaxigua** [comment]
Did you set html font-size such as
```css
html {
  font-size: 100px;
}
```
I code an example without set this and got the same display as yours.

**Comment by xiguaxigua** [comment]
At the same time, I code a simple example, did not find such a problem.
```html
<template>
  <div>
    <ve-line
      :data="chartData"
      height="4rem">
    </ve-line>
  </div>
</template>

<script>
export default {
  created () {
    this.chartData = {
      columns: ['日期', '销售额'],
      rows: [
        { '日期': '1月1日', '销售额': 1213 },
        { '日期': '1月2日', '销售额': 1223 },
        { '日期': '1月3日', '销售额': 23 },
        { '日期': '1月4日', '销售额': 4123 },
        { '日期': '1月5日', '销售额': 3123 },
        { '日期': '1月6日', '销售额': 7123 }
      ]
    }
  }
}
</script>

<style>
html {
  font-size: 100px;
}
body {
  font-size: 14px;
}
</style>

```
Can you give me more info about it? Such as outer HTML structure and css style.

**Comment by chenjiev1** [comment]
@xiguaxigua https://jsfiddle.net/p5ffqu5p/ 就像这样 高度小于200以下 好像就会重叠 我设置为100时变成一条线 添加了legend-visible=false 可是上面的空间还在

**Comment by xiguaxigua** [comment]
@chenjiev1 
这里需要重置一下 grid 的上下边距，参考[文档grid部分](http://echarts.baidu.com/option.html#grid)，grid的默认高度是60，当高度较小的时候表现的就会很明显，设置小一点就可以解决问题了。
![image](https://user-images.githubusercontent.com/9931685/28069134-ebf381e8-667a-11e7-9a4c-dd399a808e1c.png)

**Comment by chenjiev1** [comment]
@xiguaxigua 谢谢
