### ISSUE TITLE
 如何使得柱图翻转 90 度 | 翻转柱状图 | 旋转柱状图 | 横向布局

### ISSUE THREAD

**Issue by PLQin** [ElemeFE/v-charts#170]
如何使得 ` v-charts ` 柱图翻转 90 度 , 如:
![u53](https://user-images.githubusercontent.com/24371471/35424419-7bf55b4a-028e-11e8-8dad-c26c3649659f.png)

 
- 在 `issues` 与 google 中没有搜到相关资料; 
- 搜索资料得知, 在extend中进行配置 : 
  ```
    extend : {
         series : {
            dataLabels : {
                rotation: -90
            }
        }
    }
 // 但是没有生效
  ```

**Comment by xiguaxigua** [comment]
https://elemefe.github.io/v-charts/#/bar
条形图？

**Comment by PLQin** [comment]
对的;  :+1:  是条形图
