### ISSUE TITLE
VeMap does not support specialAreas

### ISSUE THREAD

**Issue by starlight0073** [ElemeFE/v-charts#171]
VeMap does not support specialAreas

**Comment by xiguaxigua** [comment]
Do you want to customize the location?
if it is like this, you can find a solution through this [link](https://elemefe.github.io/v-charts/#/map?id=%e8%ae%be%e7%bd%ae%e8%87%aa%e5%ae%9a%e4%b9%89%e4%bd%8d%e7%bd%ae%e5%b9%b6%e4%bf%ae%e6%94%b9%e6%95%b0%e6%8d%ae%e6%ba%90) ,
if not, please tell me the details.

**Comment by RobbsLuo** [comment]
http://www.echartsjs.com/gallery/editor.html?c=map-usa
![image](https://user-images.githubusercontent.com/11434009/35490718-91767d5a-04dc-11e8-9818-2e27b3cb6e31.png)

**Comment by RobbsLuo** [comment]
Alaska is large in the northwestern United States.
So I need to zoom it out and move the position.
![image](https://user-images.githubusercontent.com/11434009/35490977-8459fd02-04de-11e8-8066-60b4dcac20fe.png)

**Comment by xiguaxigua** [comment]
You can find solution by this demo: https://jsfiddle.net/vue_echarts/1fwe4tt7/20/ .
