### ISSUE TITLE
请增加树图支持

### ISSUE THREAD

**Issue by lazywhite** [ElemeFE/v-charts#173]
http://echarts.baidu.com/examples/editor.html?c=tree-basic

**Comment by xiguaxigua** [comment]
预计在本周末之前加好

**Comment by lazywhite** [comment]
有以下两个需求不知道能否实现
1.某个节点 目前只有name, value两个属性， 希望添加更多属性，在移动到每个节点时， 能全部显示
2. 点击节点或者tooltip时能进行url跳转

**Comment by xiguaxigua** [comment]
应该是没问题的
