### ISSUE TITLE
雷达图areaStyle在组件中不起作用

### ISSUE THREAD

**Issue by Creative6** [ElemeFE/v-charts#175]
在html例子中可以：http://www.creative6.cn/vechart-test.html
![image](https://user-images.githubusercontent.com/20942162/35558397-e8fe12ac-05e2-11e8-9f67-cf30a751b480.png)
![image](https://user-images.githubusercontent.com/20942162/35558408-eee58498-05e2-11e8-842b-7c474763615f.png)
![image](https://user-images.githubusercontent.com/20942162/35558431-fb6dd40e-05e2-11e8-9f61-1f6d933174c2.png)

---------------------------------------------------------------分割------------------------------------------------------------------------------------------------------------------------------------------------------------------
用vue-cli新建了一个工程
![image](https://user-images.githubusercontent.com/20942162/35558305-a969d6ee-05e2-11e8-9f73-1a8745e72dec.png)
![image](https://user-images.githubusercontent.com/20942162/35558318-b261fc4a-05e2-11e8-8a40-dcae0b442024.png)
![image](https://user-images.githubusercontent.com/20942162/35558337-c11912b4-05e2-11e8-807a-b63ebdb4cf82.png)
求解！！！

**Comment by xiguaxigua** [comment]
echarts 版本的问题，在 cli 里面使用的是3.x 的版本，需要手动设置 areaStyle 内容才会有对应的效果，html 中引用的是4.x 版本。

**Comment by roy-lau** [comment]
看看是不是这个效果:smile:

https://jsfiddle.net/jww5fqs8/15/

**Comment by xiguaxigua** [comment]
@roy-lau https://jsfiddle.net/vue_echarts/jww5fqs8/16/

当指定 echarts 版本是3.x之后就不生效了，如果要在3.x 上使用的话需要在属性里做相应的配置。

**Comment by roy-lau** [comment]
原来如此，我没有深入学习。受教了！

**Comment by roy-lau** [comment]
http://echarts.baidu.com/option.html#series-radar.areaStyle  看文档吧！
