### ISSUE TITLE
环形图去掉引导线配置失效

### ISSUE THREAD

**Issue by chenxuan0000** [ElemeFE/v-charts#176]
在文档demo配置
label: {
     show: false
}
生效成功去掉了

本地安装的依赖版本1.15.4 无法成功  麻烦告知了为什么

**Comment by xiguaxigua** [comment]
你的本地安装的应该是 echarts3.x 版本，在3.x 版本中，对 label 的设置与4.0不同 http://echarts.baidu.com/option3.html#series-pie.label.normal 
```js
label: {
  normal: {
    show: false
  }
}
```

**Comment by chenxuan0000** [comment]
好的谢谢 已经强制安装了echarts4.x
