### ISSUE TITLE
请问一下ve-chart组件以后会计划扩展其他图表类型（ex: map）吗?正在考虑只是一个容器，只需改变配置就可以实现更多图表类型

### ISSUE THREAD

**Issue by dfEric** [ElemeFE/v-charts#177]

**Comment by xiguaxigua** [comment]
没错，预想的是之后将 ve-chart 支持所有的图表和图表的组合，比如在一个图中可以使用折线图和饼图，这在当前版本是无法实现的，这可能需要一小段时间，预计在2.0版本之后支持这个功能。现在如果想要实现容器的功能，可以使用 [component 动态组件](https://cn.vuejs.org/v2/guide/components.html#%E5%8A%A8%E6%80%81%E7%BB%84%E4%BB%B6) 实现，通过 is 控制显示的是哪种图。
