### ISSUE TITLE
v-charts 的主题切换问题

### ISSUE THREAD

**Issue by corala** [ElemeFE/v-charts#178]
用v-charts 如何实现主题切换呢

**Comment by xiguaxigua** [comment]
参考 #60

**Comment by xiguaxigua** [comment]
主题的切换，要看使用的什么场景下，如果是要在页面中实时切换的话当前版本还不支持，稍等发一个版本处理掉这个问题。

**Comment by xiguaxigua** [comment]
v1.15.5 参考示例 https://jsfiddle.net/vue_echarts/1Le0wps5/78/
