### ISSUE TITLE
如何将下面的文字，隔行显示比如  0  2  4  6  8

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#181]
如何将下面的文字，隔行显示比如  0  2  4  6  8
因为现在我这里数值比较大，后面的看不到了，所以隔行想着减少一点，或者说有没有其他解决方案
![image](https://user-images.githubusercontent.com/19297519/35719472-8f618258-0824-11e8-8443-1b729b67b56f.png)

**Comment by xiguaxigua** [comment]
有两种办法可以选择：
1. 将数值做旋转，倾斜之后就可以将数值全部显示出来了，推荐这种方案 jsfiddle.net/jepw6dy2/116
2. 通过 grid 限制图的显示区域，扩大边距之后数字可以横着完全显示出来 https://jsfiddle.net/vue_echarts/m1hdcmf4/22/

**Comment by 15521054523** [comment]
好的，谢谢了，主要是api文档参数太多了，我找了半天没找到
