### ISSUE TITLE
如何实现在同一个图上有两条甚至多条折线，但是每条线实时加载的频率是不一样的，目前的版本能实现不

### ISSUE THREAD

**Issue by itsmyturn** [ElemeFE/v-charts#182]

**Comment by xiguaxigua** [comment]
“实时加载的频率” 是指让折线依次加载出来，而不是一起加载出来？

**Comment by itsmyturn** [comment]
实时加载频率是指例如红黄两条线，红线要3s更新一下数据，黄线要10s更新一个数据，他们的更新频率不一样，不是静态的两条线，是要实时更新的，这个需求是否合理

**Comment by xiguaxigua** [comment]
当前版本无法实现这个功能，只能在 3s 和 10s 时同时刷新两条线。

**Comment by itsmyturn** [comment]
我还想问一下，两条线刷新频率不一样我这个逻辑有没有问题，是不是不符合正常逻辑，
