### ISSUE TITLE
如何隐藏或修改灰色的横线？

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/v-charts#185]
如何隐藏或修改灰色的横线？
文档中似乎没有这个配置

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/53/ 是这样的效果吗？

**Comment by acmeid** [comment]
是的，谢谢

**Comment by acmeid** [comment]
还是有点问题，如果我要显示X轴和Y轴的线，隐藏横竖线，应该怎么配置？
(实在不好意思，我在ECharts文档里面也没找到这个配置😂)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/54/  是这样的吗？

**Comment by acmeid** [comment]
是的，太棒了👍
