### ISSUE TITLE
直角坐标热力图格子样式的配置问题

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/v-charts#189]
直角坐标热力图格子样式的配置问题

文档中似乎没有说明怎么配置数据对应格子的颜色范围，默认是黄色到酒红色。

如何修改数据对应格子的颜色范围？

**Comment by xiguaxigua** [comment]
格子的颜色通过 visualMap 配置

https://jsfiddle.net/mfagszmL/10/

**Comment by acmeid** [comment]
谢谢。找了半天没找到 原来是在visualMap 的 inRange 里面配置😂  。唉，真是麻烦你了~
