### ISSUE TITLE
是否支持国际化配置？

### ISSUE THREAD

**Issue by WangDongYao** [ElemeFE/v-charts#190]
怎么让工具箱显示的文字提示为英文

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/aa7ojxyt/56/

**Comment by WangDongYao** [comment]
@xiguaxigua 谢谢，还是希望可以像element ui一样可以直接设置语言，不知道有没有这个计划？

**Comment by xiguaxigua** [comment]
近期没有计划处理这方面，不过后期会把国际化的内容加上的。
