### ISSUE TITLE
热力图默认颜色问题

### ISSUE THREAD

**Issue by lazywhite** [ElemeFE/v-charts#193]
有一个10X10的热力图， 当所有grid的 value全部为0时， 默认显示红色， 怎样修改这个颜色呢

**Comment by lazywhite** [comment]
https://jsfiddle.net/mfagszmL/12/

value都是一致的， 想把目前的红色改成其他颜色

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/mfagszmL/13/ 是这样吗？

**Comment by lazywhite** [comment]
对的
