### ISSUE TITLE
搭配Element ui使用佈局問題

### ISSUE THREAD

**Issue by shihherokai** [ElemeFE/v-charts#196]
<el-row>
            <el-col :xs="24" :sm="12">
                <ve-histogram :data="chartData" :settings="chartSettings" ></ve-histogram>
            </el-col>
        </el-row>

我直接透過官方文件搭配著element ui使用但發現圖表的寬度不是畫面的一半
假設我的畫面一半是600px 圖表宣染出來是 700px 的 寬

**Comment by X-Mars** [comment]
兄弟  你咋解决的
