### ISSUE TITLE
1.16.2 版本 dependencies were not found 这个版本之前 没问题

### ISSUE THREAD

**Issue by rancongjie** [ElemeFE/v-charts#197]
ERROR  Failed to compile with 19 errors                                                

These dependencies were not found:

* echarts in ./node_modules/echarts-amap/dist/echarts-amap.min.js
* echarts/extension/bmap/bmap in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/bar in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/candlestick in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/funnel in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/gauge in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/heatmap in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/line in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/map in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/pie in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/radar in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/sankey in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/scatter in ./node_modules/v-charts/lib/index.js
* echarts/lib/chart/tree in ./node_modules/v-charts/lib/index.js
* echarts/lib/component/dataZoom in ./node_modules/v-charts/lib/index.js
* echarts/lib/component/legend in ./node_modules/v-charts/lib/index.js
* echarts/lib/component/tooltip in ./node_modules/v-charts/lib/index.js
* echarts/lib/component/visualMap in ./node_modules/v-charts/lib/index.js
* echarts/lib/echarts in ./node_modules/v-charts/lib/index.js

**Comment by xiguaxigua** [comment]
运行一下
```
npm install echarts echarts-amap -S
```

**Comment by xiguaxigua** [comment]
1.16.2 版本将 echarts 从 dependencies 修改为 peerDependencies，为了处理 echarts 版本升级（3.x -> 4.x）可能带来的问题，不过这需要额外安装一下 echarts。
