### ISSUE TITLE
ve-map 在vue2 中不能正常显示

### ISSUE THREAD

**Issue by fanyoufu** [ElemeFE/v-charts#198]
说明如下：
1. 在main.js中通过import 和 vue.use()的方式引入组件，且其它的类型的图可以正常 显示。
2. 完全使用 dome https://elemefe.github.io/v-charts/#/map 中的代码。
3. 控制台中没有显示错误，在页面观察代码结果是：

<pre> <div class="ve-map" style="width: auto; height: 400px; position: relative;"><div _echarts_instance_="ec_1519465919999" style="width: auto; height: 400px; position: relative; -webkit-tap-highlight-color: transparent; user-select: none;"><div style="position: relative; overflow: hidden; width: 1178px; height: 400px; padding: 0px; margin: 0px; border-width: 0px; cursor: default;"></div></div><div class="v-charts-component-loading" style="display: none;"><div class="loader"><div class="loading-spinner"><svg viewBox="25 25 50 50" class="circular"><circle cx="50" cy="50" r="20" fill="none" class="path"></circle></svg></div></div></div><div class="v-charts-data-empty" style="display: none;"> 暂无数据 </div></div> </pre>

**Comment by xiguaxigua** [comment]
提供一下重现的示例吧，没有重现出您遇到的问题。

**Comment by fanyoufu** [comment]
我又试了下，inpm install v-charts@1.4.1 . 严格把v-charts设置成demo中的1.4.1版本，
```
<script src="//unpkg.com/vue/dist/vue.js"></script>
<script src="//unpkg.com/echarts/dist/echarts.min.js"></script>
<script src="//unpkg.com/v-charts@1.4.1/lib/index.min.js"></script>
````
地图就可以正常显示了。

**Comment by fanyoufu** [comment]
还是有问题。 我在这个主题中提到了，我只有使用v-charts 1.4.1版本时，map 组件才能按如下方式正常工作。

1. npm install v-chart@1.4.1  // 如果不约定这个版本，则map组件就不能正常显示。其它组件没有这个问题。
```
 //main.js
import VCharts from 'v-charts' //https://elemefe.github.io/v-charts/#/start
Vue.use(VCharts)  // 图表组件
```
在某个组件中使用map组件。
```
//hello.vue
<ve-map :data="chartData" :settings="chartSettings"></ve-map>
````

可是在@1.4.1版本中map组件不能设置 positionJsonLink这个属性。所以就郁闷了：
用@1.4.1，可以看到map组件，但positionJsonLink不能使用。
不用@1.4.1，则map组件都用不了。

**Comment by xiguaxigua** [comment]
https://codesandbox.io/s/kw129l5jlo 
试了一下没发现问题，首先看下是不是没有安装 echarts，然后看下哪里的写法不同，需要怎样能够重现。

**Comment by fanyoufu** [comment]
我自己也搞糊涂了，昨天 一天都不正常。今天却又好了。 打扰了。
