### ISSUE TITLE
直接更改数据无法实时更新

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/v-charts#2]
更改数据直接赋值chartData.rows，没有效果，需要切换图表chartSettings.type之后，就能正常显示刚刚赋值的数据

**Comment by yeahTibbers** [comment]
是不是需要暴露一个手动渲染的功能，或者自动检测数据改动？

**Comment by xiguaxigua** [comment]
在 1.1.2 版本中修复了对 data 和 settings 的 watch 判断，更新一下版本看看还有没有问题；另外，如果需要实时更新的话，需要把 chartData 放到 data 中的，这样图表才会响应数据的变化。

**Comment by yeahTibbers** [comment]
你好，chartData 一直都是放在data中的

**Comment by zhenyu-dev** [comment]
@Tibbersss 请问你解决了吗
