### ISSUE TITLE
帅帅的作者大佬，手机端数据多的话，可以实现横向滚动吗

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#205]
帅帅的作者大佬，手机端数据多的话，可以实现横向滚动吗

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/189/  这种横向滚动效果？

**Comment by 15521054523** [comment]
![image](https://user-images.githubusercontent.com/19297519/36960501-43e53eb6-2082-11e8-936a-f2c39bdf815d.png)
好像有点不对劲，我要是的，比如1月1-1月3的数据，然后手指在上面滑动可以滑过去看到1月4  1月5这样

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/196/  这样？

**Comment by 15521054523** [comment]
素的素的，爱你

**Comment by ljphawk** [comment]
请求楼主怎么配置 ? 这个链接我打不开  5555    https://jsfiddle.net/jepw6dy2/196/

**Comment by zhangshichuan** [comment]
我也打不开，科学上网也打不开

**Comment by zhangshichuan** [comment]
@9yues 老哥怎么弄的呀，我的柱状图也需要x轴滚动

**Comment by androidxu** [comment]
上面那个不是连续的啊
