### ISSUE TITLE
如何更改地图组件中 标识点的坐标位置？

### ISSUE THREAD

**Issue by fanyoufu** [ElemeFE/v-charts#209]
![1](https://user-images.githubusercontent.com/12369518/37138617-c1adb37c-22e5-11e8-84a9-e1931f0a272f.png)
如上，西南区这个点的位置靠下了，我想调整它向上一些，如何设置？ 感谢，感谢 。

**Comment by xiguaxigua** [comment]
echarts 目前好像没有提供修改这个点位置的接口，如果有需要的话，可以在 echarts 的 issues 里面咨询一下。
