### ISSUE TITLE
x轴最后一个数值显示不完整

### ISSUE THREAD

**Issue by GodStream** [ElemeFE/v-charts#210]
![image](https://user-images.githubusercontent.com/23089466/37193078-79844a3e-23a3-11e8-83c2-67768d6d1da4.png)
是否能有一种更好方式展现？

**Comment by xiguaxigua** [comment]
可以将数值进行适当的旋转
https://jsfiddle.net/m1hdcmf4/30/

**Comment by GodStream** [comment]
好的，这样可以解决问题，Thanks!
