### ISSUE TITLE
How to set up the X axis of the fold line and the line display of the Y axis?

### ISSUE THREAD

**Issue by sunterry** [ElemeFE/v-charts#211]

**Comment by xiguaxigua** [comment]
Do you mean custom axes？

 If this is the case, you can use `extend` as this demo https://jsfiddle.net/jepw6dy2/243/

**Comment by sunterry** [comment]
基于高德地图的热力图怎么设置？  可有demo？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/tvtbz29c/22/

**Comment by sunterry** [comment]
非常感谢
