### ISSUE TITLE
有没有使用markline的示例

### ISSUE THREAD

**Issue by itsmyturn** [ElemeFE/v-charts#212]
需要一个markline的示例

**Comment by xiguaxigua** [comment]
https://elemefe.github.io/v-charts/#/props-demo1?id=%e8%ae%be%e7%bd%ae%e5%9b%be%e8%a1%a8%e6%a0%87%e7%ba%bf%e4%b8%8e%e6%a0%87%e7%82%b9

**Comment by itsmyturn** [comment]
恩恩，看到这个例子了，谢谢
