### ISSUE TITLE
使用v-candle的时候，如果设置了grid会报异常

### ISSUE THREAD

**Issue by zfeidy** [ElemeFE/v-charts#214]
当我设置了grid属性后就会报错，去掉就正常了

[https://jsfiddle.net/mirrorlongdd/tecfxdg9/92/](https://jsfiddle.net/mirrorlongdd/tecfxdg9/92/)

异常内容：

> vue.js:597 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'coordinateSystem' of undefined"
>
> found in
> ---> \<VeCandle>
> \<Root>

**Comment by xiguaxigua** [comment]
candle 的 gird 是一个数组，包含 candle 的 grid 和 bar 的 grid，默认值如下

![image](https://user-images.githubusercontent.com/9931685/37501220-4ffa6710-2908-11e8-9689-9d4ee1943a15.png)

如果要修改 grid 的话，也要赋值为一个包含两个对象的数组才能生效。
