### ISSUE TITLE
急需请教的一个问题

### ISSUE THREAD

**Issue by ljh005** [ElemeFE/v-charts#216]
您好，目前我们项目正在用这个组件，很好用，但现在遇到一些小问题，文档中说到有些echarts配置项对应的属性也被加到了组件上，设置后将会直接覆盖options原有的对应属性，比如radar: Object等等这一段没看懂怎么用，关键是要设置柱状图和条形图的柱子宽度不知在哪设置，希望作者能抽点时间回答一下，万分感谢！！！

**Comment by xiguaxigua** [comment]
关于柱子宽度的设置，可以参考 #141。

**Comment by xiguaxigua** [comment]
> 有些echarts配置项对应的属性也被加到了组件上，设置后将会直接覆盖options原有的对应属性

这个主要是用于像地图这样，上面可以展示散点图，也可以展示折线图，没有固定的类型显示，所以就将 echarts 的配置提供出来，用于用户直接设置属性来实现相关功能; 或者用于配置 toolbox, dataZoom 等所有图都能够使用的控件。
折线图，柱状图，饼图等 v-charts 已经封装的图，内部会生成一份配置 options,此时如果需要修改这个 options,可以使用 extend 属性，对某个配置进行单独的修改。
