### ISSUE TITLE
能否实现这样一个效果，一组数据用不同颜色的柱子表示，参考下面的示例

### ISSUE THREAD

**Issue by itsmyturn** [ElemeFE/v-charts#218]
http://gallery.echartsjs.com/editor.html?c=xBkE_NvonZ

**Comment by xiguaxigua** [comment]
是这种效果吗 https://jsfiddle.net/vue_echarts/1Le0wps5/243/

**Comment by lihanyu** [comment]
折线的空心圆点可以改成实心的吗、线条可以改成渐变色吗

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/212/

看下是不是这种样式。
