### ISSUE TITLE
如何解决由布局带来容器宽带变化的自适应？

### ISSUE THREAD

**Issue by SkyLin0909** [ElemeFE/v-charts#22]
通过点击事件，修改了最外层布局，使得margin-left由200 --> 0时，只有div.ve-line采取了width:auto，而.ve-line>div:nth-child(1) 以及 .ve-line div canves并没有自适应，需要强制刷新浏览器才有效果。那么在封装好的ve-line组件中能否自己去触发重绘？

**Comment by xiguaxigua** [comment]
@SkyLin0909  是的，目前 v-charts 没有支持响应容器变化的图表 resize，可以先用另一种方式实现：在容器宽度之后，手动触发echarts resize事件，这样应该能达到相同的效果，效果参考下面的例子。
https://jsfiddle.net/vue_echarts/pm7peL40/1/
