### ISSUE TITLE
关于label  的fomatter自定义问题

### ISSUE THREAD

**Issue by Paul-Yellow** [ElemeFE/v-charts#221]
自定义的fomatter 会执行多次         https://jsfiddle.net/a0pep942/69/

**Comment by xiguaxigua** [comment]
是的，每个 label 在生成的时候，都会对应的调用 formatter 函数, 至于为什么会调用多余的次数，试了一下直接用 echarts 写也是会这样。

**Comment by Paul-Yellow** [comment]
echars   没有问题啊我刚在官网上改了个例子就是显示的一个    http://echarts.baidu.com/examples/editor.html?c=pie-doughnut


label: {
                normal: {
                    show: true,
                    position: 'center',
                    formatter: ({ name, data, value }) => {
                        return (1 / 2) * 100 + '%'
                    },
                    color: '#333',
                 
                }
               
            }

**Comment by Paul-Yellow** [comment]
是的  是多个重合在一起了  ，看起来像是一个

**Comment by Paul-Yellow** [comment]
还有个问题请教大神：就是怎么控制它是否重合呢？（我想让它重合在一起）

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/37697994-479183e4-2d1b-11e8-84c3-5308e3877079.png)

```
avoidLabelOverlap: false,
```

设置这个属性就可以了 https://jsfiddle.net/vue_echarts/a0pep942/82/
