### ISSUE TITLE
<ve-radar>默认是circle类型的，可以支持自定义shape类型吗？ 

### ISSUE THREAD

**Issue by sshd123** [ElemeFE/v-charts#222]
<ve-radar>默认是circle类型的，可以支持自定义shape类型吗？

**Comment by xiguaxigua** [comment]
可以通过 extend 属性配置 https://jsfiddle.net/vue_echarts/jww5fqs8/113/

**Comment by sshd123** [comment]
感谢！

**Comment by feelslive** [comment]
楼上连接打不开，我把代码贴出来
`<div id="app">
  <ve-radar :data="chartData" :settings="chartSettings" :extend="chartExtend"></ve-radar>
</div>`
`data () {
    this.chartExtend = {
      radar:{
        shape:'polygon'
      } 
    }`
