### ISSUE TITLE
我把图表放模态框modal里，渲染的时候报错can’t get dom width or height,如何处理？

### ISSUE THREAD

**Issue by lzy308516024** [ElemeFE/v-charts#224]

**Comment by xiguaxigua** [comment]
> can’t get dom width or height

这个报错是由于在 echarts 渲染时，容器的宽高未知导致的渲染失败，解决方案就是在合适的时机触发 resize 方法，至于这个合适的时机，一般是指容器的 dom 宽高改变后，在 vue 中则是容器宽高属性改变后在`$nextTick`中执行，参考示例 https://jsfiddle.net/vue_echarts/aa7ojxyt/88/

fix #225 .
