### ISSUE TITLE
npm ERR! my-v-charts@1.16.7 build: `rm -f -r lib && node build/rollup.config.js && cp -f lib/index.min.js lib/style.min.css docs/`

### ISSUE THREAD

**Issue by dlsyaim** [ElemeFE/v-charts#226]
请教下。我npm start时候。提示缺少start,
还有下面一个问题，不知道怎么编译。可以写详细点吗
D:\git\v-charts>cnpm run build

> my-v-charts@1.16.7 build D:\git\v-charts
> rm -f -r lib && node build/rollup.config.js && cp -f lib/index.min.js lib/style.min.css docs/

'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-v-charts@1.16.7 build: `rm -f -r lib && node build/rollup.config.js && cp -f lib/index.min.js lib/style.min.css docs/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-v-charts@1.16.7 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dlsyaim\AppData\Roaming\npm-cache\_logs\2018-03-23T06_30_45_764Z-debug.log

**Comment by xiguaxigua** [comment]
开发的时候使用的是`npm run dev`
rm 不是内部命令是因为 window 上默认终端没有 rm 命令，可以使用 http://cmder.net/

**Comment by dlsyaim** [comment]
谢谢。大写的赞！
