### ISSUE TITLE
Unknown custom element: <ve-chart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by dlsyaim** [ElemeFE/v-charts#227]
我直接用一个Html文件。里面这么写的。这个错误好像是提示缺少组键

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>每天用气量图表</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <style>

    </style>
    <script src="v-charts/echarts.min.js"></script>
    <script src="v-charts/index.min.js"></script>
    <script src="v-charts/vue.js"></script>

    <script>
        window.onload=function(){
            new Vue({
                el: '#app',
                data: {
                    chartSettings: {}
                },
                methods: {
                    changeType: function () {
                        this.index++
                        if (this.index >= this.typeArr.length) { this.index = 0 }
                        this.chartSettings = { type: this.typeArr[this.index] }
                    }
                },
                created: function () {
                    this.chartData = {
                        columns: ['日期', '销售额-1季度'],
                        rows: [
                            { '日期': '1月1日', '销售额-1季度': 1523 },
                            { '日期': '1月2日', '销售额-1季度': 1223 },
                            { '日期': '1月3日', '销售额-1季度': 2123 },
                            { '日期': '1月4日', '销售额-1季度': 4123 },
                            { '日期': '1月5日', '销售额-1季度': 3123 },
                            { '日期': '1月6日', '销售额-1季度': 7123 }
                        ]
                    }
                    this.typeArr = ['line', 'histogram', 'pie']
                    this.index = 0
                    this.chartSettings = { type: this.typeArr[this.index] }
                }
            })
        };
    </script>
</head>
<body>
<div id="app">
    <button @click="changeType">切换图表类型</button>
    <ve-chart :data="chartData" :settings="chartSettings"></ve-chart>
</div>
</body>
</html>

浏览器里面错误提示如下：
vue.js:597 [Vue warn]: Unknown custom element: <ve-chart> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

找不到原因

**Comment by xiguaxigua** [comment]
下面是一个直接在 html 中使用的例子，可以按照这个例子修改一下。

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div id="app">
    <ve-line :data="chartData"></ve-line>
  </div>
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
  <script src="https://unpkg.com/v-charts/lib/line.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function () {
        return {
          chartData: {
            columns: ['日期', '销售额'],
            rows: [
              { '日期': '1月1日', '销售额': 123 },
              { '日期': '1月2日', '销售额': 1223 },
              { '日期': '1月3日', '销售额': 2123 },
              { '日期': '1月4日', '销售额': 4123 },
              { '日期': '1月5日', '销售额': 3123 },
              { '日期': '1月6日', '销售额': 7123 }
            ]
          }
        }
      },
      components: { VeLine }
    })
  </script>
</body>
</html>
```

**Comment by dlsyaim** [comment]
谢谢。解决了。原因是3个JS 顺序也反了
