### ISSUE TITLE
怎么把折线图设为直线

### ISSUE THREAD

**Issue by acmeid** [ElemeFE/v-charts#228]
echarts上面说是把smooth设为false就可以，不知道v-charts封装后怎么设置

**Comment by xiguaxigua** [comment]
可以通过 extend 属性实现， http://jsfiddle.net/jepw6dy2/145

**Comment by acmeid** [comment]
非常感谢！建议文档中除了settings，也给其他props作个说明，这样应该可以减少很多简单的使用上的 Issues

**Comment by xiguaxigua** [comment]
是的，接下来会完善文档中的关于这部分的示例
