### ISSUE TITLE
It has multiline same value in the y-axis when the maximum number is 0%, and the minimum number is -0.01%

### ISSUE THREAD

**Issue by amyhuangxbd** [ElemeFE/v-charts#23]
Result is:
![tmp01929668](https://user-images.githubusercontent.com/4026511/28260585-4d562746-6b0e-11e7-8250-ac34c87e2f7f.png)
 the value is : 
`"Incomelist": [
{"yield":"0","creattime":"2017-07-05"},
{"yield":"0","creattime":"2017-07-07"},
{"yield":"0","creattime":"2017-07-10"},
{"yield":"0","creattime":"2017-07-11"},
{"yield":"-0.01","creattime":"2017-07-12"},
{"yield":"-0.01","creattime":"2017-07-13"},
{"yield":"-0.01","creattime":"2017-07-14"}]`

I think it's a bug that may need to be fixed.

**Comment by xiguaxigua** [comment]
@amyhuangxbd 
Can you show me more info about it? I code a demo and just can't reproduce this bug.
https://jsfiddle.net/vue_echarts/aa7ojxyt/18/

**Comment by amyhuangxbd** [comment]
sorry, I provided wrong data,
the data is ：
` [
        { 'yield': '0', 'creattime': '2017-07-05' },
        { 'yield': '0', 'creattime': '2017-07-07' },
        { 'yield': '0', 'creattime': '2017-07-10' },
        { 'yield': '0', 'creattime': '2017-07-11' },
        { 'yield': '-0.0001', 'creattime': '2017-07-12' },
        { 'yield': '-0.0001', 'creattime': '2017-07-13' },
        { 'yield': '-0.0001', 'creattime': '2017-07-14' },
        { 'yield': '-0.0001', 'creattime': '2017-07-17' }
      ]`

**Comment by amyhuangxbd** [comment]
[https://jsfiddle.net/od0utz9o/](https://jsfiddle.net/od0utz9o/ )

**Comment by xiguaxigua** [comment]
@amyhuangxbd  OK, I can confirm it and the new version will be published soon.

**Comment by xiguaxigua** [comment]
@amyhuangxbd 
In v1.3.2, you can add prop `digit` to limit the effective number. This number depends on your decimal places.

https://jsfiddle.net/vue_echarts/od0utz9o/2/
