### ISSUE TITLE
地图 依赖 china.json

### ISSUE THREAD

**Issue by zxfOliver** [ElemeFE/v-charts#230]
地图图表中，配置中`mapURLProfix ` 默认为`https://unpkg.com/echarts@3.6.2/map/json/`，但本地无网没法加载外网的资源，该如何引入echarts的china.json文件？

**Comment by zxfOliver** [comment]
暂时解决了

**Comment by xiguaxigua** [comment]
v1.16.8 解决了这个问题，使用方法参考示例 https://github.com/ElemeFE/v-charts/blob/70af7460e9aae9448bc98127814297cd098c2e65/examples/pages/test.vue
