### ISSUE TITLE
无法设置日期连续的 柱状图

### ISSUE THREAD

**Issue by dahua910** [ElemeFE/v-charts#232]
数据：
 { '日期': '1月1日', '成本': 1523 },
 { '日期': '1月2日', '成本': 1223 },
 { '日期': '1月3日', '成本': 2123 },
 { '日期': '1月5日', '成本': 4123 }

在柱状图下，当 xAxisType = 'value'
图像无法显示

https://jsfiddle.net/mab8sgxh/3/

**Comment by xiguaxigua** [comment]
当前版本不支持日期类型的横轴，可以在数据里面插入缺失的日期并将相应的值设置为空
