### ISSUE TITLE
如何获取 饼图 点击事件 columns中除了维度和指标外其它对应的值

### ISSUE THREAD

**Issue by liuqinzhi** [ElemeFE/v-charts#233]
数据是：
{'性别': '男', '人数': 1234, '编号': 100}
{'性别': '女', '人数': 4321, '编号': 101}
维度和指标都是默认的前2列，在点击事件中可以使用e.name和e.value获取前2列的值，有什么办法可以获取第三列‘编号’的值吗？

**Comment by xiguaxigua** [comment]
可以在赋值时，操作series，把数据绑定到对应的节点上，这样点击时就可以获取到了。

示例 https://jsfiddle.net/xzosnow7/73/

**Comment by Hnnphone** [comment]
换成 ve-bar 就不好使了
