### ISSUE TITLE
V-charts里面集成了vue-resource吗

### ISSUE THREAD

**Issue by dlsyaim** [ElemeFE/v-charts#234]
我想直接用http get来获取后台数据,不知道怎么获取。有Demo吗^_^, 大神。我看官网说用的axios获取，您这里面怎么获取后台数据。我想统一下。自己瞎折腾。这么漂亮的代码。自己用Ajax写。感觉好笨卓

**Comment by xiguaxigua** [comment]
首先，v-charts 作为图表组件是没有依赖后台获取数据的方式的，只要在获取到数据后，赋值 chartData 或者根据业务逻辑修改其他属性就可以了。另外，使用 axios 或者 vue-resource，抑或是自己写 ajax 是没有绝对的好坏之分的，某些时候，自己写 ajax 可能会体积更小，使用更方便，当然 axios 在使用时，封装了很多实用的功能，所以官网推荐使用，我们在平时开发时也使用这个库。最后，如果是自己的项目，单纯的为了学习，自己实现 ajax 模块未免不是一件好事，axios 或者 superagent、还是 vue-resource 都是基于最基本的 ajax 技术封装的，可能学会了某一个库，没过多久又被其他的库代替了，但是万变不离其中，熟练了这些最基本的东西，使用库的时候才能游刃有余，所以也就没有笨拙或灵巧了。

```js
new Vue({
  el: '#app',
  data () {
    return {
      chartData: {
        columns: ['日期', '销售额'],
        rows: []
      }
    }
  },
  methods: {
    getChartData () {
      this.$http.get('api-path').then(res => {
        this.chartData.rows = res.data
      })
    }
  },
  created () {
    this.getChartData()
  }
})
```

**Comment by dlsyaim** [comment]
谢谢。太给力了。
