### ISSUE TITLE
设置地图position为'china-cities

### ISSUE THREAD

**Issue by Hufe921** [ElemeFE/v-charts#236]
设置地图position为'china-cities的时候，渲染特别慢卡

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/38226225-080fdf8a-372b-11e8-9fca-5704cbef9dc5.png)

数据量比较大，可以在渲染时加 loading，然后在 ready 后移除 loading

https://jsfiddle.net/1fwe4tt7/125/

**Comment by Hufe921** [comment]
十分感谢，但是渲染出来后，chrome65与Edge较为卡顿，火狐流畅

**Comment by xiguaxigua** [comment]
这个就不是很好处理了，因为数据量比较大，不同浏览器可能渲染起来效果也不尽如人意，有一种解决方案可以参考一下：将使用 china-city 的图只做渲染而不支持拖动和缩放，然后增加地图的点击事件，获取点击的位置，然后加载对应的省份、城市地图和数据。

**Comment by Hufe921** [comment]
考虑到兼容性是一个好思路，感谢
