### ISSUE TITLE
地图：根据数值改变颜色深浅

### ISSUE THREAD

**Issue by roy-lau** [ElemeFE/v-charts#237]
https://jsfiddle.net/1Le0wps5/316/   这是DEMO

http://echarts.baidu.com/examples/editor.html?c=map-HK  这是我的需求目标

先谢过了 😃 😄

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/1Le0wps5/319/

**Comment by roy-lau** [comment]
@xiguaxigua 还有个奇葩的需求：**不显示地图的城市**，这个功能怎么做？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/1Le0wps5/358/

**Comment by roy-lau** [comment]
Thanks very much
