### ISSUE TITLE
请问如何使地图能够自适应，目前一旦调整窗口大小，控制台就报错。

### ISSUE THREAD

**Issue by 188007803** [ElemeFE/v-charts#24]
![qq 20170718103016](https://user-images.githubusercontent.com/10063364/28298210-8aa1897e-6ba4-11e7-94c4-1bc5c99c2b66.png)
![qq 20170718103158](https://user-images.githubusercontent.com/10063364/28298265-c6a0f34c-6ba4-11e7-80d6-6b1ba5d37384.png)

**Comment by xiguaxigua** [comment]
@188007803  首先，v-charts 现在不支持地图，另外，根据你提供的这两条信息没有办法重现问题，如果方便的话最好是写一个在线的例子(jsfiddle, codepen)，或者是抽离出一份主要的代码。

**Comment by 188007803** [comment]
报歉，我写错了，我指的就是普通的图表，不是地图。
不过今天现在又不报错了，谢谢。
