### ISSUE TITLE
请问怎么从后台获取数据,我获取到 lists且数据正确,但是无法生成图像

### ISSUE THREAD

**Issue by luoxulx** [ElemeFE/v-charts#240]
export default {
  components: {
    Chart,VeLine
  },
  data() {
    return {
      statistics: {},
      lists:[]
    }
  },
  mounted() {
    this.$http.get('statistics').then((response) => {
        this.statistics = response.data
        this.lists = response.data.aaaa//这里已经获取到正确的 lists
      })
  },
  created: function () {
        console.log(this.lists)

        this.chartData = {
          columns: ['PV', 'UV', 'IP', 'date'],
          rows: lists//但是这里 lists却是一个空的Object
        }
        this.chartSettings = {
          metrics: ['PV', 'UV','IP'],
          dimension: ['date'],
          legendName:'访问统计'
        }
        var self = this
        this.chartEvents = {
            click: function (e) {
                self.name = e.name
                console.log(e)
            }
        }
        
      }
}

**Comment by xiguaxigua** [comment]
把 chartData 放到 data 里面

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/38658974-d448750a-3e59-11e8-9c0f-b9a0d5f9d6d3.png)

是否引入了 toolbox 模块？

**Comment by luoxulx** [comment]
引入了
import Chart from 'home/components/Chartjs.vue'
import VeLine from 'v-charts/lib/line'
import 'echarts/lib/component/toolbox'
这样的

**Comment by xiguaxigua** [comment]
测试了一下没重现问题 https://codesandbox.io/s/kw129l5jlo

检查一下 v-charts 的版本是最新的吗？

**Comment by luoxulx** [comment]
很感谢,我把this.toolbox = {......}这部分放到了this.chartSettings = {.....};之前,问题就解决了,放到后面,又没了,后台框架是laravel5.6,前端vue2.x
现在这样是可以的:  
export default {
        components:
        {
            Chart,
            VeLine
        },
        data() {
            return {
                statistics: {},
                chartData: {
                    columns: ['PV', 'UV', 'date'],
                    rows: []
                }
            }
        },
        mounted() {
            this.$http.get('statistics').then((response) => {
                this.statistics = response.data
                this.chartData.rows = this.statistics.lists
            })
        },
        created: function() {
            this.toolbox = {
                feature: {
                    magicType: {
                        type: ['line', 'bar']
                    },
                    saveAsImage: {}
                }
            };
            this.chartSettings = {
                metrics: ['PV', 'UV'],
                dimension: ['date'],
                legendName: '访问统计demo'
            };
            var self = this
            this.chartEvents = {
                click: function(e) {
                    self.name = e.name
                    console.log(e)
                }
            }
        }
    }
