### ISSUE TITLE
v-charts图表的标题疑问

### ISSUE THREAD

**Issue by luoxulx** [ElemeFE/v-charts#241]
请问有什么办法可以在 图示箭头处插入y轴标题吗? 如 单位:元
![image](https://user-images.githubusercontent.com/35016570/38722097-65482e08-3f2f-11e8-85ec-1bdd621a872f.png)
@sofish

**Comment by xiguaxigua** [comment]
设置标题的方法可以参考文档上的这个例子

https://v-charts.js.org/#/line?id=%E8%AE%BE%E7%BD%AE%E5%8F%8Cy%E8%BD%B4

**Comment by luoxulx** [comment]
感谢,已解决...
原谅我是个菜鸟,,,麻烦您再指点一下我的另一个疑问:
![image](https://user-images.githubusercontent.com/35016570/38732292-4bd36278-3f50-11e8-9a8d-96a76bba0ef1.png)

![image](https://user-images.githubusercontent.com/35016570/38732530-076d4012-3f51-11e8-8565-8e6f4bf16d7d.png)
