### ISSUE TITLE
legend default setting

### ISSUE THREAD

**Issue by ihoment-amu** [ElemeFE/v-charts#243]
in echart,i can use legend:selected to setting a example's legend, but in v-echart how could deal with this ev.

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/454/
As this example, you can use `extend` prop to set echarts options attribute.

**Comment by ihoment-amu** [comment]
but how can i set a function to set selected replace set a statable obj value
------------------------------------------------------------------发件人：西瓜 <notifications@github.com>发送时间：2018年4月18日(星期三) 10:41收件人：ElemeFE/v-charts <v-charts@noreply.github.com>抄　送：陈绵山 <mianshan.chen@ihoment.com>; Author <author@noreply.github.com>主　题：Re: [ElemeFE/v-charts] legend default setting (#243)
https://jsfiddle.net/jepw6dy2/454/

As this example, you can use extend prop to set echarts options attribute.

**Comment by xiguaxigua** [comment]
Do you want to provide the ability of change legend to user, check if this demo suit your requirement.

https://jsfiddle.net/jepw6dy2/513/
