### ISSUE TITLE
折线图如何显示最后一个元素的label？

### ISSUE THREAD

**Issue by hackwindqq** [ElemeFE/v-charts#244]
在文档页面 https://v-charts.js.org/#/line  中
【显示指标数值】 这个例子里，设置 show:true可以显示坐标点的数值，但是最靠右的元素时没有的，需要将鼠标移上去才可以，请问怎么解决这个问题？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/462/ 是这种样式吗？

**Comment by Spring456** [comment]
使用直角坐标系grid，调整right的值即可
