### ISSUE TITLE
鼠标hover样式

### ISSUE THREAD

**Issue by wangcch** [ElemeFE/v-charts#245]
可以修改鼠标hover事件的图表高亮样式吗，打扰了

**Comment by xiguaxigua** [comment]
可以说的具体点吗，哪种类型的图表、hover在什么模块上、以及需要定制为什么样的样式？

**Comment by wangcch** [comment]
感谢回复～举个栗子，我现在饼图和柱状图有个色块颜色较淡(#e5e5e5)，hover色块会高亮，这时候就会变成白色，有什么解决方法吗？禁用或者修改样式。打扰了

**Comment by wangcch** [comment]
如果这样呢？https://jsfiddle.net/tecfxdg9/148/

**Comment by xiguaxigua** [comment]
指定一个具体的 hover 颜色可以解决这个问题 https://jsfiddle.net/tecfxdg9/151/

**Comment by wangcch** [comment]
可以单个指定么，或者显示和默认的(defaultColor)一样

**Comment by xiguaxigua** [comment]
文档上似乎没有提供单独的颜色指定方法 http://echarts.baidu.com/option.html#series-pie.emphasis.itemStyle.color

**Comment by wangcch** [comment]
是的，我也看到了，所以很苦恼。echarts 也搜了一下，说是“emphasis设置成一样的即可”以禁用hover高亮，但是怎么一样😅
