### ISSUE TITLE
去横向网格

### ISSUE THREAD

**Issue by greenmonking** [ElemeFE/v-charts#248]
你好，柱状折线集合的图，后面的横向网格很乱，我想去掉其中一个的横向网格，
`yAxis:{
          	type: 'value',
                splitLine:{show:false},
          }`
	
  这样可以去掉所有横向网格
`yAxis:[
          {
          		type: 'value',
			name: '数值',
          },
          {
          		type: 'value',
			name: '比率',
                        splitLine:{show:false},
          },
        ]`
	

这样就不起作用      ，急求

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/548/

**Comment by greenmonking** [comment]
https://jsfiddle.net/he1u3j75/172/
我是想去掉比率的网格，不然网格太杂乱了

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/he1u3j75/173/
https://jsfiddle.net/he1u3j75/174/

是上面示例的效果吗？

**Comment by greenmonking** [comment]
是的是的，谢谢啦
