### ISSUE TITLE
Unselecting elements from radar chart changes the other element's colors but it's not reflected in the legend

### ISSUE THREAD

**Issue by smares** [ElemeFE/v-charts#25]
On the example page https://elemefe.github.io/v-charts/#/radar, if you uncheck some of the elements, the chart re-renders and the elements displayed in the chart change their color. However, this color change is not reflected in the legend.

1. Initially, 1月1日 is green, 1月2日 blue, 1月3日 red, 1月4日 yellow, 1月5日 dark blue and 1月6日 violet.
2. Unselect everything except 1月3日
--> In the legend, 1月3日 is still red, but in the chart, it's green.

**Comment by xiguaxigua** [comment]
@smares OK, I can confirm it.

**Comment by xiguaxigua** [comment]
@smares  This problem has been fixed in v1.5.0.
https://jsfiddle.net/jww5fqs8/4/
