### ISSUE TITLE
地图组件的属性没有响应series属性的变更

### ISSUE THREAD

**Issue by jeange1003** [ElemeFE/v-charts#250]
https://jsfiddle.net/jeange1003/znn0gv9a/
手动setOption可以的

**Comment by jeange1003** [comment]
呃，试了下，如果watch series deep=true的话，会重绘地图😂

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/znn0gv9a/5/  升级一下版本试试

**Comment by jeange1003** [comment]
恩，的确能响应series的改动了，但是这样会导致地图的重新加载。
在用户已经缩放的情况下，修改series，会导致地图重新加载，而回到最初设置的zoom level。

直接调用echarts的setOption并不会重新加载地图。

**Comment by ZyqGitHub1** [comment]
v1.17.0版本地图组件修改series不会显示数据

**Comment by xiguaxigua** [comment]
@ZyqGitHub1 在组件上增加 `:set-option-opts="false"` 试试。
https://jsfiddle.net/znn0gv9a/15/

**Comment by ZyqGitHub1** [comment]
@xiguaxigua 增加`:set-option-opts="false"`选项后问题解决了，非常感谢
