### ISSUE TITLE
请问radar图中如何设置每个data的lineStyle和areaStyle，echarts是在series.data里面，v-charts的chartSettings里，貌似只能设置一个颜色，是不是我写的不对呢？

### ISSUE THREAD

**Issue by sshd123** [ElemeFE/v-charts#252]
请问radar图中如何设置每个data的lineStyle和areaStyle，echarts是在series.data里面，v-charts的chartSettings里，貌似只能设置一个颜色，是不是我写的不对呢？

**Comment by xiguaxigua** [comment]
是这种效果吗？ https://jsfiddle.net/jww5fqs8/130/

**Comment by sshd123** [comment]
是的，灰常感谢！

**Comment by Jarvis1995** [comment]
> 是这种效果吗？ https://jsfiddle.net/jww5fqs8/130/

series(item)  这是什么写法?
是下面这样吗:
const series = function(item){
console.log(item) //打印不出东西
}
求教
