### ISSUE TITLE
柱状图+折线图：修改柱状图的宽度，会把折线图变成柱状图

### ISSUE THREAD

**Issue by urnorchrislee** [ElemeFE/v-charts#253]
![image](https://user-images.githubusercontent.com/12442665/39239871-c45d0f42-48b4-11e8-8d1c-a427e2e48734.png)

使用柱状图+折线图组合，通过chartExtend的series属性修改柱子的宽度，折线图变成了柱状图？？？

**Comment by xiguaxigua** [comment]
这种修改是对所有的 series 下的对象都有效的，如果要修改单独的某一个 series 下的对象，可以赋给 series 一个函数，在函数内进行操作。

**Comment by urnorchrislee** [comment]
https://v-charts.js.org/#/props-demo2 ---> 设置extend配置项
