### ISSUE TITLE
chartData 放到 data 动态更新数据，有例子吗

### ISSUE THREAD

**Issue by dlsyaim** [ElemeFE/v-charts#254]
在 1.1.2 版本中修复了对 data 和 settings 的 watch 判断，更新一下版本看看还有没有问题；另外，如果需要实时更新的话，需要把 chartData 放到 data 中的，这样图表才会响应数据的变化。
chartData 放到 data 动态更新数据，有例子吗，小白一个，还请大神百忙之中，稍微指点下，给个Demo

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/553/ 不知道这个例子能否满足你的需要
