### ISSUE TITLE
百度地图散点图，窗口最大化时，散点位置漂移

### ISSUE THREAD

**Issue by VincentZhao** [ElemeFE/v-charts#257]
使用下面的官方例子即可再现
https://jsfiddle.net/vue_echarts/tvtbz29c/1/

最大化浏览器窗口时，点的位置就不对了
拖动地图或resize浏览器窗口即可恢复

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/tvtbz29c/66/ 加个 resize 监听试试看效果能否满足需求

**Comment by xiguaxigua** [comment]
```js
setTimeout(() => {
  this.$refs.chart.resize()
}, 100)
```

增加一下延迟时间

**Comment by VincentZhao** [comment]
OK了 :smile:
