### ISSUE TITLE
afterConfig会响应多次

### ISSUE THREAD

**Issue by povs2012** [ElemeFE/v-charts#258]
异步加载数据的时候，只是改变了数据的rows，afterConfig会响应多次
[https://jsfiddle.net/vf2vuzqq/12/](url)
跟踪调试发现是在watch props的时候进入dataHandler的，dataHandler函数设置成debounce函数会不会更好？

**Comment by xiguaxigua** [comment]
我看了一下你的例子，每次刷新都会导致两次 afterConfig, 导致这样的原因是同时修改了chartData 和 loading ，不过 loading 的修改不应该重新加载图表的，稍等会发一个版本修复这个问题。

**Comment by povs2012** [comment]
我这个只是一个例子，在我实际使用中并不仅仅重新加载两次，如果我的图表的title直接写在template模板中，`<ve-line :title="{text: title, left: 'center'}"></ve-line>`类似这种写法，修改数据也会导致afterConfig触发多次，在我实际的工程中甚至出现只是异步修改数据，afterConfig触发了8次，我建议还是加一个几十毫秒的debounce延时可能会更好一点。

**Comment by xiguaxigua** [comment]
升级到 v1.16.11 就可以了
