### ISSUE TITLE
怎么修改柱状图里面柱的颜色

### ISSUE THREAD

**Issue by wangzy123** [ElemeFE/v-charts#26]

**Comment by xiguaxigua** [comment]
@wangzy123 
可以通过设置图表的颜色列表实现
```html
<ve-histogram :data="chartData" :colors="colors"></ve-histogram>

this.colors = ['#c23531','#2f4554', '#61a0a8', '#d48265', '#91c7ae','#749f83',  '#ca8622', '#bda29a','#6e7074', '#546570', '#c4ccd3']
```
参考 https://jsfiddle.net/vue_echarts/1Le0wps5/23/

**Comment by tonywangcn** [comment]
这种方式貌似只能更改 columns 的颜色，如何修改 rows 的颜色呢？不同 row 不同颜色

**Comment by spademan** [comment]
@tonywangcn，最后你是怎么解决的？

**Comment by xiguaxigua** [comment]
#90

**Comment by tonywangcn** [comment]
@spademan https://github.com/ElemeFE/v-charts/issues/90

**Comment by wangcch** [comment]
如果目标种类不可控，种类数目可以达到百位量级，自定义一个颜色。怎么处理比较好，需要定义上百个颜色吗

**Comment by xiguaxigua** [comment]
颜色的多少可以自己控制，假设需要展示100个，只定义了5种颜色，那么就会循环这5种颜色来渲染。

**Comment by wangcch** [comment]
哇～，感谢回复。但是假如我有一个键指定特定颜色呢

**Comment by xiguaxigua** [comment]
一个键？是统一指标下的某一个柱子？还是多个指标中的某一个指标？

**Comment by wangcch** [comment]
比如饼图，['类型', '数量'] ，类型数量不可控的情况下，中有一个'unknown'情况，我们需要指定它显示为 ‘灰色’，这样可以吗

**Comment by xiguaxigua** [comment]
是这种样式吗？ https://jsfiddle.net/tecfxdg9/121/

**Comment by wangcch** [comment]
完美，非常感谢
