### ISSUE TITLE
父组件传给子组件高度 子组件监听高度的变化而变化这里有一点点小问题

### ISSUE THREAD

**Issue by hzyy** [ElemeFE/v-charts#262]
`大佬能帮我看一下吗O(∩_∩)O！

<template>
  <ve-histogram :data="chartData" :legend="legend" :settings="chartSettings" ref="chart" :height="height" ></ve-histogram>
</template>

<script>

  export default {
    data() {
      return {
        chartData:{
          columns: ['日期', '成本',],
          rows: [
            {'日期': '1月1日', '成本': 1523, '利润': 1523, '占比': 0.12, '其他': 100},
            {'日期': '1月2日', '成本': 1223, '利润': 1523, '占比': 0.345, '其他': 100},
            {'日期': '1月3日', '成本': 2123, '利润': 1523, '占比': 0.7, '其他': 100},
            {'日期': '1月4日', '成本': 4123, '利润': 1523, '占比': 0.31, '其他': 100},
            {'日期': '1月5日', '成本': 4123, '利润': 1523, '占比': 0.31, '其他': 100},
            {'日期': '1月6日', '成本': 4123, '利润': 1523, '占比': 0.31, '其他': 100},
            {'日期': '1月7日', '成本': 4123, '利润': 1523, '占比': 0.31, '其他': 100},
            {'日期': '1月8日', '成本': 4123, '利润': 1523, '占比': 0.31, '其他': 100},
          ]
        },
        legend : {
          show:false
        },
        height:'200px',
        chartSettings: {
          yAxisType: ['KMB'],
          yAxisName: ['数值'],
        },
      };
    },
    props: ['ChartHeight'],
    created: function () {

    },
    watch: {
      ChartHeight(newValue, oldValue) {
        if (newValue != 0) {
          this.height = newValue+'px'
          this.$refs[`chart`].resize();
        }
      }
    },
    methods:{
    }
  }

</script>`

**Comment by xiguaxigua** [comment]
需要在 nextTick 中执行 resize ， 示例 https://jsfiddle.net/aa7ojxyt/191/ 。

**Comment by hzyy** [comment]
谢谢有了   我还想问一下  echart里面的stepLine  http://echarts.baidu.com/examples/editor.html?c=line-step用这个v-charts能否实现呢  开关量的监测吧用折线图不太直观

**Comment by xiguaxigua** [comment]
可以使用 extend 实现 https://jsfiddle.net/aa7ojxyt/194/，
step 的参数选择参考 http://echarts.baidu.com/option.html#series-line.step

**Comment by hzyy** [comment]
谢谢啦

**Comment by xiguaxigua** [comment]
逗号的问题，再打开试试。

**Comment by hzyy** [comment]
谢谢  有啦
