### ISSUE TITLE
没办法动态切换数据展示

### ISSUE THREAD

**Issue by vasesen** [ElemeFE/v-charts#264]
本想通过 一个切换按钮 点击一年时 让折线图 展示一年数据，点击半年时 展示半年数据 。在点击事件了 写了 
      this.chartData = this.halfYear;
      this.chartSettings ={}  但是折线图 不会跟新！ 我把crated（）里赋值代码 写在mouted 发现 初始化 也不能让折线图展示 ！是不是赋值和生命周期有关系，我这种动态切换 应该怎想实现

**Comment by xiguaxigua** [comment]
chartData 要放到 data 中
```
export default {
  data () {
    return {
      chartData: { ...  }
    }
  }
}
```
