### ISSUE TITLE
请问在折线图中，往往最右边的横坐标以及图表数值都被截取了。只能显示一半，怎么处理呢？

### ISSUE THREAD

**Issue by Spring456** [ElemeFE/v-charts#265]
https://v-charts.js.org/#/line   案例中，显示指标数值，最右边的日期和数值都被截取了。   请问如何设置？在公司的项目中，除了我自己的电脑外，其他同事的电脑上都显示不全。能否设置？

**Comment by xiguaxigua** [comment]
两种方式：
旋转横坐标：jsfiddle.net/aa7ojxyt/193
竖排横坐标：jsfiddle.net/aa7ojxyt/192

**Comment by Spring456** [comment]
谢谢回复，已解决。坐标旋转被产品经理否决，采用的是grid，给了一个right，

**Comment by gdmec07150942** [comment]
请问如何设置x轴字体大小呢

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/bbyL2Ln4/
