### ISSUE TITLE
xAxisType: 'value'  无效怎么办？ 试了好几次了，和官网一样                            

### ISSUE THREAD

**Issue by heroes7** [ElemeFE/v-charts#267]
this.chartSettings = {
                                        xAxisType: 'value'
                                    }

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/558/

看上去是没问题的，横轴按照数值大小递增显示。提供一个重现你遇到问题的示例吧。

**Comment by heroes7** [comment]
`                        //             columns: ['月份', '去年', '今年'],
                        //             rows: [
                        //                 { '月份': '1月',  '去年': 1000000, '今年': 2002000 },
                        //                 { '月份': '2月',  '去年': 4000000, '今年': 3002000 },
                        //                 { '月份': '3月',  '去年': 3000000, '今年': 9002000 },
                        //                 { '月份': '4月',  '去年': 1000000, '今年': 1002000 },
                        //                 { '月份': '5月',  '去年': 1000000, '今年': 1002000 },
                        //                 { '月份': '6月',  '去年': 1000000, '今年': 12000000 },
                        //                 { '月份': '7月',  '去年': 4000000, '今年': 1002000 },
                        //                 { '月份': '8月',  '去年': 1000000, '今年': 8002000 },
                        //                 { '月份': '9月',  '去年': 1000000, '今年': 4002000 },
                        //                 { '月份': '10月', '去年': 1000000, '今年': 2002000 },
                        //                 { '月份': '11月', '去年': 1000000, '今年': 3002000 },
                        //                 { '月份': '12月  ', '去年': 5000000, '今年': 6002000 }
                        //             ]`

我这样的数据有问题吗，只要 用了我的这个  数据   加上 xAxisType: 'value'  失效了  曲线图也没了。

**Comment by heroes7** [comment]
columns: ['月份', '去年', '今年'], 
rows: [
       { '月份': '1月',  '去年': 1000000, '今年': 2002000 },
       { '月份': '2月',  '去年': 4000000, '今年': 3002000 }
//我是想显示十二个月   剩下的省略
]

数组变成我这样，在加 xAxisType: 'value'   那么曲线图就不显示了。不知道为什么

**Comment by heroes7** [comment]
@xiguaxigua  我发现，我只要加了月在跟在数字后边，在加上 xAxisType: 'value'    那么曲线就没了。。去了月字就有数字显示了，可我想要十二个月一次排列 小哥哥 求救

**Comment by heroes7** [comment]
@xiguaxigua    https://jsfiddle.net/jepw6dy2/561/      把注释打开  就无效了，感觉是BUG  去掉月字就可以

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jepw6dy2/563/

**Comment by heroes7** [comment]
@xiguaxigua  为什么显示的月份，都是 1 2 4 6 8 10 12  其它的都没显示。怎么显示全部。

**Comment by xiguaxigua** [comment]
tooltip 里面的显示不正确？
如果是的话，可以参考这个例子修改 https://jsfiddle.net/jepw6dy2/564/

**Comment by heroes7** [comment]
@xiguaxigua  把横线去掉 月份就显示全了，就这样吧。我已经递交给程序了，经理也没说什么。(lll￢ω￢)  谢谢作者的耐心讲解，非常感动。
