### ISSUE TITLE
增加axisSite后，如何加上左右Y轴数值的颜色？

### ISSUE THREAD

**Issue by ljh005** [ElemeFE/v-charts#269]
如题，目前已经加上左右Y轴，还想左边Y轴值是蓝色，右边是红色，但用了extend后 设置visitExtend: {
          yAxis:[
            {
              type: 'value',
              axisTick: { show: false },
              axisLine: {
                show: true,
                lineStyle: {
                  color: '#ff5454',
                  fontSize: 12,
                  width: 0
                }
              }
            },
            {
              type: 'value',
              axisTick: { show: false },
              axisLine: {
                show: true,
                lineStyle: {
                  color: '#20a8d8',
                  fontSize: 12,
                  width: 0
                }
              }
            }
          ]
        },加不上颜色，如果不用数组
visitExtend: {
          yAxis: 
          {
            type: 'value',
            axisTick: { show: false },
            axisLine: {
              show: true,
              lineStyle: {
                color: '#ff5454',
                fontSize: 12,
                width: 0
              }
            }
          }
        },这样两边都是红色，请指点下如何做

**Comment by xiguaxigua** [comment]
可以使用函数的方式解决这个问题 https://jsfiddle.net/jepw6dy2/566/

**Comment by ljh005** [comment]
非常感谢能这么快速回复我的问题
