### ISSUE TITLE
请问可以支持TreeMap类型的图表么

### ISSUE THREAD

**Issue by Billiballa** [ElemeFE/v-charts#271]
如题。。希望实现TreeMap的效果但是没看到例子。。是还未做这种类型的支持么？或者有什么方法可以自主配置实现？
这里是[TreeMap](http://echarts.baidu.com/examples/index.html#chart-type-treemap)的Echarts官方例子。。

**Comment by xiguaxigua** [comment]
当前版本还不支持这种类型的图，会在2.0版本提供支持，大概会在6月发布。

**Comment by Billiballa** [comment]
那就期待下个版本尽早发布了~
