### ISSUE TITLE
k线图怎么修改tooltip文字？

### ISSUE THREAD

**Issue by donne1226** [ElemeFE/v-charts#273]
![pic](https://raw.githubusercontent.com/donne1226/donne1226.github.io/master/Snipaste_2018-05-16_15-50-17.png)

如图 英文要变成中文，我试了labelMap 无效，另外k线图能做一小时线吗？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/g98g02ah/67/

英文要变成中文 的问题更新一下版本就可以了。

k线图能做一小时线 如果是要展示以小时为单位的 K线只要数据传小时就可以了。

**Comment by donne1226** [comment]
`
"echarts": "^4.1.0",
"v-charts": "^1.16.11"
`
我这版本已经显示最新了。哪里不对吗？

**Comment by xiguaxigua** [comment]
1.16.12

**Comment by donne1226** [comment]
非常感谢这么快修复发布新版本！！点赞！
