### ISSUE TITLE
k线图使用markPoint.valueDim 报错

### ISSUE THREAD

**Issue by donne1226** [ElemeFE/v-charts#274]
Cannot read property 'dim' of undefined

**Comment by xiguaxigua** [comment]
提供一下重现示例吧(jsfiddle 或者 codepen)

**Comment by donne1226** [comment]
https://jsfiddle.net/donne1226/vahmgnd9/

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vahmgnd9/3/

**Comment by xiguaxigua** [comment]
组件上的 mark* 会添加到每个 series 中，如果只是需要增加到 k 线图上的话，可以使用 extend 属性实现。

**Comment by donne1226** [comment]
ok,解决了！thanks
