### ISSUE TITLE
如何利用富文本标签在X轴添加天气图标？

### ISSUE THREAD

**Issue by ljh005** [ElemeFE/v-charts#277]
![image](https://user-images.githubusercontent.com/16408828/40220529-07c155fa-5aac-11e8-91c4-59e36d3d4501.png)
如图，因为天气是动态的，日期也是动态的，我该怎么实现？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/206/

**Comment by ljh005** [comment]
非常感谢！！！
