### ISSUE TITLE
X轴数据能直接用unixstamp 格式么，type设置为time,貌似不对

### ISSUE THREAD

**Issue by ryansecret** [ElemeFE/v-charts#278]

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/jepw6dy2/577/

当前的版本不支持时间戳，可以先格式化一下时间然后再传给组件。

**Comment by firesh** [comment]
支持时间戳的。
关键代码
HTML
`      <ve-line :data="chartData" :settings="chartSettings" height="600px"></ve-line>
`
JS
`chartSettings = {
        dimension: ['createTime']
        xAxisType: 'time'
}`
@ryansecret
