### ISSUE TITLE
百度地图有一个很奇怪的bug，有复现的demo，同时after-set-option-once这个属性的判断不严谨

### ISSUE THREAD

**Issue by wangweida** [ElemeFE/v-charts#279]
我看源码中
```
if (this.afterSetOptionOnce && !this._once['afterSetOptionOnce']) {
  this._once['afterSetOptionOnce'] = this.afterSetOptionOnce(this.echarts)
}
```
是这么判断的，这种判断不是很严谨，因为当传入的函数没有返回值的情况下，此函数依然会被调用，比如在百度地图获取实例的例子中，就afterset函数就没有返回值，并不能保证只能调用一次。

另外我发现了vebmap这个组件中貌似存在一些问题，我具体没有找到是什么原因引起的，请看这个[例子](https://jsfiddle.net/tvtbz29c/70/)。不知道为什么每次点击的li的时候都会触发组件内的datahandler导致echarts实例变更，不能绘制想要的坐标点。我自己实验过了，只有vebmap组件会有这个情况，线图什么的都完全不会重新触发dataHandler这个函数。

我找了两个小时，终于发现了问题的原因...
```
<ve-bmap
    :settings="chartSettings"
    :after-set-option-once="afterSet"
    :tooltip="{ show: true }">
</ve-bmap>
```
文档中这个例子实在是有点不严谨...一个是afterset没有返回值会导致多次触发afterset函数，第二是tooltip的值直接在模板中写成了{show: true}，而源码中的addWatchToProps函数把tooltip给深度watch了，导致只要vue实例中有已经双绑的状态改变就会触发tooltip的watchhandler...

**Comment by xiguaxigua** [comment]
感谢您的反馈，问题已经在新版本中被修复，文档中的问题也已经更新。
