### ISSUE TITLE
求助:图表放到TAB里刷新时显示有问题

### ISSUE THREAD

**Issue by buershero** [ElemeFE/v-charts#28]
元素存在，但需要改动窗口大小，才可以显示图表，求帮忙解决 
案例：https://codepen.io/wangyan-g/pen/QMWpWQ?editors=1010

**Comment by xiguaxigua** [comment]
@buershero 
这个问题看起来更像是`tabs`组件引起的，在组件渲染的时候，`chart`所在的`dom`节点，在`chart` 生成的时候宽度并不是 100%，从而图表没有渲染出来，一个简单的解决办法是在`mounted`之后手动触发一次`chart`的`resize`方法，这样，图表就能正常显示出来了。
案例：https://codepen.io/quietcoder/pen/JyjWvG?editors=1010

**Comment by buershero** [comment]
谢谢解答！赞！
