### ISSUE TITLE
Last value on x-axis is not showing properly

### ISSUE THREAD

**Issue by tekbahadur1996** [ElemeFE/v-charts#280]
The last value on x-axis is not showing properly. It got cut in half even with some padding.
check the right bottom corner of the images. Please fix this.
![selection_053](https://user-images.githubusercontent.com/20125603/40266935-0cc3a38e-5b72-11e8-8d37-7cfdc6bb8a2f.png)
![selection_054](https://user-images.githubusercontent.com/20125603/40266936-13752e1e-5b72-11e8-967e-624c5a969d24.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/jepw6dy2/578/
https://jsfiddle.net/vue_echarts/jepw6dy2/579/
