### ISSUE TITLE
请问怎么实现柱状图与散点图组合显示？

### ISSUE THREAD

**Issue by snailg** [ElemeFE/v-charts#282]
请问怎么实现柱状图与散点图组合显示？包括调整柱状图的barGap，设置了0还是显示很大，如下图。

![tim 20180521153717](https://user-images.githubusercontent.com/5671609/40295703-ec4c320a-5d0c-11e8-9343-8c34950ae434.png)

**Comment by xiguaxigua** [comment]
下面这个例子是假设指标中的成本展示位散点图的例子，看看是否符合需求。

https://jsfiddle.net/vue_echarts/1Le0wps5/385/
