### ISSUE TITLE
地图组件series变化，直接重新渲染地图，感觉太过暴力

### ISSUE THREAD

**Issue by loyalove** [ElemeFE/v-charts#283]
添加在地图中的对象过多时，重新渲染整个地图开销太大

**Comment by xiguaxigua** [comment]
更新一下版本 (v1.16.15)，然后在组件上增加 `:set-option-opts="false"` 试试看能否解决你的问题

https://jsfiddle.net/vue_echarts/1fwe4tt7/183/

**Comment by xiguaxigua** [comment]
修复了，更新一下版本。

https://jsfiddle.net/vue_echarts/kv3a5ms0/2/

**Comment by loyalove** [comment]
效率点赞，完美解决
