### ISSUE TITLE
柱状图  如何指定纵坐标的递增值不是小数

### ISSUE THREAD

**Issue by liuqinzhi** [ElemeFE/v-charts#284]
请问，有什么方法能让纵坐标不显示小数吗？
如下图，纵坐标代表的是人数，出现0.2等小数值是不合理的。

![image](https://user-images.githubusercontent.com/31839895/40337744-e54303c0-5da3-11e8-8aec-ab4684855ff1.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/208/
是这种样式吗？

**Comment by liuqinzhi** [comment]
这样也是解决办法。多谢了啊 @xiguaxigua
