### ISSUE TITLE
请问下x轴时间显示和绑定数据不一致，是什么情况，显示时间为 01-02

### ISSUE THREAD

**Issue by ryansecret** [ElemeFE/v-charts#289]

**Comment by xiguaxigua** [comment]
提供一下重现的示例吧，或者是配置项和数据的格式

**Comment by ryansecret** [comment]
找到问题了， 是xAxis 中type 设置为 time的问题，还要设置 setting 的xAxisType，难道不是会xAxis中的配置会覆盖么

**Comment by xiguaxigua** [comment]
组件上设置 xAxis 替换掉内部生成的 options.xAxis, 一般不建议直接设置组件上的属性，大部分功能都可以通过 settings 内的配置，或者 extend 属性来实现。
