### ISSUE TITLE
关于自定义主题

### ISSUE THREAD

**Issue by ocean-7** [ElemeFE/v-charts#29]
非常感谢饿了么团队为vue生态做的贡献，你们的ElementUI真的为我们带来了很多的便利。
最近我们在做图表控件的选型，在vue-echarts，vue-echarts-v3和v-charts之间徘徊。我想问的是：

1. v-charts支持配置全局主题吗？类似于Echarts.registerTheme(json)
2. Echarts的灵活性很高，可配置参数非常多，v-charts支持的配置参数是不是全部能覆盖到呢？

非常希望能得到你们的回复，谢谢。

**Comment by xiguaxigua** [comment]
首先感谢你的肯定，
1，在v1.6.1版本后，支持在组件上通过使用`theme`来自定义主题；
2，v-charts的定位是基于我们在业务中常见的使用场景加以扩展，目的是为了在常用的使用场景中，减轻配置上的麻烦，当然，v-charts也支持通过`after-config`来修改最后交给echarts渲染的`options`，从而能够实现文档上所列出的可配置参数修改，但如果需求很复杂，就会有一大坨的afterConfig，这并不是v-charts的本意，如果要实现类似折线图个柱状图结合，折线图和地图结合这样的复杂需求的话，这个时候不要用`v-charts`，使用vue-echarts-v3，在其上自己封装一个组件反而可能会更加适合你的使用场景。
