### ISSUE TITLE
不同router下的多个ve-bmap实例，百度地图api.js会重复请求

### ISSUE THREAD

**Issue by loyalove** [ElemeFE/v-charts#291]
### Summary 简述
创建多个ve-bmap实例，百度地图api.js会重复请求
https://api.map.baidu.com/api?v=2.0&ak=oBvDtR6nzWtVchkY4cLHtnah1VVZQKRK&callback=bmap1527145769936

### Expect 期望结果
百度地图api.js只应该请求一次

### Reproduce 重现示例

![qq 20180524151537](https://user-images.githubusercontent.com/11372459/40470190-56fec874-5f65-11e8-9507-4ebe35a82467.png)

**Comment by xiguaxigua** [comment]
可以在全局引入地图的依赖，然后在组件的 settings 中设置 useOuterMap: true,

http://jsfiddle.net/vue_echarts/tvtbz29c/82/
