### ISSUE TITLE
折线图 数据展示

### ISSUE THREAD

**Issue by lihanyu** [ElemeFE/v-charts#293]
折线图可以像下图那样展示数据吗
![image](https://user-images.githubusercontent.com/3992478/40473993-62375098-5f70-11e8-8926-008691b2f873.png)
![image](https://user-images.githubusercontent.com/3992478/40474184-f14c9928-5f70-11e8-8d8c-739f82006993.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/aa7ojxyt/213/

**Comment by lihanyu** [comment]
谢谢！
