### ISSUE TITLE
数据展示配置

### ISSUE THREAD

**Issue by lihanyu** [ElemeFE/v-charts#294]
支持如下配置吗
![image](https://user-images.githubusercontent.com/3992478/40474916-c4c38a40-5f72-11e8-9e39-3ef794ef6c45.png)

**Comment by xiguaxigua** [comment]
可以参考这个例子 https://jsfiddle.net/vue_echarts/1Le0wps5/386/

**Comment by lihanyu** [comment]
恩恩，谢谢！
