### ISSUE TITLE
缺少debounce依赖

### ISSUE THREAD

**Issue by Optimusruan** [ElemeFE/v-charts#297]
### Summary 简述
利用vue-cli 建立的项目，安装v-charts运行时提示缺少依赖

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/16751699/40493480-669f400c-5fa5-11e8-991f-7b0ec3793ab4.png)

**Comment by xiguaxigua** [comment]
引入的是 `lib` 下的文件吗？
