### ISSUE TITLE
引用错误Uncaught ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by yeahTibbers** [ElemeFE/v-charts#3]
版本"v-charts": "^1.1.2"
![image](https://cloud.githubusercontent.com/assets/10751521/26619322/8777123c-4610-11e7-8ed6-5c68dc8c674c.png)

**Comment by xiguaxigua** [comment]
是否引入了对应的图表模块？https://elemefe.github.io/v-charts/#/start?id=%e6%8c%89%e9%9c%80%e5%bc%95%e5%85%a5
方便贴一下代码看看吗？

**Comment by yeahTibbers** [comment]
你好，我使用的是完整引用，代码如下
![image](https://cloud.githubusercontent.com/assets/10751521/26620013/997eb860-4613-11e7-96b2-e3127f782a79.png)

**Comment by xiguaxigua** [comment]
@yeahTibbers 我在本地测试了一下，没有发现这个问题，可能是因为data或者settings里面的数据结构导致的，具体的在 https://gitter.im/v-charts/Lobby 里面沟通吧

**Comment by jinhaidi1** [comment]
你好  我现在遇到了相同的问题   想请教一下是怎么解决的

**Comment by xiguaxigua** [comment]
v-charts 在项目里是如何引用的？如果方便的话，最好是贴一下可以重现的代码。

**Comment by xiguaxigua** [comment]
可以试着升级一下 vue, echarts, v-charts 的版本看看还会不会出现这个问题。

**Comment by jinhaidi1** [comment]
这是我的代码[
<img width="857" alt="wx20171109-104232 2x" src="https://user-images.githubusercontent.com/26374251/32585929-d08e7588-c53a-11e7-9b79-7eae491aa518.png">
](url)

**Comment by jinhaidi1** [comment]
开始使用是良好的   但是因为需求的变化  我需要使用echarts里面的关系图  所以我一些折线图和饼状图使用的是您的代码   关系图使用的echarts的  但是在引入echarts的时候出现了这个问题   现在将echarts注视掉也会出现这个问题  导致现在 两个都无法使用[
<img width="1429" alt="wx2017" src="https://user-images.githubusercontent.com/26374251/32586015-5a957362-c53b-11e7-9f0a-932d9f34981e.png">
](url)

**Comment by jinhaidi1** [comment]
问题还是存在。

**Comment by xiguaxigua** [comment]
在 webpack的配置里面加一个配置
```js
plugins: [
  new webpack.DefinePlugin({
    __DEV__: true
  })
]
```
![image](https://user-images.githubusercontent.com/9931685/32586674-00b182d8-c53f-11e7-9cf1-07674432e64e.png)

**Comment by ChobitsSP** [comment]
https://github.com/ecomfe/echarts/issues/6984

**Comment by ChobitsSP** [comment]
npm i -S echarts@3.7.1 zrender@3.6.1

**Comment by jinhaidi1** [comment]
非常感谢  已经解决
