### ISSUE TITLE
图表不支持 南丁格尔玫瑰图 多圆饼呢

### ISSUE THREAD

**Issue by myxingke** [ElemeFE/v-charts#30]
图表不支持 南丁格尔玫瑰图 多圆饼呢 这样子免得去多次做配置来实现呢！

**Comment by xiguaxigua** [comment]
新增了两个属性用来处理这个问题：`level`和`roseTyle`，可参考以下示例使用
https://jsfiddle.net/vue_echarts/bax7k19f/
https://jsfiddle.net/vue_echarts/61uhgyg5/
