### ISSUE TITLE
折线图右侧日期显示问题

### ISSUE THREAD

**Issue by linlinjava** [ElemeFE/v-charts#301]
### Summary 简述

折现图右侧日期显示不正常。

在#265 中，可以采用旋转横坐标的方式。
但是我觉得效果不是很好。例如数据量少的时候，斜下标不是很美观。
而在echarts实例中显示可以。
不知道是否需要特殊的设定，还是采用一些样式调整。

### Expect 期望结果

折现图右侧日期显示正常。

### Reproduce 重现示例

我项目中出现的效果：

![image](https://user-images.githubusercontent.com/4223779/40577264-70902d7e-6135-11e8-9518-db6ba31e61f3.png)

而在echarts实例中显示可以，例如：

![image](https://user-images.githubusercontent.com/4223779/40577268-789bef76-6135-11e8-9abd-d2dc466e0453.png)

**Comment by xiguaxigua** [comment]
可以让左右两侧留出一定的距离
https://jsfiddle.net/vue_echarts/aa7ojxyt/218/

**Comment by linlinjava** [comment]
好的，多谢。

建议在官网中也采用这个配置，因为官网里面也是这个问题。可能对初学者有点疑惑。

**Comment by linlinjava** [comment]
或者直接把这个设置成默认效果。
