### ISSUE TITLE
饼图

### ISSUE THREAD

**Issue by cosse** [ElemeFE/v-charts#309]
饼图不支持百分比吗.?

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/40758355-7d24523a-64bf-11e8-9db6-6962fb116753.png)

是这种效果吗？

**Comment by cosse** [comment]
不知道你说的,是不是我说的.. 因为我看你引用的是百度是echart的二次封装..所以百度饼图有一个radius : '80%', 可以设置百分比. 但是您这边只能接收Number..

**Comment by xiguaxigua** [comment]
可以使用 extend 函数实现百分比 radius 
https://jsfiddle.net/x9qc7n2u/1/

**Comment by cosse** [comment]
ok

**Comment by xiguaxigua** [comment]
上一个示例有问题，可以查看下面的这个示例
https://jsfiddle.net/x9qc7n2u/5/
