### ISSUE TITLE
v-charts不支持官方的series参数吗？

### ISSUE THREAD

**Issue by shoyuf** [ElemeFE/v-charts#31]
比如我要在饼图上展示
```
normal:{ 
  label:{ 
    show: true, 
    formatter: '{b} : {c} ({d}%)' 
  }, 
  labelLine :{show:true} 
} 
```
[demo](https://codepen.io/anon/pen/dzGrJz)

这样的效果，能否指教下怎么实现？当前用的版本为1.6.8

**Comment by xiguaxigua** [comment]
@shoyuf 
当前版本可以通过在after-config钩子中修改options中对应的配置实现
参考：https://jsfiddle.net/vue_echarts/a0pep942/6/

预计会在下个版本中整合一下这类的配置。

**Comment by poemxl** [comment]
那个链接打不开了，目前我使用series设置饼图的label还是不行呢
