### ISSUE TITLE
环状图如何设置大小

### ISSUE THREAD

**Issue by IVANLEE99** [ElemeFE/v-charts#310]
### Summary 简述

设置了width  height
但是显示的只是图的一部分，没有缩小显示

### Expect 期望结果

能够设置环状图的大小，伸缩显示图，

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/18308725/40769946-dd4ab970-64eb-11e8-9fa9-c860f80c9331.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/LLgu4kwr/

**Comment by IVANLEE99** [comment]
@xiguaxigua 
![image](https://user-images.githubusercontent.com/18308725/40770781-3d57a894-64ee-11e8-8d9c-42c6620ebfac.png)
能直接贴代码吗？
jsfiddle.net 访问不用了，即使FQ了

**Comment by xiguaxigua** [comment]
```js
new Vue({
  el: '#app',
  data () {
	this.chartSettings = {
		radius: ['50%', '40%']
	}
    return {
      chartData: {
        columns: ['日期', '访问用户'],
        rows: [
          { '日期': '1/1', '访问用户': 1393 },
          { '日期': '1/2', '访问用户': 3530 },
          { '日期': '1/3', '访问用户': 2923 },
          { '日期': '1/4', '访问用户': 1723 },
          { '日期': '1/5', '访问用户': 3792 },
          { '日期': '1/6', '访问用户': 4593 }
        ]
      }
    }
  }
})
```

**Comment by IVANLEE99** [comment]
@xiguaxigua 谢谢你的热心回答，祝你生活愉快

**Comment by IVANLEE99** [comment]
还有个问题，就是设置height并不能使高度自适应，造成空隙很大

![image](https://user-images.githubusercontent.com/18308725/40771494-0f042a4c-64f0-11e8-9fcf-c4579e4fc757.png)

![image](https://user-images.githubusercontent.com/18308725/40771570-4a824338-64f0-11e8-8102-4de279e51dea.png)

**Comment by IVANLEE99** [comment]
@xiguaxigua

**Comment by xiguaxigua** [comment]
环图的大小取决于容器宽高中较小的那个，所以如果容器的高度过长的话，环就会默认在垂直中间的位置。
如果想要修改这个样式的话，可以修改容器的高度，或者设置环相对于垂直方向的距离.

```js
new Vue({
  el: '#app',
  data () {
	this.chartSettings = {
		radius: ['50%', '40%'],
		offsetY: '10%'
	}
    return {
      chartData: {
        columns: ['日期', '访问用户'],
        rows: [
          { '日期': '1/1', '访问用户': 1393 },
          { '日期': '1/2', '访问用户': 3530 },
          { '日期': '1/3', '访问用户': 2923 },
          { '日期': '1/4', '访问用户': 1723 },
          { '日期': '1/5', '访问用户': 3792 },
          { '日期': '1/6', '访问用户': 4593 }
        ]
      }
    }
  }
})
```

**Comment by IVANLEE99** [comment]
@xiguaxigua  
![image](https://user-images.githubusercontent.com/18308725/40772827-a2f827a0-64f3-11e8-8ce3-a8b1e3822b92.png)

甚好！
谢谢你的热心解答，完美解决了我的问题
祝你心想事成，工作顺利
