### ISSUE TITLE
请问如何调用后跳数据？

### ISSUE THREAD

**Issue by RikaLuo** [ElemeFE/v-charts#311]
调用后台数据并绑定到相应位置后，页面无图标展示，后台数据的rows只有一条数据：
![1](https://user-images.githubusercontent.com/19562162/40773204-bddc7d22-64f4-11e8-8084-c5a8b24206c5.png)
![2](https://user-images.githubusercontent.com/19562162/40773209-bf21b71a-64f4-11e8-9241-61069b6f953a.png)
![3](https://user-images.githubusercontent.com/19562162/40773210-bf7cc5ec-64f4-11e8-80f3-92f72352d874.png)

**Comment by xiguaxigua** [comment]
可以参考这个示例

https://jsfiddle.net/b7kzdtbx/1/

**Comment by RikaLuo** [comment]
@xiguaxigua 参数传递后线条会一闪全部出现，能否改为逐渐平滑显示的效果呢？ 我测试了如图的参数 依旧无效：
![image](https://user-images.githubusercontent.com/19562162/40792681-166e49a6-652d-11e8-890f-fcc45874e34b.png)

**Comment by xiguaxigua** [comment]
这种现实方式是 echarts 的默认表现：
https://jsfiddle.net/vue_echarts/aj9cemsf/1/
https://jsfiddle.net/vue_echarts/aj9cemsf/

翻了一圈没有找到太好的解决办法，下面是一个兜底方案可以尝试一下：
https://jsfiddle.net/vue_echarts/b7kzdtbx/2/

**Comment by RikaLuo** [comment]
感谢刚刚那个解决方案，还想问个问题，我后台接收到数据为：
![image](https://user-images.githubusercontent.com/19562162/40796335-5edd8300-6537-11e8-8eb0-2cf1338cd427.png)
我是将这个再作为子组件使用的。父组件给他传递参数后报错，实在找不到原因。测试过你给的代码去掉rows中的一个值却能正常运行：
![image](https://user-images.githubusercontent.com/19562162/40796398-84113cac-6537-11e8-9384-8fad5cb16f77.png)

**Comment by xiguaxigua** [comment]
没看懂描述的问题，从报错的图片来看是 VeLine 没有被注册，在使用 VeLine 的页面中注册或者是注册到全局就可以了。
如果不好描述的话，可以把将你遇到的问题按照前面示例的写法抽出一个重现的示例，或者是把页面中的关键代码都粘贴上来，这样会比较好解决问题。

**Comment by RikaLuo** [comment]
![image](https://user-images.githubusercontent.com/19562162/40798101-cf385076-653c-11e8-80f5-388fb2c7783f.png)

这是我抽离出来的echart子组件 

![image](https://user-images.githubusercontent.com/19562162/40798130-e20b2ff2-653c-11e8-83a1-06cba4e4988a.png)

父组件是这样引用的，然后通过接口获取数据，再传递给子级Echarts组件，你说的 Veline 我在Echarts组件中有引用呀。好苦恼~

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/40811441-cc0c4bec-6563-11e8-8d7c-338a134263af.png)

改成
```js
export default {
  name: 'HomeEchart',
  components: { VeLine },
  props: {
    echartColumns: Array,
    echartRows: Array
  }
```

**Comment by RikaLuo** [comment]
按照你说的修改了 ，然而又有了新的bug。orz
![image](https://user-images.githubusercontent.com/19562162/40818272-f821732c-6588-11e8-9f95-0d081ce833cf.png)

![image](https://user-images.githubusercontent.com/19562162/40818266-eb5a41be-6588-11e8-8836-c2ece3641d5d.png)

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/40818452-a5e53a98-6589-11e8-894c-078978ee24bb.png)

**Comment by RikaLuo** [comment]
哇哇哇 感谢感谢 我的粗心！ 总算出来了 好开心
