### ISSUE TITLE
如何在事件监听中传递自己的参数

### ISSUE THREAD

**Issue by IVANLEE99** [ElemeFE/v-charts#312]
### Summary 简述

就是点击后将能在时间中拿到传递的参数

![image](https://user-images.githubusercontent.com/18308725/40776876-a0d7fc10-64fe-11e8-8bc5-1fca7266be9a.png)

### Expect 期望结果

```
      this.chartEvents = {
        click: function (e,p) {
          self.name = e.name
          //能够获取到传递的参数p
          console.log(e,p)
        }
      }
```

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/LLgu4kwr/1/

**Comment by IVANLEE99** [comment]
完美的解决了我的问题
只不过jsfiddle.net就是打不开，好气
千辛万苦，换个浏览器就好了
还是感谢
祝你过个好六一

`  <ve-ring :settings="chartSettings" :events="{ click: clickHandler.bind(this, 1) }" :data="chartData" @ready="ready"></ve-ring>`


```
	  clickHandler (p, e) {
			console.log('outer-params', p)
			console.log('event', e)
		},
```
