### ISSUE TITLE
折线图 折线下的区域渐变色，可以设置嘛？

### ISSUE THREAD

**Issue by ijzn** [ElemeFE/v-charts#313]
### Expect 期望结果
![image](https://user-images.githubusercontent.com/22594109/40817086-fed807ea-6582-11e8-991b-8dd6e3ef1dbe.png)

**Comment by ijzn** [comment]
自问自答一波，解决了；
![image](https://user-images.githubusercontent.com/22594109/40817535-78ab5d2c-6585-11e8-8a05-1b3b21975f44.png)
![image](https://user-images.githubusercontent.com/22594109/40817545-8b68d6a6-6585-11e8-95d8-4c93d2f074ec.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/24xsm2yu/2/

可以参考这个示例实现

**Comment by webCoderJ** [comment]
碰到同样的问题了，想问下如果是多条线需要不同的渐变呢？

**Comment by BaronFu** [comment]
> 碰到同样的问题了，想问下如果是多条线需要不同的渐变呢？

我也碰到了同样的问题，有没有什么解决方法

**Comment by BaronFu** [comment]
> 碰到同样的问题了，想问下如果是多条线需要不同的渐变呢？
已找到解决方法：
https://v-charts.js.org/#/props-demo2

**Comment by feSnake** [comment]
> https://jsfiddle.net/vue_echarts/24xsm2yu/2/
> 
> 可以参考这个示例实现

参考这个案例 白屏了   在main.js全局引入的

**Comment by linshuoe** [comment]
> > 碰到同样的问题了，想问下如果是多条线需要不同的渐变呢？
> > 已找到解决方法：
> > https://v-charts.js.org/#/props-demo2

请问多条渐变你是怎么解决的？可以分享一下吗
