### ISSUE TITLE
自定义问题

### ISSUE THREAD

**Issue by xingyys** [ElemeFE/v-charts#314]
1.怎么自定义主题呢？
2.为什么通过直接修改本地的源码结果不能生效？

**Comment by xiguaxigua** [comment]
自定义主题可以参考 #60 .

> 直接修改本地的源码结果不能生效

这个问题没看懂，描述的清楚一些吧

**Comment by xingyys** [comment]
就是v-charts的源码下载到本地后，我修改本地的v-charts源码，但是图表不能生效。

**Comment by xiguaxigua** [comment]
在页面上是如何引入的？
修改的是哪个路径下的源码？
想要达到什么样的效果？

**Comment by xingyys** [comment]
在main.js文件引入
```
import VCharts from 'v-charts'
import 'v-charts/lib/style.css'
Vue.use(VCharts)
```
修改v-charts/src/core.js

想要修改图表的颜色。（或者在theme下直接可以修改颜色吗）

**Comment by xiguaxigua** [comment]
使用上述的引入方式，引入的文件是 `lib/index.js`，修改的话要修改这里才能生效：
![image](https://user-images.githubusercontent.com/9931685/40819648-bb3a2b06-658e-11e8-949a-6024619849ec.png)

修改图表的颜色最直接的方式是使用 colors 属性：
https://jsfiddle.net/vue_echarts/9krzkta7/

**Comment by RikaLuo** [comment]
请问怎么调图标距离上下左右的距离？ @xiguaxigua

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/f2wj64op/
