### ISSUE TITLE
How does ve-bar sort?

### ISSUE THREAD

**Issue by newwangjie** [ElemeFE/v-charts#32]
Ve-bar gets data on how to go from small to large or from large to small

**Comment by newwangjie** [comment]
Ve-bar gets data on how to go from small to large or from large to small

**Comment by xiguaxigua** [comment]
是下面这个例子的意思吗？
https://jsfiddle.net/vue_echarts/m1hdcmf4/12/

**Comment by newwangjie** [comment]
yes,thank you!! The problem has been settled
