### ISSUE TITLE
环形图默认选中 以及选中后数据详情

### ISSUE THREAD

**Issue by AkiraSun** [ElemeFE/v-charts#323]
### Summary 简述

1.环形图默认选中并有突出效果   
本想使用echarts中
```js
this.myChart.dispatchAction({
            type: 'pieSelect',
            seriesIndex: 0,
            dataIndex: 0
        })
```
v-charts没有实例
后使用了 selected:true
```js
ringData: {
        columns: ['日期', '访问用户'],
        rows: [
          { 日期: '1/1', 访问用户: 1393 ,selected:true},
          { 日期: '1/2', 访问用户: 3530 },
          { 日期: '1/3', 访问用户: 2923 },
          { 日期: '1/4', 访问用户: 1723 },
          { 日期: '1/5', 访问用户: 3792 },
          { 日期: '1/6', 访问用户: 4593 }
        ]
      },
```
每次都要对数据做处理觉得不合理还有其他方法吗？
2.选中后数据详情显示在圆环中，点击圆环可以切换数据
3.默认选中数据 并且凸出  详情显示在圆环外并且带对应颜色，点击圆环可以切换数据
### Expect 期望结果
1.
2.
![image](https://user-images.githubusercontent.com/21287041/40962932-95fcf302-68d9-11e8-805e-1838da0fb01b.png)

3.
![image](https://user-images.githubusercontent.com/21287041/40963051-f16da47a-68d9-11e8-8650-755191aa7156.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/z0gjtq4b/18/

1. 通过 this.$refs.chart.ecahrts 可以获取到实例。
2. 使用 echarts 自带的环图居中显示标签会有很多限制，推荐使用 dom 实现。

**Comment by iTaster** [comment]
> https://jsfiddle.net/z0gjtq4b/18/
> 
> 1. 通过这个。$ refs.chart.ecahrts可以获取到实例。
> 2. 使用echarts自带的环图居中显示标签会有很多限制，推荐使用dom实现。

今天在写这个时发现遇到上面小哥同样的问题，根本居中不了
