### ISSUE TITLE
Element Tabs 组件中使用 ve-histogram组件渲染不出来

### ISSUE THREAD

**Issue by wenhandi** [ElemeFE/v-charts#326]
### Summary 简述
ve-histogram组件单独使用可以正常快速渲染，Element Tabs 组件中使用 ve-histogram组件不能渲染出来。

### Expect 期望结果
柱状图组件在Element Tabs组件中正常渲染出来

### Reproduce 重现示例

![534af41961c0278967a8ae15154cdf5](https://user-images.githubusercontent.com/12582497/40980492-1389d926-690b-11e8-9b0d-9f843947929e.png)

![6b38c08339948d8fce7d60f3e373481](https://user-images.githubusercontent.com/12582497/40980404-e4efb2c0-690a-11e8-8bd6-8a9715c8c81d.png)

**Comment by xiguaxigua** [comment]
https://v-charts.js.org/#/skill-demo

可以参考这篇文档修改

**Comment by wenhandi** [comment]
好用，谢谢你
