### ISSUE TITLE
折线图添加滑动区域组件鼠标滚动无效果

### ISSUE THREAD

**Issue by ploki8** [ElemeFE/v-charts#328]
### Summary 简述
折线图添加滑动区域组件鼠标滚动无效果,只能单击拖动进行区域的缩放

### Reproduce 重现示例

this.PUE = {
			columns: ['时间', 'PUE'],
			rows: [
				{ PUE: 1.2, 时间: '1月1日' },
				{ PUE: 1.4, 时间: '1月2日' },
				{ PUE: 1.3, 时间: '1月3日' },
				{ PUE: 1.5, 时间: '1月4日' },
				{ PUE: 1.6, 时间: '1月5日' },
			],
		};
		this.PUESettings = {
			metrics: ['PUE'],
			dimension: ['时间'],
			
			showMA: true,
			showVol: true,
			showDataZoom: true,
     
		};
		this.dataZoom = [
        {
          type: 'slider',
          start: 0,
          end: 20
        }

**Comment by xiguaxigua** [comment]
当 dataZoom 的 type 被设置为 slider 时，控制的是用户的拖动滚动条行为，如果要增加鼠标滚动，需要增加一个 type 为 inside 的配置：
```js
this.dataZoom = [
  {
    type: 'slider',
    start: 0,
    end: 20
  },
  {
    type: 'inside',
    start: 0,
    end: 20
  }
]
```
https://jsfiddle.net/dx7v0o28/
