### ISSUE TITLE
柱状图维度过多时，文字总是隔一个显示一个，如何设置全部显示

### ISSUE THREAD

**Issue by codingJia** [ElemeFE/v-charts#329]
### Summary 简述
柱状图数据过多时，横坐标维度总是隔一个显示一个，不能全部显示，如果做到全部显示？

### Expect 期望结果
显示全部维度文字

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/22971213/41021560-7178dc74-6999-11e8-80e5-43e9f436aeaf.png)

**Comment by xiguaxigua** [comment]
设置文字倾斜

```js
this.chartExtend = {
  xAxis: {
    axisLabel: {
      rotate: 45
    }
  }
}
```

https://jsfiddle.net/sbz2e4dr/

**Comment by codingJia** [comment]
好的，谢谢
