### ISSUE TITLE
Ve-histogram cannot set minimum scale？

### ISSUE THREAD

**Issue by newwangjie** [ElemeFE/v-charts#33]
Ve-histogram cannot set minimum scale，No parameters are set for minimum calibration

**Comment by xiguaxigua** [comment]
This feature was added in v1.6.10.
eg: https://jsfiddle.net/vue_echarts/1Le0wps5/26/

**Comment by newwangjie** [comment]
Can the Chart scale be set to an integer?

**Comment by xiguaxigua** [comment]
`chartSettings: { scale: 1000 }` ?
if you want to set a specific value, you need to use `min` instead. and `min, max, scale` props all must be an array, in order to handle double y-axes.
