### ISSUE TITLE
这个支持移动端吗？

### ISSUE THREAD

**Issue by JulesCesar** [ElemeFE/v-charts#330]

**Comment by xiguaxigua** [comment]
支持

**Comment by JulesCesar** [comment]
还有个问题。关于配置图表 比如说控制x轴y轴显示与不显示，折线图还是平滑的折线图。还有配置图例的地方

比如说这里，如果移动端放上去的话可以自适应么？？？
![image](https://user-images.githubusercontent.com/19618696/41080377-c9d4a87a-6a58-11e8-93a8-24eaa9baa6bd.png)
