### ISSUE TITLE
正副标题可以在同一行显示嘛？

### ISSUE THREAD

**Issue by ijzn** [ElemeFE/v-charts#334]
### Summary 简述
https://jsfiddle.net/aa7ojxyt/233/

**Comment by xiguaxigua** [comment]
echarts 没有提供直接的属性实现，倒是有一个方案可以试试：
https://jsfiddle.net/aa7ojxyt/240/

**Comment by ijzn** [comment]
谢谢大佬，v-charts 可以不可以后期加个功能，可以设置多个标题？
