### ISSUE TITLE
theme更换问题

### ISSUE THREAD

**Issue by gassnake999** [ElemeFE/v-charts#337]
想请教一下我能否使用在echarts下载的主题

**Comment by xiguaxigua** [comment]
可以使用，以在 echarts 官方的主题配置页面生成的主题包为例，在项目文件中放置这个文件进去，然后在 main.js 中引入这个文件，在组件中设置 theme-name="主题名" 。

![image](https://user-images.githubusercontent.com/9931685/41136573-6c77c0de-6b09-11e8-8309-fc42e8dcd414.png)

**Comment by xiguaxigua** [comment]
也可以复制 JSON 版本，在项目中自行注册主题，或者直接将主题对象赋给组件的 theme 属性。

**Comment by gassnake999** [comment]
再请教一下 我是用的k线 其他的属性都能生效 但是阴线阳线的颜色好像改了无法生效
`candlestick: {
     itemStyle: {
     normal: {
        color: "#FD1050",
        color0: "#0CF49B",
        borderColor: "#FD1050",
        borderColor0: "#0CF49B"
      }
   }
}`
不知道是否是我改错地方了

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/41149210-94d8e9a2-6b3d-11e8-82de-531b705d1599.png)

试试在 settings 里配置这两个属性

**Comment by gassnake999** [comment]
可以了 感谢

**Comment by 1652866741** [comment]
main.js 引入echarts主题包，组件也设置 theme-name，为什么图形线条颜色还是默认的

**Comment by jackchoumine** [comment]
> 也可以复制 JSON 版本，在项目中自行注册主题，或者直接将主题对象赋给组件的 theme 属性。

```html
<ve-line :data="chartData" :theme="theme"></ve-line>
```
js
```js
import VeLine from 'v-charts/lib/line.common'
const macarons = require('echarts/theme/macarons')
export default {
  components: {
    VeLine
  },
  data() {
    return {
      theme: macarons,
      chartData: {
        columns: ['date', 'PV'],
        rows: [
          { 'date': '01-01', 'PV': 1231 },
          { 'date': '01-02', 'PV': 1223 },
          { 'date': '01-03', 'PV': 2123 },
          { 'date': '01-04', 'PV': 4123 },
          { 'date': '01-05', 'PV': 3123 },
          { 'date': '01-06', 'PV': 7123 }
        ]
      }
    }
}
}
```
我设置主题，没生效啊，大佬能写个 demo 吗？ 或者我的这个错在哪儿啊。谢谢

**Comment by jackchoumine** [comment]
> 可以了 感谢

帅哥，怎么设置的，可以写一个 demo 吗？
