### ISSUE TITLE
typescript项目使用

### ISSUE THREAD

**Issue by lebang** [ElemeFE/v-charts#340]
### Summary 简述

在typescript项目中使用，缺少types，如何手写解决？感谢

### Expect 期望结果

![image](https://user-images.githubusercontent.com/1699165/41191642-45cd5ab2-6c25-11e8-98d4-4f8d65c187bb.png)

**Comment by xiguaxigua** [comment]
类似下面这样，在项目中的 '.d.ts' 文件中增加一个声明就行了

```ts
declare module 'v-charts/lib/line'
declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}

```

**Comment by xiguaxigua** [comment]
按照常规的注册组件的方式写就行了

**Comment by godpan** [comment]
declare module 声明后出现这个错误提示，放在.d.ts文件中也一样，怎么解决呢？
![wechatimg5](https://user-images.githubusercontent.com/17349682/45075575-20103800-b11a-11e8-9ff7-1ef373b4cd09.jpeg)
@xiguaxigua

**Comment by startblingbling** [comment]
在typescript项目中使用， this.$nextTick(_ => {
          this.$refs[`chart1`].echarts.resize()
        })
echarts这个方法不能使用，报错Unresolved variable echarts ，怎么解决呢？

**Comment by shen-lan** [comment]
```
data () {
    this.chartSettings = {
      radius: [10, 100],
      offsetY: 100
    }
    return {
      chartData: {
        columns: ['日期', '访问用户'],
        rows: [
          { '日期': '1/1', '访问用户': 1393 },
          { '日期': '1/2', '访问用户': 3530 },
          { '日期': '1/3', '访问用户': 2923 },
          { '日期': '1/4', '访问用户': 1723 },
          { '日期': '1/5', '访问用户': 3792 },
          { '日期': '1/6', '访问用户': 4593 }
        ]
      }
    }
  }
```
ts 里
```
    this.chartSettings = {
      radius: [10, 100],
      offsetY: 100
    }
```
报错如何处理
