### ISSUE TITLE
1.16.20 开始有问题。

### ISSUE THREAD

**Issue by DiamondYuan** [ElemeFE/v-charts#341]
### Summary 简述

1.16.20开始报错

### Expect 期望结果

官网的JSFiddle 就有问题 

https://jsfiddle.net/vue_echarts/aa7ojxyt

**Comment by xiguaxigua** [comment]
原因是1.16.20之后引入了 [numerify](http://daxigua.me/numerify/) 来更好的实现数值的格式化，不过这个依赖没有加到在线的文档示例上，现在在线示例已经更新了。

**Comment by DiamondYuan** [comment]
@xiguaxigua  我的项目用了v-charts 没制定版本 突然一天就挂了。
你们自己用了新的库为啥不放在v-chats里面呀。

**Comment by xiguaxigua** [comment]
今天会发布一个版本修复这个问题

**Comment by xiguaxigua** [comment]
v1.16.23 版本处理掉了这个问题，再次为这种冒进的行为向您表示歉意，后面再次遇到这种决策的时候不会再有同样的问题出现。
