### ISSUE TITLE
地图事件监听无法获取第二个指标纬度的值

### ISSUE THREAD

**Issue by jiangxuzh** [ElemeFE/v-charts#344]
### Summary 简述
地图中传入多指标数据。在点击事件中无法获取除了第一个指标外其他指标的值

### Reproduce 重现示例

代码如下
`<ve-map :data="chartData" :settings="chartSettings" :events="{click: onChartClick}"></ve-map>`
`
chartData: {
  columns: ['name', 'allnet', 'code'],
  rows: [
    { 'prov': '吉林', 'allnet': 123, 'code': 1223 },
    { 'prov': '北京', 'allnet': 1223, 'code': 2123 },
    { 'prov': '上海', 'allnet': 2123, 'code': 1243 },
    { 'prov': '浙江', 'allnet': 4123, 'code': 5123 }
  ]
}
`
`onChartClick (e) { console.log(e) }`

![209b631baacc1740d7ccb8beff2bca5](https://user-images.githubusercontent.com/22673000/41210926-e438109c-6d66-11e8-9777-13de1d66be52.png)

**Comment by xiguaxigua** [comment]
当前版本没有将所有指标绑定到地图模块上，可以尝试使用一种临时的解决方案：

在获取到数据时，以 name 为 key 生成一个数据对象，在触发点击事件是，根据 name 从前面的数据对象中查找数据。

**Comment by jiangxuzh** [comment]
好的，感谢解答，期待之后会有更容易的方法获取其他指标
