### ISSUE TITLE
在watch中直接修改chartData的数值后地图组件不渲染，

### ISSUE THREAD

**Issue by ijzn** [ElemeFE/v-charts#345]
### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/22594109/41228010-70c03214-6da9-11e8-8600-8a909cdbfa9b.png)
![image](https://user-images.githubusercontent.com/22594109/41227922-22437f74-6da9-11e8-9b0b-115f65c68c9c.png)
![image](https://user-images.githubusercontent.com/22594109/41227989-6198dffc-6da9-11e8-99ae-414cd17d9fc3.png)

**Comment by xiguaxigua** [comment]
写了一个示例，似乎不是 v-charts 的问题，检查一下代码逻辑吧。
https://jsfiddle.net/vue_echarts/bndg2tqy/3/

**Comment by ijzn** [comment]
找到问题了，是在省一级的地图的话，必须 ‘市’  比如 杭州，如果后台返回的 数据是 杭州市 就可以正确显示， 如果是杭州就显示不出来。
