### ISSUE TITLE
如何在动态数据上实现图表缩放呢?

### ISSUE THREAD

**Issue by coolucifer** [ElemeFE/v-charts#348]
### Summary 简述
想在图表上实现缩放,但是数据是动态变化的,每次拖动滑动条的时候都会在下一次数据刷新的时候重置到开始的位置.

### Expect 期望结果
滑动条窗口不受数据刷新影响

### Reproduce 重现示例

https://jsfiddle.net/coolucifer/qztn4gbm/3/

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/qztn4gbm/16/

把 dataZoom 里面的 start 和 end 去掉，然后在组件上增加属性 `:set-option-opts="false"`

**Comment by coolucifer** [comment]
@xiguaxigua 谢谢
