### ISSUE TITLE
Why can't the values in columns change dynamically based on selection?

### ISSUE THREAD

**Issue by newwangjie** [ElemeFE/v-charts#35]
Why can't the values in columns change dynamically based on selection?
When the value in columns changes, the legend above does not change, and the data renders an error

**Comment by xiguaxigua** [comment]
@newwangjie 
If you want to change the metrics, set `metrics` in settings is better, and there is an example about this.
https://jsfiddle.net/vue_echarts/we718276/2/

Then, if this example is useless, you may give me some code to reproduce this bug.

**Comment by newwangjie** [comment]
yes,thank you!!!
