### ISSUE TITLE
如何实时无刷新更新echart

### ISSUE THREAD

**Issue by RikaLuo** [ElemeFE/v-charts#351]
### Summary 简述
根据筛选条件实时更新echart，目前状态是需要刷新页面才会将最新数据更新到Echart图上。
![image](https://user-images.githubusercontent.com/19562162/41325925-686d1202-6eef-11e8-8b69-9b3437a36762.png)

### Expect 期望结果
希望能无刷新更新Echart

**Comment by RikaLuo** [comment]
我的代码是这样 根据后台获取到的数据，希望能实时shu刷新echart
![_20180613103221](https://user-images.githubusercontent.com/19562162/41327224-2ba6862c-6ef5-11e8-8a48-08cc1a5ffc2e.png)

**Comment by xiguaxigua** [comment]
可以参考这个示例：
https://v-charts.js.org/#/data?id=%E6%95%B0%E6%8D%AE%E8%AF%B7%E6%B1%82%E7%A4%BA%E4%BE%8B

**Comment by RikaLuo** [comment]
目前的代码如下所示，但是依旧不能实时刷新，求助。。。
![image](https://user-images.githubusercontent.com/19562162/41329118-5cf8f7ce-6efe-11e8-8545-708118fbb347.png)
![image](https://user-images.githubusercontent.com/19562162/41329154-926ef868-6efe-11e8-9130-4dc5861733bd.png)

**Comment by xiguaxigua** [comment]
home-echart 是如何封装的呢？

**Comment by RikaLuo** [comment]
这个是home-echart的代码：
![image](https://user-images.githubusercontent.com/19562162/41329515-cae3101a-6f00-11e8-9a4d-1778e3268fa1.png)

**Comment by RikaLuo** [comment]
`<template>
	<div>
        <ve-line v-if="chartVisible" :grid="chartGrid" :data="chartData" :loading="chartLoading" :set-option-opts="false" :judge-width="false" :data-empty="dataEmpty">
        </ve-line>
    </div>
</template>

<script>
import VeLine from 'v-charts/lib/line'
export default {
    name: "HomeEchart",
    components: { VeLine },
    props: {
        echartColumns: Array,
        echartRows: Array
    },
    data() {
        this.chartSettings = {
            dimension: ['日期']
        }
        this.chartGrid = {
            left: '3%',
            right: '4%'
        }
        return {
            chartData: {
                columns: [],
                rows: []
            },
            chartLoading: false,
            dataEmpty: false,
            judgeWidth: false,
            chartVisible: true
        };
    },
    methods: {
        getData () {
            this.chartLoading = true
            this.dataEmpty = false
            setTimeout(() => {
                this.chartData.columns = this.echartColumns
                this.chartData.rows = this.chartData.rows.length ? [] : this.echartRows
                this.dataEmpty = !this.chartData.rows.length
                this.chartLoading = false
                this.chartVisible = false
                this.$nextTick(_ => {
                    this.chartVisible = true
                })
            }, 1000)
        }
    },
    mounted() {
        this.getData();
    },
};
</script>`

**Comment by xiguaxigua** [comment]
调整一下 home-echart 的实现形式：
将 getData 函数移除掉，使用 computed 将数据赋值到 data
```js
    computed: {
      chartData () {
        return {
          columns: this.echartColumns || [],
          rows: this.echartRows || []
        }
      }
    }
```
loading 和 dataEmpty 通过 props 从父组件中传递过来就可以了，在父组件中判断并修改这两个状态。
（示例中增加 setTimeout 只是为了模拟数据请求的延时过程，实际写的时候不需要写这个）

**Comment by RikaLuo** [comment]
大概是我没弄懂，我改完之后有bug，下面是我的代码，你可不可以在这个基础上改一下呀？感谢！
```
<template>
	<div>
        <ve-line v-if="chartVisible" :grid="chartGrid" :data="chartData" :loading="chartLoading" :set-option-opts="false" :judge-width="false" :data-empty="dataEmpty">
        </ve-line>
    </div>
</template>

<script>
import VeLine from 'v-charts/lib/line'
export default {
    name: "HomeEchart",
    components: { VeLine },
    props: {
        echartColumns: Array,
        echartRows: Array,
        // dataEmpty: Boolean,
        // chartLoading: Boolean
    },
    data() {
        this.chartSettings = {
            dimension: ['日期']
        }
        this.chartGrid = {
            left: '3%',
            right: '4%'
        }
        return {
            chartData: {
                columns: [],
                rows: []
            },
            chartLoading: false,
            dataEmpty: false,
            judgeWidth: false,
            chartVisible: true
        };
    },
    methods: {
        getData () {
            this.chartLoading = true
            this.dataEmpty = false
            setTimeout(() => {
                this.chartData.columns = this.echartColumns
                this.chartData.rows = this.chartData.rows.length ? [] : this.echartRows
                this.dataEmpty = !this.chartData.rows.length
                this.chartLoading = false
                this.chartVisible = false
                this.$nextTick(_ => {
                    this.chartVisible = true
                })
            }, 1000)
        }
    },
    mounted() {
        this.getData();
    },
};
</script>
```

**Comment by xiguaxigua** [comment]
```html
<template>
	<div>
        <ve-line
          v-if="chartVisible"
          :grid="chartGrid"
          :data="chartData"
          :loading="chartLoading"
          :set-option-opts="false"
          :judge-width="false"
          :data-empty="dataEmpty">
        </ve-line>
    </div>
</template>

<script>
import VeLine from 'v-charts/lib/line'
export default {
    name: "HomeEchart",
    components: { VeLine },
    props: {
        echartColumns: Array,
        echartRows: Array,
        dataEmpty: Boolean,
        chartLoading: Boolean
    },
    data() {
        this.chartSettings = {
            dimension: ['日期']
        }
        this.chartGrid = {
            left: '3%',
            right: '4%'
        }
        return {
            chartVisible: true
        };
    },
    methods: {
        getData () {
          this.chartData.columns = this.echartColumns
          this.chartData.rows = this.echartRows
          this.dataEmpty = !this.echartRows.length
          this.$nextTick(_ => {
            this.chartVisible = true
          })
        }
    },
    watch: {
      echartRows: {
        immediate: true,
        handler: 'getData'
      }
    }
};
</script>
```

**Comment by RikaLuo** [comment]
引用后 页面报错
![image](https://user-images.githubusercontent.com/19562162/41332662-661bcfda-6f11-11e8-96b4-16d1c23c04ab.png)

**Comment by xiguaxigua** [comment]
代码我做了调整，重新复制过去试试

**Comment by RikaLuo** [comment]
是直接复制过去的，我把homeEchart这个组件里的
this.dataEmpty = !this.echartRows.length
这段代码注释后，就不报错了，但是出现了从有数据到无数据时，页面出现以下情况：
![image](https://user-images.githubusercontent.com/19562162/41332974-78a274f0-6f12-11e8-9663-280acb467acd.png)
我的main.vue的代码是：
![image](https://user-images.githubusercontent.com/19562162/41333004-9d2dfed4-6f12-11e8-99ed-af2530d3ff18.png)
![image](https://user-images.githubusercontent.com/19562162/41333033-b88577b6-6f12-11e8-924c-addccec69807.png)

**Comment by xiguaxigua** [comment]
检查一下数据为空时 chartData.rows 的状态

**Comment by RikaLuo** [comment]
打印出来的结果是这样的：
![image](https://user-images.githubusercontent.com/19562162/41333553-ce2cfb32-6f14-11e8-859c-53e26a69b9ac.png)
![image](https://user-images.githubusercontent.com/19562162/41333539-bf93ada0-6f14-11e8-9f9c-edff70186b25.png)

**Comment by xiguaxigua** [comment]
在 css 里把 .v-charts-data-empty 背景色设置为白色

**Comment by RikaLuo** [comment]
可以了，感谢感谢
