### ISSUE TITLE
图表右下角显示不全

### ISSUE THREAD

**Issue by leisclei** [ElemeFE/v-charts#352]
### Summary 简述
你好,发现个bug, 图表右下角显示不全

### Expect 期望结果
因为是canvas里面,我没找到地方添加css

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/32569272/41340634-66f72f76-6f2a-11e8-97df-a32cdeb7e5a4.png)

**Comment by xiguaxigua** [comment]
更新版本再试试 v1.16.25

**Comment by leisclei** [comment]
这个版本还没上线

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/41343170-7a1d5fa2-6f30-11e8-9cdd-1b4abf67e0d1.png)

已经上线了，重新更新一下吧。

**Comment by leisclei** [comment]
完美,谢谢
![sagc kgvpj 1p g _ nxw](https://user-images.githubusercontent.com/32569272/41386441-f8b0ccea-6fb3-11e8-9599-d93ce48b74cc.png)
