### ISSUE TITLE
百度地图(ve-bmap)如何自定义绘制点

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/v-charts#354]
### Summary 简述
百度地图(ve-bmap)如何自定义绘制点

### Expect 期望结果
有个例子瞧瞧或者说明一下

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/24503453/41342007-c4ae928c-6f2d-11e8-855f-a7c48b7911dd.png)

**Comment by xiguaxigua** [comment]
echarts 的文档上似乎没有提供自定义 dom 的玩法，v-charts 没有对这部分做定制，echarts 的配置都可以使用 http://echarts.baidu.com/option.html#series-line.symbol 。

**Comment by MaJiaXuan** [comment]
好了，搞定了

**Comment by 309893147** [comment]
请问具体怎么实现的呢,有没有demo
