### ISSUE TITLE
饼状图数据相同的时候，扇形的颜色相同

### ISSUE THREAD

**Issue by frankxjkuang** [ElemeFE/v-charts#355]
### Summary 简述
当<strong style="color: red">数据相同</strong>的时候，渲染出来的扇形颜色相同

### Expect 期望结果
<strong style="color: red">即时</strong>数据一样也应该安装设置的color数组进行依次渲染

### Reproduce 重现示例

![pic](https://user-images.githubusercontent.com/25651756/41342489-f2cdd8de-6f2e-11e8-9ccd-936ae2f68413.png)

**Comment by xiguaxigua** [comment]
把 name 改成不同的试试

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/api/post/library/pure/

**Comment by frankxjkuang** [comment]
我的意思就是因为该条对象的值相同导致这个问题，在数据相同的情况下不能让颜色值不一样么？

**Comment by frankxjkuang** [comment]
@xiguaxigua 我的意思就是因为该条对象的值相同导致这个问题，在数据相同的情况下不能让颜色值不一样么？

**Comment by xiguaxigua** [comment]
一种比较简单的做法是通过修改数据中维度的值，将相同的维度加上不同的后缀用以区分：https://jsfiddle.net/rswfqj0g/12/
还可以基于上面的这种做法，修改维度的值，然后通过 formatter 还原维度：
https://jsfiddle.net/rswfqj0g/19/

**Comment by frankxjkuang** [comment]
@xiguaxigua 端午节期间都去陪家人玩了，没有看到您的留言！感谢的帮助。抓住端午的尾巴，祝您端午安康！
