### ISSUE TITLE
line图tooltip设定trigger为item时报错，tooltip无法正常显示

### ISSUE THREAD

**Issue by terevor** [ElemeFE/v-charts#357]
### Summary 简述
line图多个指标，设定tooltip如下：

`
tooltip: {
    trigger: 'item'
}
`

tooltip无法显示，console报错。

源码/node_modules/v-charts/src/packages/line/main.js，
line 130：tooltip trigger为item时，formatter的参数items非数组，此处items[0]为undefined

### Expect 期望结果
tooltip正常显示

### Reproduce 重现示例
[https://jsfiddle.net/oehjfy2x/1/](https://jsfiddle.net/oehjfy2x/1/)

**Comment by xiguaxigua** [comment]
可以设置使用默认 formatter
https://jsfiddle.net/oehjfy2x/2/
