### ISSUE TITLE
图表数据为字符串时tooltip显示为0

### ISSUE THREAD

**Issue by coolucifer** [ElemeFE/v-charts#358]
### Summary 简述
图表数据为字符串时tooltip上显示为0,
但是图表中显示的柱状图/折线图高度没有影响
之前的vcharts  1.16.5版本没有这个问题,更新到1.16.23版本就会这样了.
echarts没有这个问题,是vcharts特意做成这样的吗?
![image](https://user-images.githubusercontent.com/23123540/41394485-aac564c2-6fdc-11e8-82c5-fc31faa64662.png)

### Expect 期望结果
数据为字符串时如果能转换为数字则显示对应数字

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/23123540/41394320-13c47202-6fdc-11e8-98be-d7b368bdc78b.png)
[https://jsfiddle.net/coolucifer/og6kj4dh/1/](https://jsfiddle.net/coolucifer/og6kj4dh/1/)

**Comment by xiguaxigua** [comment]
更新一下版本就行了（v1.16.27） https://jsfiddle.net/og6kj4dh/4/

**Comment by coolucifer** [comment]
好的, 谢谢
