### ISSUE TITLE
need help-支持自定义v-line的Y轴数据类型

### ISSUE THREAD

**Issue by SKYhuangjing** [ElemeFE/v-charts#360]
### Summary 简述
目前提供的chartSetting中存在 yAxisType: ["KMB"],可以转换数据
但在流量使用场景时,我需要的转换应该是K,M,G,T...
ps,在环形图中,我可以通过修改tooltip完成我的转换,但如何在折线图中实现此转换呢

### Expect 期望结果
提供自定义的转化类型接口,使数据呈现的样式更加灵活配置

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/13705011/41398578-6303ee3e-6fea-11e8-89ed-1303b495393e.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/0y1jwo9q/3/

升级一下版本(v1.16.28)，然后使用下面这种方式，通过 numerify.setOptions 来修改，更多玩法可以参考 numerify 的[文档](https://daxigua.me/numerify/)

https://github.com/ElemeFE/v-charts/blob/master/examples/test/number-format.vue#L10-L17
