### ISSUE TITLE
地图区域的label 文字显示在区域边界上了，如何调整label的位置

### ISSUE THREAD

**Issue by ijzn** [ElemeFE/v-charts#361]
### Summary 简述
echarts 可以调整 地图json 来修改，那v-charts有方法直接修改嘛？让label 文字居中显示
https://github.com/apache/incubator-echarts/issues/4635

### Expect 期望结果
http://gallery.echartsjs.com/editor.html?c=xHyPl7vyu

**Comment by xiguaxigua** [comment]
可以将 json 下载下来，修改后放到你的项目中，然后在页面里引入，通过  settings.mapOrigin 传递给 `ve-map` 组件使用

![image](https://user-images.githubusercontent.com/9931685/41401336-288808d2-6ff2-11e8-936a-3da09eec2e97.png)
