### ISSUE TITLE
弱弱问一下2.0的release时间

### ISSUE THREAD

**Issue by SparksFyz** [ElemeFE/v-charts#364]
正好看到说2.0会有treeMap, 所以弱弱问一下...

**Comment by xiguaxigua** [comment]
2.0版本可能还需要一段时间，`treeMap` 会先于2.0版本 publish 出来，在7月之前，完成核心部分的升级之后，补全对 echarts 图表的支持。

**Comment by taruigu** [comment]
treeMap现在能用了吗？没看到官网上  （https://v-charts.js.org） 有呢……
