### ISSUE TITLE
饼图移动端项目title不显示

### ISSUE THREAD

**Issue by zwq8299174** [ElemeFE/v-charts#366]
### Summary 简述

昨天以为饼图无法使用extend属性，然后说是格式有问题，我照着
https://jsfiddle.net/43uxgeb5/4/
调整了项目中数据的格式，然后发现饼图出来了，title一直没有，然而jsfiddle中是有的，然后重新初始化了一个项目，使用的是滴滴的mand-mobile，
https://didi.github.io/mand-mobile/#/zh-CN/docs/started

然后我自己初始化完的项目在github上面  仅仅只是初始化然后把VePie 组件导入，然后使用官方数据也是无法显示。

我不知道是否有影响。

### Expect 期望结果

饼图title可以显示

### Reproduce 重现示例

https://github.com/zwq8299174/v-charts-demo.git

**Comment by xiguaxigua** [comment]
项目中是否引入了 title 模块

`import "echarts/lib/component/title";`

**Comment by zwq8299174** [comment]
好吧.....api页面里没有任何体现，希望官网可以体现一下，有哪些单独的功能是需要引入模块的

**Comment by xiguaxigua** [comment]
感谢您的建议，文档上有体现，不过可能说的不是很明确，我会想个别的办法来更好的提示这个问题。

![image](https://user-images.githubusercontent.com/9931685/41448954-8b5aa124-7090-11e8-8b58-5f6d10d17b37.png)
