### ISSUE TITLE
如何给饼状图各个扇形区域指定特定的颜色

### ISSUE THREAD

**Issue by linsywu** [ElemeFE/v-charts#367]
### Summary 简述
如何给饼状图各个扇形区域指定特定的颜色，而不是从默认的colorList中根据数据下标获取？

### Expect 期望结果

现在饼状图存在三种状态，成功，失败，处理中；希望三个扇形区域的颜色固定的是绿色，红色，黄色，原始的echarts中可以通过data的itemStyle指定，不知道我们这个插件有没有融合这个功能？

### Reproduce 重现示例

]
![image](https://user-images.githubusercontent.com/15061856/41448933-738424a8-7090-11e8-85be-bf9bf3fb5565.png)

**Comment by xiguaxigua** [comment]
可以固定 rows 的顺序为 [成功，失败，处理中]，然后指定 colors: [green,red,yellow] [示例](https://jsfiddle.net/ofk3mcxd/2/), 如果 rows 中的顺序无法固定的话，也可以通过 extend 属性，在 series 中，判断文本并设置颜色。

**Comment by linsywu** [comment]
搞定，感谢老板，老板抽烟
