### ISSUE TITLE
仪表盘(ve-gauge)设置的title设置不了formatter

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/v-charts#368]
### Summary 简述
按照文件上面的写，无效，仪表盘(ve-gauge)设置的title设置不了formatter
![image](https://user-images.githubusercontent.com/24503453/41452678-8a7a7314-70a5-11e8-8220-0ae7f51e14e6.png)

### Expect 期望结果
解决方法

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/24503453/41452695-9dc89e46-70a5-11e8-9c7c-6f5591e249f7.png)

**Comment by xiguaxigua** [comment]
试试这样配置

https://jsfiddle.net/7bd0pco8/2/

**Comment by MaJiaXuan** [comment]
如果我想拿到我的参数，去自定义标题内容呢？

**Comment by xiguaxigua** [comment]
详细描述一下吧，这个参数要从哪里拿？

**Comment by xiguaxigua** [comment]
直接读取 rows[0].type 赋给 title.text 应该就可以了。
https://jsfiddle.net/7bd0pco8/9/

**Comment by MaJiaXuan** [comment]
![image](https://user-images.githubusercontent.com/24503453/41453574-dd0e9da0-70a8-11e8-8321-d9b75e844faf.png)
搞错了，其实就是想设置这里的标题

**Comment by MaJiaXuan** [comment]
这种要怎么设置？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/7bd0pco8/36/

**Comment by MaJiaXuan** [comment]
好吧，先这样吧，问题还没彻底解决，感觉回答！
