### ISSUE TITLE
图表不显示

### ISSUE THREAD

**Issue by frogRen** [ElemeFE/v-charts#37]
通过post获取数据之后，图表不显示
修改窗口大小之后 才显示出来

**Comment by xiguaxigua** [comment]
@frogRen  数据没有放到data里面？

**Comment by frogRen** [comment]
数据设置上了。  原因大概是, div没有设置宽度  给el-line设置默认宽度后可以正常显示

另外咨询下 line图如何像瀑布图那样 每列显示出对应的数值，而不需要鼠标指向

**Comment by shayumaoliang** [comment]
@frogRen  也遇到这个问题，设定表格宽度木有用，是如何解决的？

**Comment by xiguaxigua** [comment]
@shayumaoliang 默认 chart 的宽度为100%，也就是说，如果父级如果没有宽度的话是无法显示的，解决的方法要么给父级一个宽度，要么给 chart 设置`width`属性指定一个像素值。如果不生效的话，最好是可以写一个例子，或者提供一下这个 chart 所处的 dom 结构，这样我可以更好的解决你的问题。

**Comment by xiguaxigua** [comment]
@frogRen v1.7.8 之后，支持在settings中设置label来实现这个功能，参考下面的例子：
https://jsfiddle.net/vue_echarts/jepw6dy2/48/
