### ISSUE TITLE
多条线悬浮提示显示成了0

### ISSUE THREAD

**Issue by snailg** [ElemeFE/v-charts#370]
### Summary 简述
多条线悬浮提示显示成了0。

### Expect 期望结果
实际的值。

### Reproduce 重现示例

![7f86f3a8-2c18-4607-b77f-2378d4755440](https://user-images.githubusercontent.com/5671609/41457548-a0129010-70b6-11e8-93de-121cbf4b1811.png)

**Comment by xiguaxigua** [comment]
数值是字符串吗？ 如果是的话更新一下版本应该就行了

**Comment by snailg** [comment]
请问现在版本多少？我是通过CDN方式引入的。使用的下面两个地址。
    <script src="https://cdn.jsdelivr.net/npm/numerify/lib/index.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/v-charts/lib/index.min.js"></script>

**Comment by xiguaxigua** [comment]
<script src="https://cdn.jsdelivr.net/npm/v-charts@1.16.29/lib/index.min.js"></script>

另外 numerify 已经被默认打包到 v-charts 中了，所以不用在额外引入

**Comment by snailg** [comment]
我是前几天看系统的时候老是报一个错误：“p 不是函数”，我就去官网看了下，发现引用方式变了。如果我不写
<script src="https://cdn.jsdelivr.net/npm/numerify/lib/index.umd.min.js"></script>    就会一直报那个错误，写上就没事，我也没弄明白。

**Comment by xiguaxigua** [comment]
是的，上个版本不慎引入了一个 breaking change，现在已经修复了。

**Comment by snailg** [comment]
<script src="https://cdn.jsdelivr.net/npm/v-charts@1.16.29/lib/index.min.js"></script>
我更新了版本也不行，必须得返回数字类型吗？现在数值是字符串。

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/fo2h5cbj/ 似乎是没有问题的，能否提供一个重现的链接呢？

**Comment by snailg** [comment]
您提供的这个链接，也存在这个问题。字符串也是显示0


![tim 20180615164300](https://user-images.githubusercontent.com/5671609/41459256-9dbdece2-70bb-11e8-8aec-6a52ebcadd6e.png)
![tim 20180615164142](https://user-images.githubusercontent.com/5671609/41459259-9e12f9da-70bb-11e8-9dde-e11e7de6402e.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/fo2h5cbj/6/
使用 1.16.30 版本试试

**Comment by snailg** [comment]
已经可以了，谢谢。另外一个问题也可以了。
