### ISSUE TITLE
项目打包优化

### ISSUE THREAD

**Issue by xiterjia** [ElemeFE/v-charts#374]
### Summary 简述
引入方式：`yarn add v-charts echarts`
> echarts 4.1.0  
> v-charts 1.16.18
##### 未经过任何优化打包
打包后发现，echarts和v-charts全部都打包进去了，项目中只用到了Pie、Line、Bar这三种图例
##### 只引入单个的组件的min
打包后，文件会小一些，但是分析后发现，小的只是v-charts相关的代码，echarts还是原本不动的打包进去了

### Expect 期望结果
通过配置webpack的externals，直接引入echarts的部分模块，移出node_modules中的echarts，项目直接运行不了了。

如果全部剥离出来，不安装node_modules里，直接引用外部文件的话，后期增加图例的话，还要再去引用相关的v-charts脚本。

请问一下有什么比较好的打包优化方式么？

**Comment by xiguaxigua** [comment]
```js
import VePie from "v-charts/lib/pie.common";
import VeLine from "v-charts/lib/line.common";
import VeBar from "v-charts/lib/bar.common";

[VeLine, VePie, VeBar].forEach(comp => {
  Vue.component(VeLine.name, VeLine);
});
```

上面这样引入可以得到最小的打包体积。

echarts 的体积比较大，大约在200~400k左右，zrender 有100+k，v-charts 包大概每个有5k左右，另外还有的就是 numerify + utils + core 等部分总共10+k。

v-charts 在封装 echarts 的时候，遵循了最少引入的原则，只引入了图对应的模块包，在不引入例如 dataZoon，visualMap等插件的情况下，不需要在项目中手动引入 echarts 相关的模块。

**Comment by xiguaxigua** [comment]
上面的体积是针对使用 v1.17+ 来说的，17以下的版本可能体积会稍大一些，最好是升级到1.17+ 版本。

**Comment by xiterjia** [comment]
非常感谢，我之前没细看，以为此项目是把所有的echarts包都导进去了。
另外还想请问一下
```javascript
import VePie from "v-charts/lib/pie.common.min";
```
通过这样引入```common.min.js```之后，打包后会更小一些，不过看文档并未这样推荐，不知其原因。

还有一个是新版本的bug
在版本```1.16.18```引入正常
最新版本```1.17.1```引入```common.min.js```时报错，并未找到utils、core与constants相关的模块包，如下图所示。

![image](https://user-images.githubusercontent.com/3360879/41509480-e9ae2776-7286-11e8-8f7a-efca02843aa9.png)

**Comment by xiguaxigua** [comment]
在文档中，[开始使用](https://v-charts.js.org/#/start)一节更新了按需引用的方法。
在上一个版本中，只测试了没有 min 过的包，没有测试 uglify 的包，确实是一个很大的疏忽 😢，因为平时开发使用时，更多的还是没有 min 的包，后续版本会增加一些这方面的测试，最后 感谢您的支持 :grinning:。
