### ISSUE TITLE
环图的标签显示错误

### ISSUE THREAD

**Issue by hiipeng** [ElemeFE/v-charts#376]
### Summary 简述
1/1的标签显示到1/2中
![image](https://user-images.githubusercontent.com/32444545/41516402-1d1ac820-72e7-11e8-8c46-89413370a135.png)

**Comment by xiguaxigua** [comment]
在内环半径过小时，echarts 本身关于 label 的计算似乎有问题，将内环半径调高即可。
https://jsfiddle.net/aj9cemsf/11/
