### ISSUE TITLE
是否支持配置项封装导出，以便于下次从数据库获取并加载配置好的配置项

### ISSUE THREAD

**Issue by DarkRake** [ElemeFE/v-charts#377]
### Summary 简述

您好，最近公司有一枚新的需求，配置项希望是可视化进行配置的，可视化配置完成之后，是否支持将配置项导出呢？以便于入库

### Expect 期望结果

支持配置项导出特定json格式，便于入库，以及加载指定格式的JSON配置项

**Comment by xiguaxigua** [comment]
导出配置可以在可视化配置之后实现。
可视化配置需要开发者在项目中自行设计，例如以饼图为例，可以增加 是否显示为玫瑰图，数据格式设置，显示的指标设置，数据的条数，边距等等，这些设置在界面上设置好之后，通过 settings, extend 等显示在页面上，此时可以将 setting, extend，grid 等 存入数据库中，在下一次渲染对应图的时候，将这些属性赋值到组件上就可以了。

**Comment by DarkRake** [comment]
灰常感谢您的回复
