### ISSUE TITLE
现在急需在histogram柱形图里显示标签，希望新增的label配置可以尽快发布到npm package上

### ISSUE THREAD

**Issue by Telanx** [ElemeFE/v-charts#38]
现在急需在histogram柱形图里显示标签，希望新增的label配置可以尽快发布到npm package上

**Comment by Telanx** [comment]
发布到npm最新包1.7.10似乎没有更新lib里的文件，还是无法显示标签
我把github里的最新文件npm run com生成替换掉后可以显示了

**Comment by xiguaxigua** [comment]
发了1.7.11了，升级下试试

**Comment by Telanx** [comment]
@xiguaxigua 谢谢~
