### ISSUE TITLE
heatmap show label 热力图不显示值

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/v-charts#385]
### Summary 简述
By default, heatmap doesn't show label. How to allow heatmap to show labels on tiles like this: [demo](https://ecomfe.github.io/echarts-examples/public/editor.html?c=heatmap-cartesian) where the number is on the tile. Also is there anyway to customize this field? For example, maybe show the fourth column of the data and apply a toUpperCase function to format it.
现在heatmap上面不显示值，只显示颜色，则么设置能让颜色块上面显示值。有没有办法制定显示数据中的第几个值，然后能不能format这个值，比如加一个toUpperCase()的函数。

### Expect 期望结果
Show labels on tiles
heatmap显示值

**Comment by xiguaxigua** [comment]
可以使用 extend 属性的回调函数方式实现。 https://jsfiddle.net/074yqc6r/8/
