### ISSUE TITLE
 父容器发生长度、宽度变化时，以及左右浮动时，v-chart无法响应

### ISSUE THREAD

**Issue by DarkRake** [ElemeFE/v-charts#386]
### Summary 简述

 父容器发生长度、宽度变化时，以及左右浮动时，v-chart无法响应

### Expect 期望结果

动态调整父容器宽度、高度、以及浮动属性时，v-chart作为子组件应该适配影响

### Reproduce 重现示例

[https://jsfiddle.net/enmdjb3w/5/](url)

**Comment by xiguaxigua** [comment]
可以将宽高属性传给组件 https://jsfiddle.net/enmdjb3w/8/ 。

**Comment by DarkRake** [comment]
在我的工程中，看到了这样一个神奇的现象，v-line的高度，宽度属性也传递过去了，但是所生成的内层div以及canvas，大小均没有响应。
父组件中使用v-for，进行循环调用v-line，v-line的配置项，均被封装到了对象中。
想象入下图，jsfiddle上组件子组件不太好弄。
![image](https://user-images.githubusercontent.com/13619406/41698679-44119bc6-7552-11e8-86d0-740bfb22163b.png)

**Comment by xiguaxigua** [comment]
使用的是最新的版本吗？
如果不是的话，可以先升级一下版本然后看效果。

**Comment by DarkRake** [comment]
从1.16升级至1.17.3，动态传进来的配置项，已经能够及时生效了，感谢v-charts
