### ISSUE TITLE
使用dataZoom时，切换数据导致渲染错误

### ISSUE THREAD

**Issue by luohao777** [ElemeFE/v-charts#387]
### Summary 简述

场景：使用dataZoom，设置一定的显示比例；
此时将data中rows所有数据变为0，放在点上为0，而图表却还有折线

当去掉dataZoom时，切换不会造成这个问题

### Expect 期望结果

切换后，图表正常应为一条直线

### Reproduce 重现示例

https://jsfiddle.net/seele7/8y3qdptL/20/

**Comment by xiguaxigua** [comment]
这个应该是 echarts 切换数据+datazoom 时触发的一个数值计算错误的问题，重新渲染组件就可以了。
https://jsfiddle.net/8y3qdptL/38/

**Comment by xiguaxigua** [comment]
还有另外一种修改方式，使用 afterConfig 属性修改 options 内容，这样在页面上的表现会更好一些 https://jsfiddle.net/8y3qdptL/53/ 。

**Comment by luohao777** [comment]
问题得到了解决，感谢
