### ISSUE TITLE
resizeable设置为true，对图表组件做缓存的问题

### ISSUE THREAD

**Issue by Htongbing** [ElemeFE/v-charts#388]
### Summary 简述
当对图表组件做缓存时，切换出组件，然后改变视口的宽或者高，再次切回来图表组件不显示，要触发视口的resize才会再次显示，将resizeable设置为false时这个问题不会出现。

### Expect 期望结果
将resizeable设置为true并对图表组件做缓存的情况下，切出去改变视口宽高再切回来图标组件能正常显示。

**Comment by xiguaxigua** [comment]
当图表设置了 `resizeable: true` 之后，组件内部会监听浏览器的 resize 事件并相应的 resize 图表，
当组件 被 keep-alive 并隐藏，resize 时将会因为没有宽高而导致显示不出来，再次展示图表的时候就会变成空白。
当前版本下的一个解决办法是将 resizeable 设为 false，然后在页面中处理 reize 的逻辑：当组件被缓存时不 resize，当组件展示时调用 resize。
第二个方案是动态赋值 resizeable ，缓存时将这个值设置为空。
第三个方案是在组件内发生 resize 时检测容器宽度

第一个方案当前版本可行，第二、三个方案更方便不过需要稍等下午发布一个版本。

**Comment by xiguaxigua** [comment]
升级版本（1.17.4） 再试试。

**Comment by Htongbing** [comment]
非常感谢
