### ISSUE TITLE
When I pass the param 'xAxis' or 'yAxis, it give me a warn

### ISSUE THREAD

**Issue by whirly77cai** [ElemeFE/v-charts#39]
Prop "xaxis" is passed to component <VeLine>, but the declared prop name is "xAxis". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "x-axis" instead of "xAxis".
But actually I passed "xAxis"

**Comment by xiguaxigua** [comment]
Do you want to use `xAxis` like [this](https://jsfiddle.net/vue_echarts/aa7ojxyt/24/) ?

And if not, can you provide a simple example?

**Comment by xiguaxigua** [comment]
The doc is currently missing examples of such props, I will fill this part as soon as possible.

**Comment by whirly77cai** [comment]
I code like that: ":xAxis="foo"", but the browser console warned me what I first commented. It just a vue tip.
And I find out that the splitLine can not be customized by passing  the param `xAxis:{splitLine:{show:true}}.`
I guess that if u give it a fixed theme
`echarts.registerTheme('ve-chart', {
  categoryAxis: {
    axisLine: { show: false },
    axisTick: { show: false },
    splitLine: { show: false }
  },
  valueAxis: {
    axisLine: { show: false }
  },
  line: {
    smooth: true
  },
  grid: {
    containLabel: true,
    left: 10,
    right: 10
  }
});`
In order to show the xAxis's splitLine, I give it a new theme by the :theme

**Comment by xiguaxigua** [comment]
Yes, things just as you think. now there are two methods to customize `splitLine`:

- reset the theme by `theme` or `themeName` prop
- use `afterConfig` prop to edit `options` before `setOption`

And I think I will choose the first way if I meet the same requirement.

But, in the next version, I will add these props to component or settings in order to customize them easier.

In addition, if you want to use `xAxis`, It need to be wrote such as `x-axis`.
https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

**Comment by whirly77cai** [comment]
Hi! Sorry to disturb you.
There is a situation that make me puzzled. I just pass a theme like “{}”. It shows two bold lines. Not so beautiful.
[cid:image003.png@01D3410E.7DFD3490]
How to take these two lines out? Hope u to give me some advise. Thx!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 西瓜<mailto:notifications@github.com>
发送时间: 2017年8月21日 17:26
收件人: ElemeFE/v-charts<mailto:v-charts@noreply.github.com>
抄送: whirly77cai<mailto:xieriver@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ElemeFE/v-charts] When I pass the param 'xAxis' or 'yAxis, it give me a warn (#39)


Yes, things just as you think. now there are two methods to customize splitLine:

  *   reset the theme by theme or themeName prop
  *   use afterConfig prop to edit options before setOption

And I think I will choose the first way if I meet the same requirement.

But, in the next version, I will add these props to component or settings in order to customize them easier.

In addition, if you want to use xAxis, It need to be wrote such as x-axis.
https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case

―

**Comment by xiguaxigua** [comment]
Image can't display, and can u upload it again with github web page?

**Comment by whirly77cai** [comment]
![a](https://user-images.githubusercontent.com/18453908/31329168-5d9a55e8-ad0b-11e7-89fa-7b2b2cbee40f.png)

**Comment by xiguaxigua** [comment]
I see, u can set this prop in theme
```js
this.chartTheme = {
  valueAxis: {
    axisLine: { show: false }
  }
}
```
with a smal example https://jsfiddle.net/jepw6dy2/88/ .

**Comment by whirly77cai** [comment]
How to set the font size of the province in the map? I can not find out the config option in the document...
![5 fagns tjqpol1sp62 v](https://user-images.githubusercontent.com/18453908/31573279-26cda69e-b0eb-11e7-9e02-cd34787ca61a.png)
