### ISSUE TITLE
如何设置饼状图或者环形图在X轴的偏移量

### ISSUE THREAD

**Issue by JohnsonWQ** [ElemeFE/v-charts#391]
### Summary 简述

如题：如何设置饼状图或者环形图在X轴的偏移量，在示例中只看到了“”offsetY“可以设置在Y轴上的偏移量，但是并没有定义在X轴上的方法，通过echart中的“”center:[20,30]“”在 :settings="",中无效，在:extend中也无效

### Expect 期望结果
求告知定义X轴偏移量方法

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/p1d2skq9/

**Comment by PLQin** [comment]
jsfiddle.net 在中国大陆已经无法访问, 求更新!
