### ISSUE TITLE
请教下，怎么实现混合图表？

### ISSUE THREAD

**Issue by 285858315** [ElemeFE/v-charts#392]
例如：[http://echarts.baidu.com/examples/editor.html?c=mix-line-bar](http://echarts.baidu.com/examples/editor.html?c=mix-line-bar)

**Comment by xiguaxigua** [comment]
折线图加柱状图 可以在文档中找到使用方法 https://v-charts.js.org/#/histogram?id=%E6%9F%B1%E7%8A%B6%E5%9B%BE%E6%8A%98%E7%BA%BF%E5%9B%BE

其他类型的混合图表，大部分可以使用 extend 修改 series 实现，少部分可能会复杂一些，后续会增加一个专门用来做图表混合的组件。

**Comment by 285858315** [comment]
好的，谢谢。
