### ISSUE TITLE
X-axis with AM/PM not sorted correctly 时间轴加入上午下午不再按时间排序

### ISSUE THREAD

**Issue by WangHansen** [ElemeFE/v-charts#398]
### Summary 简述
时间轴加入am/pm之后会先显示下午再显示上午
AM/PM我使用moment显示的
x-axis would show pm before am when am/pm is enabled
I used moment.js for am, pm display

code:
```javascript
moment.updateLocale('en', {
  meridiem: function (hour) {
    if (hour >= 6 && hour <= 17) {
      return "AM";
    } else {
      return "PM";
    }
  } 
}) 
...
let timeGroup = _.groupBy(this.data, function (value) {
    return moment(value.timestamp).format("ddd, MMM Do YYYY, a")
})
...
```

### Expect 期望结果
先显示上午再显示下午
show am before pm

### Reproduce 重现示例

![screen shot 2018-06-26 at 4 23 07 pm](https://user-images.githubusercontent.com/15679461/41944583-47dc77c6-795d-11e8-87b6-ca442c475ab4.png)

**Comment by xiguaxigua** [comment]
按照国际标准 [十二小时制](https://zh.wikipedia.org/wiki/%E5%8D%81%E4%BA%8C%E5%B0%8F%E6%99%82%E5%88%B6) ，把时间的判断逻辑修改一下应该就行了。
如果需求是按照上面的这种逻辑来判断的话，可以使用 x 轴默认的类目轴，然后在获取到数据后，对数据的维度进行操作（修改文案，补充遗漏的数据等），然后赋值给组件。

**Comment by WangHansen** [comment]
不太懂你的意思，我现在就是在获取数据之后赋值给组件的。x轴的设置我都是用的默认的，没有改变什么。但是现在自动呈现出来的就是反着的顺序。

**Comment by xiguaxigua** [comment]
按照标准，am 是 0~12，pm 是 12~24，而你的时间逻辑里写的是 am 为 6~17，echarts 在横轴打点时使用的估计应该是0点和12点，所以就会出现点到的情况，可以通过修改时间判断逻辑来修复顺序上的问题。
