### ISSUE TITLE
How to get source data(rows) after dataOrder ？

### ISSUE THREAD

**Issue by qiaolevip** [ElemeFE/v-charts#402]
### Summary 简述
如何获取排序后的数据？
原始数据经过：dataOrder排序了

### Expect 期望结果
```
tooltip: {
  formatter: v => {
     console.log(${this.score.data.rows[v[0].dataIndex]);
     //这里如何通过dataIndex获取排序后的数据
  }
},
```

### Reproduce 重现示例

左图为排序后的数据：   右边为原始数据
![image](https://user-images.githubusercontent.com/996755/41953690-8f4158a0-7a09-11e8-8073-b612d14c25aa.png)

**Comment by xiguaxigua** [comment]
当前版本没有把转化好的数据挂到组件上，可以使用与组件内处理逻辑相同的代码再重新生成一份相同的数据出来 https://github.com/ElemeFE/v-charts/blob/master/src/packages/bar/main.js#L316-L329 。

**Comment by qiaolevip** [comment]
好的，目前已经是这样先处理了。
话说这样的话，dataOrder功能是有点鸡勒了。
