### ISSUE TITLE
移动端使用ve-bmap，自定义label的单位问题

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/v-charts#403]
### Summary 简述
移动端使用ve-bmap，自定义label的单位问题，采用formatter的api，自定义绘制，但是我移动端使用的是rem，formatter的样式，都是以px为单位。
如果我想要以rem为单位，该怎办？
当然我不是想在这输入rem的值，而是通过我输入px的值，然后到页面转为rem的单位，参考px2rem

### Expect 期望结果
formatter的rem解决

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/24503453/41956058-ee02e2f4-7a14-11e8-875a-ed890b9dcbe4.png)

**Comment by xiguaxigua** [comment]
https://github.com/apache/incubator-echarts/issues/5280

看上去 echarts 目前还不支持这种方式。

**Comment by MaJiaXuan** [comment]
那换一种方式，label支持用dom做？

**Comment by xiguaxigua** [comment]
应该也是不行的 https://jsfiddle.net/vue_echarts/aj9cemsf/25/ ，
echarts 对于这种问题的解决方案是使用一种类似 media query 的方式实现，可以尝试一下，不过感觉这种方式并没有使用 rem 灵活方便。

**Comment by MaJiaXuan** [comment]
这种也不行，算了，我先设置死的吧，期待后面能加上支持rem，要是能自定义dom就更好了
