### ISSUE TITLE
折线图的area背景色设置始终不生效！

### ISSUE THREAD

**Issue by sowee121** [ElemeFE/v-charts#405]
### Summary 简述
折线图的area背景色设置始终不生效！demo上是好的，可是项目中相同的用法就是不生效！

### Expect 期望结果
![image](https://user-images.githubusercontent.com/18671659/42014530-5b73dcba-7ad5-11e8-8e18-7be3ab2d5d61.png)

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/18671659/42014498-3256ac7c-7ad5-11e8-843c-4b8868ee7d7e.png)

**Comment by xiguaxigua** [comment]
使用 extend 属性设置应该是没问题的 https://jsfiddle.net/jf7dqr1a/1/ ,提供一个重现的示例吧。

**Comment by sowee121** [comment]
https://jsfiddle.net/jf7dqr1a/17/
改到示例上是好的，但在项目里就是不正常，项目里是全局引入的，有木有可能还少什么依赖？

**Comment by xiguaxigua** [comment]
```js
this.chartExtend = {
      series: {
        areaStyle: {
          normal: {
            color: '#ccc'
          }
        }
      }
    }
```

试试这样写是否会生效

**Comment by sowee121** [comment]
这样生效了！这是因为echarts的版本问题吗？

**Comment by xiguaxigua** [comment]
是的，3.x 版本需要这样写才能生效
