### ISSUE TITLE
折线图里面怎么让显示的图像是占满整个图表的？

### ISSUE THREAD

**Issue by Jordonwang** [ElemeFE/v-charts#407]
### Summary 简述
怎么让折线图里面的图像是占满整个图表的？

![_20180628170654](https://user-images.githubusercontent.com/25704787/42025048-4369e026-7af6-11e8-9d5e-29a8df48a037.png)

我看了最后一个折线图示例配置如下可以占满
`
this.chartSettings = {
      xAxisType: 'time'
}
`
但是我配置其他的并没有生效，不明白这个xAxisType对应的可选值: category, value, time, log都是什么用途啊

**Comment by xiguaxigua** [comment]
占满图 通过设置 xAxis.boundaryGap 实现，这样设置有一个缺点，就是横轴自适应计算会有误差，可能会导致最右侧的文字被遮挡，此时设置文字旋转就可以解决，具体的配置方法可以参考下面的示例。
https://jsfiddle.net/b67sdu4k/1/

**Comment by Jordonwang** [comment]
可以了 ，thanks!
