### ISSUE TITLE
会考虑加入图表标题吗？

### ISSUE THREAD

**Issue by niices** [ElemeFE/v-charts#41]
会考虑加入图表标题吗？

**Comment by xiguaxigua** [comment]
@niices  你说的是这个意思吗？https://jsfiddle.net/aa7ojxyt/25/

![image](https://user-images.githubusercontent.com/9931685/29961372-0b217cfc-8f32-11e7-9f37-52780d5d7ebe.png)

**Comment by niices** [comment]
是的  3Q😁
