### ISSUE TITLE
图表名字怎么添加

### ISSUE THREAD

**Issue by hejindan** [ElemeFE/v-charts#411]

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/hcyjwed5/2/

**Comment by hejindan** [comment]
chartTitle: {text: '标题', left: 'middle', bottom: 20}

**Comment by hejindan** [comment]
@xiguaxigua 3ks 
chartTitle: {text: '标题', left: 'middle', bottom: 20}
 <ve-chart :data="chartData" :settings="chartSettings" :title="chartTitle"></ve-chart>

**Comment by xiguaxigua** [comment]
no 3ks :grinning:
