### ISSUE TITLE
ve-line 折线图可以让某条数据特别标记出来吗？

### ISSUE THREAD

**Issue by Jordonwang** [ElemeFE/v-charts#416]
### Summary 简述
ve-line 折线图的可以在渲染后的界面中自定义标记吗？比如现在是每个都是一样的圆点，能特别高亮某个颜色在某个地方的圆点吗？

### Reproduce 重现示例

![_20180705162414](https://user-images.githubusercontent.com/25704787/42311222-eb690a26-806f-11e8-833a-602574fdbbb0.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/efamchun/10/

**Comment by Jordonwang** [comment]
看到效果了，这个特别提示的颜色可以控制的吗? 还有鼠标悬浮上去这个特别标注的点的提示也可以增加特别的提示吗？

**Comment by xiguaxigua** [comment]
样式的配置可以参考
http://echarts.baidu.com/option.html#series-line.data
tooltip 的配置可以通过自定义 tooltip 内容实现
https://jsfiddle.net/efamchun/28/

**Comment by Jordonwang** [comment]
明白了~ 非常感谢~~ 每次都很及时的回复
