### ISSUE TITLE
怎么设置标题和图的上下位置之间的距离

### ISSUE THREAD

**Issue by zhanwen** [ElemeFE/v-charts#417]
### Summary 简述

饼图的大小被缩放了，导致之间的距离增大

### Expect 期望结果
距离变小

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/11382789/42417197-1f5017f6-82b6-11e8-90aa-95660d3c7101.png)

**Comment by xiguaxigua** [comment]
距离的设置通过 center 来定义。 https://jsfiddle.net/vue_echarts/mx5z2rq8/2/

饼图上边缘与容器上边缘的距离 = center[1] - 饼图半径 radius ，如果 radius 设置成了百分比的话，当饼图缩小时，半径减小，就会导致间距变大，这个倒是没有太好的方案，可以尝试给饼图设置固定的 radius，或者容器定义最小宽度，来防止间距过大导致页面显示不优雅。

**Comment by zhanwen** [comment]
那这个标题能不能去掉呢，只保留图
