### ISSUE TITLE
loading失效

### ISSUE THREAD

**Issue by zhanwen** [ElemeFE/v-charts#418]
### Summary 简述

在`<ve-line :data="chartData" :loading="true”></ve-line>`,并且也引入了对应的css文件，就是没有出现loading的效果。

### Expect 期望结果
loading 转圈

**Comment by zhanwen** [comment]
自己解决了，呜呜

**Comment by cloudhuang** [comment]
@zhanwen 也遇到这个问题，是如何解决的？

**Comment by zhanwen** [comment]
记得当时应该是优先级的问题，有个 <style scope>
