### ISSUE TITLE
Echarts（Canvas）在容器display:none的时候无法渲染

### ISSUE THREAD

**Issue by niices** [ElemeFE/v-charts#42]
具体是我在将v-charts的图表嵌套到Element-UI的Tabs 标签页时，只有第一个标签页能渲染，剩下的display：none的容器里面无法渲染。
我在网上查到资料需要在显示的时候resize一下。
请问需要在什么时机，如何获取v-charts的图表对象进行resize呢？

**Comment by xiguaxigua** [comment]
#28 看看是不是这个问题

**Comment by niices** [comment]
是的  3Q😁

**Comment by xiguaxigua** [comment]
no 3Q😀

**Comment by niices** [comment]
我的问题好像跟例子不太一样。
#28 可以通过设置默认激活包含图表tab页解决。
![image](https://user-images.githubusercontent.com/8327775/29967198-0be1d874-8f48-11e7-8a53-72f1d042aeb6.png)

但是我有三个tab里面都有图表。
第一个能显示，然后后面两个都无法显示。
然后我打印`this.$refs`对象为空。
![image](https://user-images.githubusercontent.com/8327775/29967247-5518695e-8f48-11e7-8780-4fb503027088.png)

**Comment by niices** [comment]
我的问题好像跟例子不太一样。
#28<https://github.com/ElemeFE/v-charts/issues/28> 可以通过设置默认激活包含图表的tab页解决。
[image]<https://user-images.githubusercontent.com/8327775/29967198-0be1d874-8f48-11e7-8a53-72f1d042aeb6.png>

但是我有三个tab里面都有图表。
第一个能显示，然后后面两个都无法显示。
然后我打印this.$refs对象为空。
[image]<https://user-images.githubusercontent.com/8327775/29967247-5518695e-8f48-11e7-8780-4fb503027088.png>
在 2017年9月1日，18:42，西瓜 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #42<https://github.com/ElemeFE/v-charts/issues/42>.

**Comment by niices** [comment]
是我无知了 Vue用的不太熟- -
https://cn.vuejs.org/v2/api/#ref

**Comment by xiguaxigua** [comment]
所以，问题解决了？

**Comment by xiguaxigua** [comment]
根据你的需求，重写了一个例子，看看能不能解决现在遇到的问题。
https://codepen.io/quietcoder/pen/JyjWvG

**Comment by niices** [comment]
用了一个很蠢的方法😂

发自我的 iPhone

在 2017年9月1日，22:01，西瓜 <notifications@github.com<mailto:notifications@github.com>> 写道：


根据你的需求，重写了一个例子，看看能不能解决现在遇到的问题。
https://codepen.io/quietcoder/pen/JyjWvG

**Comment by niices** [comment]
解决了  谢谢啦😁  昨晚下班回家断网了
