### ISSUE TITLE
散点图

### ISSUE THREAD

**Issue by zhanwen** [ElemeFE/v-charts#422]
### Summary 简述
请问下是否支持散点图，不是带有日期这种，比如x，y
![image](https://user-images.githubusercontent.com/11382789/42440178-87100b80-8397-11e8-8613-39d88605ee78.png)
而不是这种
![image](https://user-images.githubusercontent.com/11382789/42440192-921200a6-8397-11e8-91c8-654afa617f12.png)

### Expect 期望结果
或者其它实现

**Comment by xiguaxigua** [comment]
没太看懂你说的这两种之间的区别，可以详细描述一下吗？

**Comment by zhanwen** [comment]
![image](https://user-images.githubusercontent.com/11382789/42482851-912b2d22-841c-11e8-9d42-75fa52a8483d.png)
就是这种，但是想要x，y不要分开，而是表示的是一个点

**Comment by xiguaxigua** [comment]
> 如果三列数据，第一列作为x轴，其它两列当作数据，在这个图上面就会出现两种颜色的点，而不是想要的那个只有一个点

> 就是这种，但是想要x，y不要分开，而是表示的是一个点

想要的效果是这样的吗？ https://jsfiddle.net/w57jrmkt/5/

**Comment by zhanwen** [comment]
我将你的实例调成两列数据时，生成图形如下效果，当鼠标悬停在上面的时候，会显示三个数据，其中第三个数据为 `undefined`。当我增加到三列的时候，这个问题就没有了，也就是`columns`必须要三列吗？
[https://jsfiddle.net/w57jrmkt/11/](https://jsfiddle.net/w57jrmkt/11/)

**Comment by xiguaxigua** [comment]
第三列一般表示气泡的大小，也可以不需要，具体配置参考示例 https://jsfiddle.net/w57jrmkt/17/

**Comment by zhanwen** [comment]
好的，谢谢

**Comment by zhanwen** [comment]
作者您好，我发现散点图的横轴是不会从小到大排序的，而是按点分布的。还有一个是数据一多（200），横轴就只显示了几个点的坐标。如下
![image](https://user-images.githubusercontent.com/11382789/42545068-19e18c26-84e8-11e8-8909-6daca2e07e5a.png)
但是我在jsfiddle中却能正常显示横轴的数据，但横轴还是不能自动排序。
[https://jsfiddle.net/w57jrmkt/23/](https://jsfiddle.net/w57jrmkt/23/)

**Comment by xiguaxigua** [comment]
可以增加 dataZoom 控件看看能否解决问题。 https://jsfiddle.net/vue_echarts/w57jrmkt/30/

**Comment by zhanwen** [comment]
非常棒，原来这个是可以手动加的，那对应的这线图那个，下面的dataZoom是不是可以去掉，直接将dataZoom设置为空就行了？

**Comment by xiguaxigua** [comment]
> 那对应的折线图那个

是指的哪一个？

dataZoom 默认是没有值的，可以通过 extend 增加，也可以在组件上增加。

**Comment by zhanwen** [comment]
就是这个折线图，这个是`<ve-line></ve-line>`默认就带的，如果我想去掉的话，是不是就可以将dataZoom设置为空就行了，设置了结果还在，最后我是直接把`:dataZoom`属性去掉就没有了，感谢解答。
![image](https://user-images.githubusercontent.com/11382789/42745577-2120b1f2-8906-11e8-8a34-1c2be5af6efe.png)
