### ISSUE TITLE
条形图增加xAxis时，坐标轴名称出现两次，上下各一次

### ISSUE THREAD

**Issue by swliu920322** [ElemeFE/v-charts#425]
### Summary 简述
条形图增加xAxis时，坐标轴名称出现两次，上下各一次

### Expect 期望结果

应该只出现一次x坐标轴

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/19258473/42502086-bb0d8fc2-8467-11e8-9fd1-c4385601730e.png)

**Comment by xiguaxigua** [comment]
指定一下坐标轴就行了，默认是在两个坐标轴上都加的
```js
{
  'xAxis.0': {
    name: '办件量',
    nameGap: -10,
    nameLocation: 'start'
  }
}
```
https://jsfiddle.net/r415xua2/1/

**Comment by swliu920322** [comment]
好的，有些图还是挺正常的
