### ISSUE TITLE
图表宽度没有自适应父元素的宽度

### ISSUE THREAD

**Issue by sowee121** [ElemeFE/v-charts#431]
### Summary 简述
折线图随着窗口大小改变时，没有自适应父元素的宽度，这是有问题的！
![image](https://user-images.githubusercontent.com/18671659/42671665-c857b148-8693-11e8-8200-1c3626c72483.png)

### Expect 期望结果
![image](https://user-images.githubusercontent.com/18671659/42671650-b17de460-8693-11e8-9aee-163a31e0ba9e.png)

**Comment by xiguaxigua** [comment]
如果不是浏览器窗口的变化是不会出发图表宽度修改的，这种情况下可以在容器宽度变化后手动触发chart.resize 。

**Comment by sowee121** [comment]
当然是浏览器窗口啦，问题是有几个相似的折线图，只有其中某个会出现这个问题，还是偶现，一般窗口缩放速度较快的时候会出现，canvas的宽度计算出错的情况，所以就没有自适应父元素

![image](https://user-images.githubusercontent.com/18671659/42686238-da30a8e6-86c7-11e8-8797-ff8270295fbc.png)

![image](https://user-images.githubusercontent.com/18671659/42686269-f154feb4-86c7-11e8-9dbf-9a9bee6027ab.png)

**Comment by xiguaxigua** [comment]
- 可以尝试增加 resize 的延迟 `:resize-delay="400"`
- 可以尝试使用 svg 渲染看看会不会有改善

**Comment by psc0606** [comment]
“如果不是浏览器窗口的变化是不会出发图表宽度修改的，这种情况下可以在容器宽度变化后手动触发chart.resize 。”
怎么解决提到一非浏览器窗口变化导致的不自适应问题，我之前用echarts是直接chart.resize()，v-chart怎么弄啊？

**Comment by wangbing0417** [comment]
<ve-line
	:data="data"
	:extend="extend"
	:after-set-option-once="echarts=> echarts.resize()"
/>

使用钩子函数，after-set-option-once    :after-set-option-once="echarts=> echarts.resize()"
