### ISSUE TITLE
多条折线 不同的渐变色

### ISSUE THREAD

**Issue by yuzmb** [ElemeFE/v-charts#433]
### Summary 简述
用new echarts.graphic.LinearGradient，柱状图能实现，折线图就不行了

### Expect 期望结果

多条折线 不同的渐变色

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/8a3rjuf1/1/ 是这种效果吗？

**Comment by yuzmb** [comment]
对了对了，感谢

**Comment by MeetYouZi** [comment]
v-charts可以用new echarts？
