### ISSUE TITLE
柱状图设置xAxisType: 'value'不起作用

### ISSUE THREAD

**Issue by dyh333** [ElemeFE/v-charts#437]
### Summary 简述
this.chartSettings = {
    	xAxisType: 'value', // !!!
      metrics: ['访问用户', '下单用户'],
      dimension: ['日期']
    }

### Expect 期望结果
柱状图横过来显示

### Reproduce 重现示例
https://jsfiddle.net/dyh333/jora2wux/

**Comment by xiguaxigua** [comment]
> 柱状图横过来

是这种样式吗 https://v-charts.js.org/#/bar

**Comment by dyh333** [comment]
@xiguaxigua 是的 谢谢
