### ISSUE TITLE
map 里的itemStyle 存在问题。应该是 Object 类型的，但是现在是 Boolean

### ISSUE THREAD

**Issue by xkcoding** [ElemeFE/v-charts#44]
![image](https://user-images.githubusercontent.com/10429917/30421980-1d0d529e-9971-11e7-8238-949901e17233.png)

**Comment by xiguaxigua** [comment]
没错，这里确实写得有问题。type 是 Boolean和Object，如果设置为true的话，会有一个默认样式，false不显示默认样式，如果是Object，则作为样式配置直接加到图上。

**Comment by xkcoding** [comment]
但是我的itemStyle是Object的，仍然是默认样式

**Comment by xiguaxigua** [comment]
写了一个小例子，可以参考一下 http://jsfiddle.net/vue_echarts/1fwe4tt7/4/

**Comment by xkcoding** [comment]
额额。谢啦。我貌似写错位置了。直接v-bind:itemStyle了。。谢谢谢谢。不过那个文档那里的类型还是需要修改下，再次感谢！！！

**Comment by xiguaxigua** [comment]
文档之前写的不是很完善，缺少一些针对性的例子，近期就会全部补充上。

**Comment by xkcoding** [comment]
辛苦了。感谢感谢！
