### ISSUE TITLE
Display XAxis as string instead of value

### ISSUE THREAD

**Issue by phongtrandang** [ElemeFE/v-charts#440]
### Summary 简述
When using Histogram chart and set `XAxisType: 'value'`, my XAxis is displaying  it's value number, but i want to display my x Axis as a String label

### Expect 期望结果
in Histogram Chart, How can i display my x Axis as a String label instead of it's value when my setting is `XAxisType: 'value'`

### Reproduce 重现示例
![create a new pen](https://user-images.githubusercontent.com/15318099/42748300-e5aff5d4-8909-11e8-8ace-73b708b32d3b.png)

**Comment by xiguaxigua** [comment]
what kind of `string label` do you want?
if you want to formate xAxis label, you can set `extend` prop to do it such as this [example](https://codepen.io/xiguaxigua/pen/vaLbRL?editors=1010) .

**Comment by phongtrandang** [comment]
For example, if my XAxis is an array of unix date, the rows value could be:
`
["date": 1531760400, "sent": 150, "opened": 250, 
"date": 1535760400, "sent": 150, "opened": 250]
`
the value is too large and then v-charts can not be rendered as expected

**Comment by xiguaxigua** [comment]
as your example, I understand that your need is to let the x axis appear as formatted time. if it is this, you can set xAxis label use formatter as the [demo](https://codepen.io/xiguaxigua/pen/vaLbRL?editors=1010) , if not ,please say more in detail.

**Comment by phongtrandang** [comment]
yea, thank you for your example, i can format the xAxis label now, but i got another problem when my xAxis value is unix time, i think the value is too large and v-charts is died, do you have any solution for my situation, i have comment on this [demo](https://codepen.io/WindyCloud9/pen/oMdKmj?editors=1011).

**Comment by xiguaxigua** [comment]
It seems that directly assigning a unix timestamp can cause computational problems. You can try to convert the timestamp into a formatted string and then assign it to chartdata. https://codepen.io/xiguaxigua/pen/yqqELj?editors=1111

**Comment by phongtrandang** [comment]
thanks, i can see that in your example, xAxisType is `time`, but my purpose to use xAxisType = value is that : I want to group two columns overlay to each other like this https://codepen.io/WindyCloud9/pen/PBdQKW?&editors=101

**Comment by xiguaxigua** [comment]
https://codepen.io/xiguaxigua/pen/yqqELj?editors=1011
such as this demo ?

**Comment by phongtrandang** [comment]
yeah, that's exactly what i need, thank you very much @xiguaxigua
