### ISSUE TITLE
按照echarts官网xAxis配置样式不起作用

### ISSUE THREAD

**Issue by janxy** [ElemeFE/v-charts#445]
### Summary 简述

![qq 20180724175217](https://user-images.githubusercontent.com/10809790/43131878-b14f959c-8f6c-11e8-8e64-02e6489cc7c8.png)

### Expect 期望结果

修改红框标识线条的颜色，请教！

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/jb7cpwe3/6/ 是这种样式吗？

**Comment by janxy** [comment]
谢谢，是这样的
