### ISSUE TITLE
是否可以帶入參數後自行產生客製化 tooltip

### ISSUE THREAD

**Issue by kevin10410** [ElemeFE/v-charts#448]
### Summary 简述
是否可以帶入參數後自行產生客製化 tooltip

### Expect 期望结果
產生客製化 tooltip

### Reproduce 重现示例

客製化前
![image](https://user-images.githubusercontent.com/34804798/43185619-feb9946a-901e-11e8-9e5a-c9e52158b6cc.png)
客製化後
<img width="219" alt="2018-07-25 3 26 02" src="https://user-images.githubusercontent.com/34804798/43185648-13360cfc-901f-11e8-81e8-4bdf2b66a27e.png">

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/rLednaq5/1/

**Comment by kevin10410** [comment]
自己解掉了 Thanks!
`this.chartExtend = {
      tooltip: {
        padding: 0,
        backgroundColor: '#FAFAFA',
        formatter(items) {
          const account = items[0].value;
          const time = new Date(Math.floor(items[1].value * 10000000000000));
          const year = time.getFullYear();
          const month = `0${time.getMonth() + 1}`.slice(-2);
          const date = `0${time.getDate()}`.slice(-2);
          const hourStart = `0${time.getHours()}`.slice(-2);
          const hourEnd = `0${time.getHours() + 1}`.slice(-2);
          const tooltip = `<div class="tooltip"><p class="tooltip__time"><span>${year}/${month}/${date}</span><span>${hourStart}:00～${hourEnd}:00</span></p><div class="tooltip__data"><p class="tooltip__data--value">${account}</p><p class="tooltip__data--describe">Trips</p><p class="tooltip__data--describe">(times)</p></div></div>`;
          return tooltip;
        },
      },
    };`
