### ISSUE TITLE
升级到版本 "v-charts": "^1.17.8" 后 x轴的键出现相同值时 折线图异常 

### ISSUE THREAD

**Issue by jinggoing** [ElemeFE/v-charts#450]
### Summary 简述
升级到版本  "v-charts": "^1.17.8" 后
this.chartData = {
        columns: ['时间', '得分'],
        rows: [
            {'得分':69, '时间': '01:44'},
            {'得分':57, '时间': '23:55'},
            {'得分':57, '时间': '00:20'},
            {'得分':63, '时间': '00:35'},
            {'得分':63, '时间': '01:29'},
            {'得分':57, '时间': '01:44'},
            {'得分':63, '时间': '01:53'}
        ]
      }
![image](https://user-images.githubusercontent.com/16497547/43241180-9e2b60c0-90cc-11e8-8402-1f6a8f595b97.png)

升级到版本  "v-charts": "^1.17.8" 前  "v-charts": "^1.17.4"  正常
![image](https://user-images.githubusercontent.com/16497547/43241246-082581f4-90cd-11e8-82bf-985eac243740.png)

### Expect 期望结果

![image](https://user-images.githubusercontent.com/16497547/43241249-0bc5b46e-90cd-11e8-8910-39cc7aa679ec.png)

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/16497547/43241180-9e2b60c0-90cc-11e8-8402-1f6a8f595b97.png)

**Comment by xiguaxigua** [comment]
发生样式变化的原因是当前版本使用了比较不容易触发 bug 的内部数据格式，从数据的角度来讲，单维度单指标的数据，每个维度对应的数值应该是唯一的，可以在获取到数据之后，手动加一条过滤，将重复的数据过滤掉即可。
https://jsfiddle.net/gdzpf5q2/5/

**Comment by Hnnphone** [comment]
单维度多指标也有这种情况啊
