### ISSUE TITLE
用自定义图片做背景，能否实现像地图热力图那样的效果？

### ISSUE THREAD

**Issue by janxy** [ElemeFE/v-charts#451]

**Comment by xiguaxigua** [comment]
没太看明白，提供一些具体的信息吧

**Comment by janxy** [comment]
热力图的例子里面，第四个热力图效果，背景为中国地图的那个，，，可以实现把中国地图换成自定义图片吗

**Comment by xiguaxigua** [comment]
这种样式 https://jsfiddle.net/a0csj4b9/ ？

**Comment by janxy** [comment]
你好，就是热点柑橘left和top的位置显示呢。

**Comment by janxy** [comment]
你好，就是热点根据left和top的位置显示呢。

**Comment by xiguaxigua** [comment]
这种样式 echarts 还不支持 https://github.com/apache/incubator-echarts/issues/2378
