### ISSUE TITLE
VeChart 组件官方文档里没有

### ISSUE THREAD

**Issue by iTaster** [ElemeFE/v-charts#459]
### Summary 简述

我在webpack 里面的图表组件都是一个个单独引入的，

但是在写图标切换时发现`ve-chart`组件根本就不会被渲染，然后找了一下依赖包

`import VeChart from 'v-charts/lib/chart.common'              //todo: 专门用来切换折线图，饼图，柱状图`

加上这个就可以使用了，但是感觉这个是全部组建的综合体，不知道正确的应该是引用那个组件

**Comment by xiguaxigua** [comment]
这个组件最初的设计是被用来做折线图，饼图，柱状图的切换，类似于 echarts 的 toolbox 中的图表切换的功能，但是现在来看，其实这个组件应该承载的东西可能并不局限于此，而使用这个组件实现图表切换有时候显得不是很灵活，所以，当前版本下，多图表切换的需求推荐使用 component 组件实现
`<component is="ve-line" data settings></component>`, 而 ve-chart 组件，后面会被修改为实现多图表切换，融合等的一个高阶组件。
