### ISSUE TITLE
小问题，进来帮忙看下

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#46]
![image](https://user-images.githubusercontent.com/19297519/30464069-e5dd04ae-9a01-11e7-8dcb-038de97df98a.png)
如何把这个白色的小点去掉

**Comment by xiguaxigua** [comment]
写了一个小例子，参考一下。
https://jsfiddle.net/vue_echarts/jepw6dy2/68/

当前版本没有提供部分不常用属性的配置，下一个版本计划处理掉这部分属性，目前可以通过 afterConfig 实现。

**Comment by 15521054523** [comment]
您好，您可能理解错了我的意思，我的意思不是隐藏圆点，而是隐藏下面的小竖线
![image](https://user-images.githubusercontent.com/19297519/30465007-56d2f0ba-9a07-11e7-828b-127cf5a3eae8.png)

**Comment by 15521054523** [comment]
因为我也是把下面的值设置了空值，然后想着顺便把下面的小竖线也给去掉
![image](https://user-images.githubusercontent.com/19297519/30465022-6ce2dc26-9a07-11e7-93f1-349ca74d38cb.png)

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/jepw6dy2/72/ 是这个样式？

**Comment by 15521054523** [comment]
对的，太谢谢了
