### ISSUE TITLE
百度地图点击上面的某个点，怎么让这个点定位到中间来

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/v-charts#460]
### Summary 简述
百度地图点击上面的某个点，怎么让这个点定位到中间来

### Expect 期望结果
点击地图上面某个点，然后让这个点显示到屏幕的中间

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/24503453/43443103-80cf1bde-94d2-11e8-9834-2b981c7162fd.png)

**Comment by xiguaxigua** [comment]
点击标记的点可以获取到这个点的坐标，然后调用百度地图设置中心的方法就可以了。
不知道是不是你的需求，如果不是的话，可以提供一个 demo，我会根据你的 demo 提供具体的解决方案。

**Comment by MaJiaXuan** [comment]
![image](https://user-images.githubusercontent.com/24503453/43443572-d7b02e60-94d3-11e8-908e-daf1323521a8.png)
![image](https://user-images.githubusercontent.com/24503453/43443648-10882b66-94d4-11e8-8b6b-eb039e408bc6.png)
点的数据我是拿到了，只是这要如何重新设置？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/pLv5ctqx/9/
参考这个示例，tooltip 可以通过 dispatchAction 解决。
重绘的问题具体体现在什么方面呢？

**Comment by MaJiaXuan** [comment]
但是你这个 dispatchAction 会导致我点击的时候，tooltip就隐藏了，要长按才能显示出来。
重绘表现在，移动地图的时候，那些点并不是跟我鼠标移动，而是待我移动结束后，那些点才回到原来的位置。
@xiguaxigua

**Comment by xiguaxigua** [comment]
> 点击的时候，tooltip就隐藏了，要长按才能显示出来
我这边的情况是：鼠标浮在点上，显示 tooltip，点击后，地图移动中心，tooltip 消失，再次 hover 时触发 tooltip，没有出现长按才能显示。
> 那些点并不是跟我鼠标移动，而是待我移动结束后，那些点才回到原来的位置
是指点的移动没有跟上地图的移动吗？

如果方便的话，提供一下示例吧，这样比较方便重现你遇到的问题。

**Comment by MaJiaXuan** [comment]
https://jsfiddle.net/8amc37ht/24/
@xiguaxigua 
要在移动端看，而不是PC端

**Comment by MaJiaXuan** [comment]
我解决了，我在动画渲染结束时，手动重新计算 tooltip的位置
