### ISSUE TITLE
设置柱间隔导致全部柱消失

### ISSUE THREAD

**Issue by Neltharion3927** [ElemeFE/v-charts#461]
### Summary 简述
按文档设置  xAxisType: 'value' 导致柱全部消失。

### Expect 期望结果
各个柱之间无间隙

### Reproduce 重现示例

```
<div id="app">
  <ve-histogram
    :data="chartData"
              :settings="chartSettings"
    :extend="chartExtend">
  </ve-histogram>
</div>
```
```
data () {
this.chartSettings = {
        xAxisType: 'value'
      }
···
}
```
![360 187201217071101](https://user-images.githubusercontent.com/19289718/43445251-85cc53ee-94d8-11e8-93e8-1f673c399ec9.png)

**Comment by xiguaxigua** [comment]
提供一下示例的地址吧

**Comment by xiguaxigua** [comment]
维度（流水线）的值并不是数字，所以就会导致显示失败，需求是展示成什么样式呢？

**Comment by Neltharion3927** [comment]
需求就是 流水线这里的四个柱之间能够没有空隙

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/ty81sq6d/1/ 是这种样式吗？

**Comment by Neltharion3927** [comment]
是的，万分感谢
