### ISSUE TITLE
参数set-option-opts失效情况

### ISSUE THREAD

**Issue by loyalove** [ElemeFE/v-charts#465]
### Summary 简述

参数set-option-opts=false在同时使用legend=legend（或者 extend）失效，
在change数据后，legend设置重置了

### Expect 期望结果
在change数据后，legend不设置

### Reproduce 重现示例
[https://codepen.io/loyalove/pen/gjKjXE?&editors=101](https://codepen.io/loyalove/pen/gjKjXE?&editors=101)

**Comment by xiguaxigua** [comment]
是这种效果吗？ https://codepen.io/xiguaxigua/pen/LBBmaK?editors=1010

**Comment by loyalove** [comment]
赞
