### ISSUE TITLE
是否支持左右滑动

### ISSUE THREAD

**Issue by picnic-yu** [ElemeFE/v-charts#47]
需求： 需要展示一个月的数据，但是初始化可展示10个，其他的数据左右滑动显示，但是不要和移动端上下滑动冲突，是否支持

**Comment by xiguaxigua** [comment]
可以使用dataZoom实现这个功能，写了一个小例子：
https://jsfiddle.net/vue_echarts/jepw6dy2/75/

需要注意的是，如果使用的是webpack加载的话，需要额外加载DataZoom模块
```js
import 'echarts/lib/component/dataZoom'
```
