### ISSUE TITLE
v-charts 设置工具箱 toolbox 文字提示显示不全

### ISSUE THREAD

**Issue by ltxlouis** [ElemeFE/v-charts#470]
### Summary 简述
按照官方示例, 其他 -> 属性配置示例(1) -> 设置工具箱进行配置
https://v-charts.js.org/#/props-demo1
最后一个工具的悬浮提示文字会显示不全, 只显示 _保存为图_
还有x轴文字显示不全的问题, 除了旋转的办法, 不知道能不能自己定义边距呢
https://github.com/ElemeFE/v-charts/issues/210

### Reproduce 重现示例
https://v-charts.js.org/#/props-demo1

**Comment by xiguaxigua** [comment]
1. toolbox 可以往左边挪一挪 https://jsfiddle.net/38gw6cds/ 。
2. 定义边距也可以 https://jsfiddle.net/m1hdcmf4/112/ 。

**Comment by ltxlouis** [comment]
解决了, 看来还是要多看看文档, 非常感谢!
