### ISSUE TITLE
折线图如何设置全选 / 全不选

### ISSUE THREAD

**Issue by EryouHao** [ElemeFE/v-charts#476]
### Summary 简述

![image](https://user-images.githubusercontent.com/17328747/43881309-5a4bfabe-9bde-11e8-8033-804f6ee97f40.png)

### Expect 期望结果
想实现在 legend 这里添加一个选项，点击后可以控制 所有的 legend 全选 全不选

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/pwtb85yj/11/ 是这种样式吗？

**Comment by EryouHao** [comment]
@xiguaxigua 是的，感谢。祝生活愉快
