### ISSUE TITLE
tab切换问题，报错Error in nextTick: "TypeError: Cannot read property 'echarts' of undefined"

### ISSUE THREAD

**Issue by BOB262** [ElemeFE/v-charts#485]
### Summary 简述
console两个报错以下：
Error in nextTick: "TypeError: Cannot read property 'echarts' of undefined"

Cannot read property 'echarts' of undefined

我按https://v-charts.js.org/#/skill-demo 这个示例，图表没组件，使用ve-histogram 三个图表，切换正常没报错，然后我把ve-histogram再做一个子组件，方便复用这个图表组件，父组件获取数据通过prop向子组件（图表）传递数据，，tab切换显示正常，但是tab每次切换console一直报错。
我看了 #455 不知道是不是$children问题？我试了还是不行，请求助。
在发现新一个，默认在第一个tab（没有图表）点击切换到第二个tab，图表有加载动画，点击切换到第三个tab，图表没有动画。
### Expect 期望结果
虽然显示正常，可是我希望不要红叉的报错，请问问题在哪儿？

### Reproduce 重现示例

![tim 20180815162820](https://user-images.githubusercontent.com/24404857/44139045-7d3e4a1c-a0a8-11e8-9930-9d90e83691b4.png)
图表子组件代码如下：
![tim 20180815163522](https://user-images.githubusercontent.com/24404857/44139332-58b29d32-a0a9-11e8-8404-2660caa1a0f4.png)
父组件代码如下：
![tim 20180815163557](https://user-images.githubusercontent.com/24404857/44139334-5e2a5dae-a0a9-11e8-9f5d-1124b8c55512.png)

**Comment by xiguaxigua** [comment]
看上去是没有找到对应的 ref `this.$refs[`chart`]` ，看看是不是没有在组件上声明 `<chart ref="chart" />` 。

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/44379897-b77e6400-a53a-11e8-8ca9-31ca6180134c.png)

打印一下 `this.$refs` 和 `this.$refs.chart` 看看

**Comment by BOB262** [comment]
解决问题，辛苦您。

**Comment by BOB262** [comment]
重现链接： https://jsfiddle.net/bob262/mczn5wa3/    tab切换时候图表为什么会重新渲染?

**Comment by xiguaxigua** [comment]
在初始状态下，图表的宽度是没有的（因为此时容器 display: none），所以需要在切换tab时触发 echarts 的刷新让图根据已经有宽度的容器进行渲染。如果不想重复渲染的话可以试试下面示例中的解决方案 https://jsfiddle.net/mczn5wa3/7/

**Comment by BOB262** [comment]
明白了，感谢你的帮助。
