### ISSUE TITLE
对图表设置别名后 legend 的 selected 属性无效

### ISSUE THREAD

**Issue by TothingWay** [ElemeFE/v-charts#487]
### Summary 简述
在 settings 属性中设置好别名后，再用 extend 设置 legend 的 selected 属性，无法生效，去掉 settings中的别名设置，selected 生效。

### Expect 期望结果

在设置别名的情况下，期望 selected 也能生效

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/44350608-6470c680-a4d2-11e8-8cff-9128258aa398.png)

如上图所示，通过 labelMap 设置别名会修改 legend 中对应的值，所以，设置 legend 的 selected 属性时需要对设置别名后的属性赋值 true or false .

**Comment by TothingWay** [comment]
好的，谢谢
