### ISSUE TITLE
v-charts如何重新渲染图表

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#49]
我的数据是用定时器每隔1秒添加进去，显示不成功，数据没有问题

**Comment by xiguaxigua** [comment]
写了一个小例子，看看能不能解决你的问题
https://jsfiddle.net/vue_echarts/jepw6dy2/76/

**Comment by 15521054523** [comment]
解决了，原来是我的数据没有在data里面定义导致，动态更新数据时，页面没有效果
