### ISSUE TITLE
v-charts在何处屏蔽enableMapClick

### ISSUE THREAD

**Issue by sumayi** [ElemeFE/v-charts#491]
### Summary 简述
想屏蔽百度地图enableMapClick，不知该写在何处

### Expect 期望结果
望回复！

### Reproduce 重现示例

```js
 this.chartSettings = {
        key: '1AFxxxxxxxxxxxxxxx',
        bmap: {
          center: [123.929055, 40.7671], 
          zoom: 16,
          roam: true, 
          silent: false,
          enableMapClick: false,//没有效果。。。
          mapStyle: {},
        }
      }
```

**Comment by xiguaxigua** [comment]
这个问题算是 echarts 的一个历史遗留问题了，目前来看没有太好的解决办法 https://github.com/apache/incubator-echarts/issues/4608 ， 有一个不是很好的解决方案可以尝试一下：
将 echarts 拉到本地，修改 echarts 中对应生成 bmap 配置的部分 https://github.com/apache/incubator-echarts/pull/8806 ， 然后 build 一下发到你的 github 下 https://github.com/apache/incubator-echarts/issues/6902#issuecomment-389015670 ，安装 echarts 的时候指定 echarts 的源为你的 github 账号下的版本 `npm install github:yourname/echarts`。
