### ISSUE TITLE
双y轴折线，但x轴刻度不一样

### ISSUE THREAD

**Issue by yqyily** [ElemeFE/v-charts#492]
### Summary 简述

您好，我想要实现双y轴曲线，但是两条线的x轴刻度不一样，比如第一条线只有在x轴是2,4,6,8，9,10下有数值，而第二条线只有在1,2,5,7,9下有数值，这样的两条曲线可以用双y轴表示吗？在线着急等

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/Lr7ezknh/1/ 是这种效果吗？

**Comment by yqyily** [comment]
是的，太感谢了，还有虚线的设置在哪里呢？比如一条线只有在x轴是1和5的时候有数据，这时需要对应x轴为1-5时，显示成虚线

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/Lr7ezknh/5/ echarts 只支持设置整条线的样式，无法针对某一段设置线条样式。

**Comment by yqyily** [comment]
恩恩，感谢
