### ISSUE TITLE
使用图表   右边缺失  显示不全

### ISSUE THREAD

**Issue by sunshuaisky** [ElemeFE/v-charts#496]
### Summary 简述

使用图表   右边缺失  显示不全
![1535178435617](https://user-images.githubusercontent.com/20508982/44615687-0b5ab700-a873-11e8-8889-bf1154b21ad4.jpg)
![1535178442645](https://user-images.githubusercontent.com/20508982/44615688-0d247a80-a873-11e8-836c-509443dc5ffb.jpg)

### Expect 期望结果

希望能够显示全

**Comment by xiguaxigua** [comment]
可以通过设置右边距来显示完整的字符 https://jsfiddle.net/89r5mh7c/

**Comment by sunshuaisky** [comment]
@xiguaxigua    多谢  已解决
