### ISSUE TITLE
如何获取到dataView里面的最新数据呢？

### ISSUE THREAD

**Issue by djkloop** [ElemeFE/v-charts#498]
### Summary 简述
在dataview里面修改数据
如何更新到视图上呢？

### Expect 期望结果
希望能获取到正确的数据

### Reproduce 重现示例

https://jsfiddle.net/3yx6fhm5/26/

**Comment by xiguaxigua** [comment]
echarts 的这个函数似乎设计的有问题 https://github.com/apache/incubator-echarts/blob/dev/src/component/toolbox/feature/DataView.js#L376 ，可以自己实现一个浮层，将数据更新的逻辑实现一遍就可以了。

**Comment by djkloop** [comment]
@xiguaxigua 您的意思是指 自己实现一个toolbox然后自己做个弹窗，在里面修改完数据，在重新修改echarts里面的chartData就行了么？

**Comment by djkloop** [comment]
已经用自定义toolbox解决。
