### ISSUE TITLE
请教一个小问题

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#50]
![image](https://user-images.githubusercontent.com/19297519/30581963-950a8ff0-9d54-11e7-8417-d6f2734b6d0a.png)
这里的legend可以改变字体颜色吗？或者是中间那个白色小圆球可以改成透明色吗？

**Comment by xiguaxigua** [comment]
可以修改字体颜色 https://jsfiddle.net/vue_echarts/jepw6dy2/77/，

白色的小球似乎不能改成透明色

**Comment by 15521054523** [comment]
大神看了你代码，才知道原来还有这种操作。。。
这个线条的起点，可以设置在画布的左下角开始吗

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/jepw6dy2/79/

可以尽量让起点靠坐下，在数据支持的情况下（起点为数据内值最小的一个）

**Comment by 15521054523** [comment]
可以了，我这里设置了一个最大的数值30，目的是为了实现，动态加载数据时，可以一点一点的增长，有没有办法让这个30到画布的顶部？图中的30才到画布的一半
![image](https://user-images.githubusercontent.com/19297519/30584036-23ee2d7a-9d5b-11e7-8fed-fe334c82d47a.png)

**Comment by xiguaxigua** [comment]
设置一下grid.top 应该就可以了
https://jsfiddle.net/vue_echarts/jepw6dy2/80/

**Comment by 15521054523** [comment]
可以了，主要是我不知道控制这个东西的是用 grid.top，我自己看文档有时候也是一脸懵，感谢大神的帮助
