### ISSUE TITLE
折线图或柱状图，X轴值相同的问题

### ISSUE THREAD

**Issue by MaJiaXuan** [ElemeFE/v-charts#500]
### Summary 简述
如果设置X轴显示的值是相同的，但是v-charts是把相同的值渲染在同一X轴上，理想效果应该是要分开显示的

### Expect 期望结果
X轴即使值相同，也要分开X轴显示，不能渲染在一起

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/24503453/44759429-b1a50600-ab6c-11e8-8999-22dbe9a68d58.png)

**Comment by xiguaxigua** [comment]
这个需求似乎无法实现，echarts 会将同样的维度值会被归到一起。

**Comment by MaJiaXuan** [comment]
@xiguaxigua 那换一种方式，X轴的排序方式以一个随机数来代替，保证不会重复，然后显示的值，用别名代替，这种可行？

**Comment by Hnnphone** [comment]
tooltip 怎么搞

**Comment by jayconscious** [comment]
@xiguaxigua 你可真棒👍
