### ISSUE TITLE
雷达图指标名称不支持颜色回掉函数

### ISSUE THREAD

**Issue by JianyeCao** [ElemeFE/v-charts#504]
### Summary 简述
如图所示，该指标的名字样式能不能单独设置，支持不不支持回掉函数
![image](https://user-images.githubusercontent.com/18524637/44782305-5cdbac80-abb9-11e8-8349-3fb109306f87.png)

**Comment by xiguaxigua** [comment]
是这种样式吗？ https://jsfiddle.net/6huo7wja/4/

**Comment by JianyeCao** [comment]
是的，谢谢，之前忽略了用extends属性。
