### ISSUE TITLE
引用环图发现却是饼状图

### ISSUE THREAD

**Issue by HongqingCao** [ElemeFE/v-charts#505]
1、<ve-ring :data="chartData"></ve-ring>
本来期望是环图的，引用后是发现是饼状图

2、建议属性配置示例写丰富一些

**Comment by xiguaxigua** [comment]
提供一下出现问题的示例代码吧

**Comment by jackson567** [comment]
原因是   
 <ve-pie>  radius: 80,
<ve-ring> 的  radius: [10, 100],

<ve-ring>的radius 是数组,设置成number的话,会变成 <ve-pie>
