### ISSUE TITLE
These dependencies were not found

### ISSUE THREAD

**Issue by hezhongfeng** [ElemeFE/v-charts#506]
引入的时候`import VeLine from 'v-charts/lib/line.common';`，出错，删除依赖依然这样，项目是根据vue的webpack模板做的，刚才测试vue-cli的上面没问题，版本如下："echarts": "^3.8.5","v-charts": "^1.17.10",
![](http://ww1.sinaimg.cn/large/b2395f3dly1fuqtpbdbhqj20v605pq31.jpg)

**Comment by xiguaxigua** [comment]
执行一下 `npm i echarts -S` 试试

**Comment by hezhongfeng** [comment]
问题找到了，是在`webpack.base.conf`的别名冲突了，不好意思打扰了
