### ISSUE TITLE
有个横屏切换渲染的问题。

### ISSUE THREAD

**Issue by 15521054523** [ElemeFE/v-charts#51]
默认是这样
![image](https://user-images.githubusercontent.com/19297519/30644016-8b151610-9e43-11e7-8c1d-ed5c9ad55e8a.png)
横屏后
![image](https://user-images.githubusercontent.com/19297519/30644035-9f3a9b7e-9e43-11e7-961f-6295b39fd713.png)
然后这个时候再横屏回来
![image](https://user-images.githubusercontent.com/19297519/30644050-b040f8be-9e43-11e7-9489-8e3d4194a922.png)
就会出现绘制超出边界的问题

**Comment by xiguaxigua** [comment]
在手机上横竖屏切换？
代码方便抽象出一个示例吗？或者简单描述一下有页面结构
