### ISSUE TITLE
v-charts 中怎么实现重新绘制

### ISSUE THREAD

**Issue by vincentSea** [ElemeFE/v-charts#514]
### Summary 简述、
问题：怎么实现重新绘制
案例：echart中是 setOption(option, true) 的api实现重新绘制的
v-charts 中怎么实现重新绘制

### Expect 期望结果
希望提供重新绘制的功能

**Comment by vincentSea** [comment]
已解决

**Comment by LiuduZero** [comment]
@vincentSea 请问你是怎么解决的呢
