### ISSUE TITLE
设置yAxis的min、max属性显示双Y轴问题

### ISSUE THREAD

**Issue by cxmhcc** [ElemeFE/v-charts#515]
### Summary 简述
地址：https://v-charts.js.org/#/line
第四个示例，在extend配置中添加如下代码：

`
yAxis: {min:1, max: 5000}
`

### Expect 期望结果
期望：通过min、max限制y轴的显示范围
结果：出现了双y轴的情况， 不希望有双y轴的效果
使用原生echarts不会有这个问题

### Reproduce 重现示例

https://jsfiddle.net/xkLe9j5n/

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/xkLe9j5n/3/

**Comment by cxmhcc** [comment]
好的，多谢啦

**Comment by king-ying** [comment]
我设置显示Y轴坐标，但是显示了两条y轴，请问怎么解决呢
