### ISSUE TITLE
如何指定图例的颜色、线的颜色、拐点的颜色 三者的颜色一致

### ISSUE THREAD

**Issue by snailg** [ElemeFE/v-charts#517]
### Summary 简述
如何指定图例的颜色、线的颜色、拐点的颜色 三者的颜色一致？需要指定颜色将颜色固定，而不是使用color属性，因为系数个数不固定，所以color属性无法准确匹配。

### Expect 期望结果
图例的颜色、线的颜色、拐点的颜色 三者的颜色一致

**Comment by xiguaxigua** [comment]
![image](https://user-images.githubusercontent.com/9931685/45397082-f5b9ff80-b670-11e8-8f1f-7d6bfa71df18.png)

当前版本 图例的颜色、线的颜色、拐点的颜色 三者的颜色 应该也是一致的，请详细描述一下问题吧。

**Comment by snailg** [comment]
@xiguaxigua   我是说通过指定颜色，例如我就指定红黄蓝对应这三条线，该如何做呢？

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/8u346Ls9/1/ 是这种样式吗？

**Comment by snailg** [comment]
@xiguaxigua 是这样的。谢谢，没看到文档上还有那么一个属性。
