### ISSUE TITLE
您好,给图表设置legend的时候不起效

### ISSUE THREAD

**Issue by yifangts** [ElemeFE/v-charts#52]
this.chartSettings = {
    	legend:{
        selectedMode:'single',
      }
}
在echarts官网示例中能够设置图例的选择模式,可以设置成为单选,但是在我们v-charts中并不支持,我看了一下源码,只有metrics,legendName,legendMap三种才能够修改,
希望能够下版本更新之后加上哈,或者大神告诉我有能够实现的方式

**Comment by xiguaxigua** [comment]
目前可以通过afterConfig实现，写了一个小例子
https://jsfiddle.net/vue_echarts/jepw6dy2/85/

**Comment by yifangts** [comment]
感谢大神,之前我还引入'echarts/lib/component/legend'   然后在图表里面 :legend这种方式添加
现在有这种方式就好多了

**Comment by yifangts** [comment]
那设置title的时候是报错了,这个是不一样的方法设置的吗?还是要引入title的包?

**Comment by xiguaxigua** [comment]
应该是不需要的，试试下面的用法

```html
<template>
  <div>
    <ve-line :title="chartTitle" :data="chartData"></ve-line>
  </div>
</template>

<script>
import VeLine from '../../src/packages/line'

export default {
  data () {
    this.chartTitle = {
      text: '图表标题'
    }

    return {
      chartData: {
        columns: ['日期', '余额', '年龄'],
        rows: [
          { '日期': 1, '余额': 123, '年龄': 3 },
          { '日期': 2, '年龄': 6 },
          { '日期': 3, '余额': 123, '年龄': 9 },
          { '日期': 4, '余额': 123, '年龄': 12 },
          { '日期': 5, '余额': 323, '年龄': 15 },
          { '日期': 6, '余额': 123, '年龄': 20 }
        ]
      }
    }
  },

  components: { VeLine }
}
</script>

```

![image](https://user-images.githubusercontent.com/9931685/30732446-313d2520-9fa5-11e7-999b-6498c694d154.png)

**Comment by xiguaxigua** [comment]
如果还是加不上的话，可以把报错信息贴一下，或者试试加上`import 'echarts/lib/component/line'`

**Comment by yifangts** [comment]
需要加上import 'echarts/lib/component/title'
才能够显示标题呢

**Comment by yifangts** [comment]
不加上import 'echarts/lib/component/title'   这个没有报错

**Comment by xiguaxigua** [comment]
文档上没有写明，回头补充一下😀

**Comment by yifangts** [comment]
感谢大神,大神,数据数组长度零的时候,有没有做提示无数据的呢

**Comment by xiguaxigua** [comment]
目前是没有的，可以在v-charts外部自定义一个无数据的提示，下一版会处理掉这个问题。

**Comment by yifangts** [comment]
好的,已经在外部定义了哈,下一版本的计划在什么时候发布呢?
会增加更多的类型的图表吧

**Comment by xiguaxigua** [comment]
下一个版本预计十月份吧，更多的图表会在下半年逐步增加。

**Comment by yifangts** [comment]
好的,谢谢大神!

**Comment by lazywhite** [comment]
目前在使用v-charts: 1.17.10 
现在最好的实现selectedMode的方法是什么
