### ISSUE TITLE
柱状图有卡顿是什么情况....

### ISSUE THREAD

**Issue by djkloop** [ElemeFE/v-charts#520]
### Summary 简述
柱状图有卡顿

### Expect 期望结果
如何不卡顿

### Reproduce 重现示例

https://jsfiddle.net/aeyq6jwL/

**Comment by djkloop** [comment]
如果直接把头部写死在columns就不卡顿，如果动态改变columns就会出现卡顿的情况。

**Comment by xiguaxigua** [comment]
在获取数据时先修改columns然后再赋值给chartData即可。
https://jsfiddle.net/aeyq6jwL/3/

**Comment by djkloop** [comment]
@xiguaxigua  谢谢，我以为在before那个生命周期里面修改呢...
