### ISSUE TITLE
v-charts怎么给动态生成的饼状图配上相应的背景色呢？

### ISSUE THREAD

**Issue by cishengbuhuan** [ElemeFE/v-charts#524]
### Summary 简述
我现在想要给我的饼状图的每个区域一个自定义的颜色，我看了echart的文档，上面直接给rows里面添加一个itemStyle属性就行了，但是我在v-charts里面添加这个属性是无效的，颜色并没有设置上去
![image](https://user-images.githubusercontent.com/33612942/45373501-3a6a7a00-b622-11e8-9b6e-dcb7df3edc66.png)

### Expect 期望结果
![image](https://user-images.githubusercontent.com/33612942/45373777-d8f6db00-b622-11e8-96d7-1b8fc960d664.png)

**Comment by cishengbuhuan** [comment]
因为我这个饼状图的数量是随机生成的，所以直接给绑定:colors='colors'这样写死的方法是不可行的，需要动态配置，这个问题希望大佬能指点一下，谢谢

**Comment by xiguaxigua** [comment]
可以在数据中动态获取颜色然后配置到图上
https://jsfiddle.net/bgfua7r1/7/

**Comment by cishengbuhuan** [comment]
> 可以在数据中动态获取颜色然后配置到图上
> https://jsfiddle.net/bgfua7r1/7/

这个思路可以，我去尝试下，谢谢大佬指点
