### ISSUE TITLE
柱状图 + 折线图，如何将折线设置成面积图效果？

### ISSUE THREAD

**Issue by shauning** [ElemeFE/v-charts#528]
柱状图 + 折线图，如何将折线设置成面积图效果，以下设置无效：
https://codepen.io/shauning/pen/KxxWwZ

`this.chartSettings = {
      showLine: ["下单用户"],
      area: true
    };`

希望能实现堆叠面积图demo那种面积效果

**Comment by maxycode** [comment]
https://codepen.io/maxycode/pen/QVVqWz   你想要的是这种效果吗？

**Comment by shauning** [comment]
> https://codepen.io/maxycode/pen/QVVqWz 你想要的是这种效果吗？

明白了，非常感谢。
