### ISSUE TITLE
core文件里的beforeDestroy单词写错了

### ISSUE THREAD

**Issue by liCat** [ElemeFE/v-charts#53]
很看好这套组件，也用了一段时间。
希望团队有代码review做严格的检查把关。
其它的类似于width，height首次绑定未生效这种问题我就没提了，我只能给你们的组件加个ref，比如就叫chart，然后我this.$refs.chart.echart.resize({})这种在父组件里操控你们写的子组件的方式来做了。
希望你们后续有更多的完善。

**Comment by xiguaxigua** [comment]
修复了(1.8.4)

**Comment by xiguaxigua** [comment]
很感谢您的建议，后面也会有其他人参与到这个项目中来维护，刚开始开发的时候，为了能够更快的实现功能，可能没有太关注review，之后的代码都会有review过后才会被合；同时，也希望用户能够在使用过程中反馈问题，让这个开源项目走的更远。
