### ISSUE TITLE
折线图的API问题

### ISSUE THREAD

**Issue by cishengbuhuan** [ElemeFE/v-charts#532]
### Summary 简述
我现在有一个折线图，上面的很多东西需要自定义设置，比方说线的颜色，宽度，折点的宽度，横坐标纵坐标的单位，鼠标放上去显示的内容等等，这些API上面都没有提到要怎么去自定义设置，对于新手来说找起来太麻烦了，希望有大佬能指点下，感激不尽

### Expect 期望结果
期望可以自定义折线图的样式

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/33612942/45727330-d6355080-bbf5-11e8-9ee3-546bbe87992d.png)

**Comment by maxycode** [comment]
https://codepen.io/maxycode/pen/xamVWb  这是一些你提到的自定义配置，对于更多的个性化配置，还是要结合v-chart和echarts的文档来看
