### ISSUE TITLE
k线图y轴位置问题

### ISSUE THREAD

**Issue by ruziyi** [ElemeFE/v-charts#533]
能否设置y轴在右边，并且最后一个 蜡烛距离y轴有一定距离。
如下图

![image](https://user-images.githubusercontent.com/7804644/45858894-26e1b080-bd92-11e8-8a6c-076b81275bb3.png)

**Comment by maxycode** [comment]
https://codepen.io/maxycode/pen/mGgMaz  是这样么？

**Comment by ruziyi** [comment]
是的 ，谢谢
