### ISSUE TITLE
折线图splitArea设置成渐变色

### ISSUE THREAD

**Issue by MeetYouZi** [ElemeFE/v-charts#536]
### Summary 简述
v-charts折线图splitArea无法设置成渐变色

### Expect 期望结果
v-charts折线图splitArea设置成渐变色

**Comment by maxycode** [comment]
该版本中暂无法实现渐变功能（配置详见 http://www.echartsjs.com/option.html#yAxis.splitArea.areaStyle.color ），只能实现 https://codepen.io/maxycode/pen/oProGO   这样分割明显的坐标轴

**Comment by MeetYouZi** [comment]
没有什么办法能实现吗？

发自我的 iPhone

**Comment by MeetYouZi** [comment]
这种能实现吗？
发自我的 iPhone

**Comment by maxycode** [comment]
https://codepen.io/maxycode/pen/oProGO  看下是不是你要的效果？至于颜色的话可以自己配置。所有用到的渐变色的地方统一用 new echarts.graphic.LinearGradient(配置详情参照 http://www.voidcn.com/article/p-rlpklfob-bps.html)实现。
