### ISSUE TITLE
折线图可以设置彩虹背景色吗

### ISSUE THREAD

**Issue by MeetYouZi** [ElemeFE/v-charts#537]
### Summary 简述
折线图的grid区域是根据y轴每一个值的范围设定颜色背景。折线图在被背景颜色的上面。就是在以y坐标轴上有多种颜色

### Expect 期望结果
折线图的坐标轴内背景图可以是多色拼接的。可以根据y轴数值画出不同颜色的彩虹背景图

**Comment by maxycode** [comment]
不太清楚 expect中的描述。能给个大致的草图实例么

**Comment by maxycode** [comment]
https://codepen.io/maxycode/pen/pxzxNG  在设置splitarea的color的时候多加几个渐变色就可以了
