### ISSUE TITLE
添加数据后不展示

### ISSUE THREAD

**Issue by LoserForLoser** [ElemeFE/v-charts#541]
### Summary 简述

使用折线图模版后，在网页模拟器上可以正常展示，但真机连调时不展示

![ddfb6d6a-013e-439b-90ce-db630fd09f4c](https://user-images.githubusercontent.com/17430128/46255767-0a512100-c4d4-11e8-8750-f63ad349f5f8.png)
![wechatimg3](https://user-images.githubusercontent.com/17430128/46255779-294fb300-c4d4-11e8-818d-70bcea4309db.png)

### Expect 期望结果

手机端正常展示

**Comment by maxycode** [comment]
请把代码贴到codepen或者jsfiddle重现实例
