### ISSUE TITLE
地图，可以不管有无数据都显示地名吗

### ISSUE THREAD

**Issue by wangyanchen** [ElemeFE/v-charts#543]
### Summary 简述
现在需要每个地名都显示名称
现在图中潍坊跟青岛都不显示地名

### Expect 期望结果
不管有没有数据都显示地名

### Reproduce 重现示例

https://codepen.io/anon/pen/vVygGV?editors=1010

**Comment by maxy612** [comment]
参见issues #556 https://github.com/ElemeFE/v-charts/issues/556
