### ISSUE TITLE
Uncaught Error: series.type should be specified.

### ISSUE THREAD

**Issue by MeetYouZi** [ElemeFE/v-charts#549]
### Summary 简述
请求接口之后数据之后，再更新chartdata就报错，而且页面图表数据也不更新

### Expect 期望结果
不报错，且请求数据之后图表更新。

### Reproduce 重现示例

 // 今日用电情况
      this.$axios('/web/electric/dayConsumpTrend', {lineBodyId: lineId}, res => {
        this.dayConsumpTrend = res.data
        let columns = this.dayConsumpTrend.deviceIdList
        let rows = this.dayConsumpTrend.consumpTrendList
        // columns.push('时间', '限定值')

        this.eleDescData.columns = columns
        this.eleDescData.rows = rows

        // this.eleDescData = {
        //   columns: columns,
        //   rows: [
        //     { '时间': '2', '1#': 13, '2#': 13, '3#': 20, '限定值': 30 },
        //     { '时间': '4', '1#': 13, '2#': 3, '3#': 20, '限定值': 30 },
        //     { '时间': '6', '1#': 13, '2#': 13, '3#': 20, '限定值': 30 },
        //     { '时间': '8', '1#': 13, '2#': 13, '3#': 20, '限定值': 30 },
        //     { '时间': '10', '1#': 13, '2#': 13, '3#': 30, '限定值': 20 },
        //     { '时间': '12', '1#': 13, '2#': 13, '3#': 30, '限定值': 20 },
        //     { '时间': '14', '1#': 9, '2#': 13, '3#': 30, '限定值': 20 },
        //     { '时间': '16', '1#': 3, '2#': 13, '3#': 30, '限定值': 30 },
        //     { '时间': '18', '1#': 3, '2#': 13, '3#': 30, '限定值': 30 },
        //     { '时间': '20', '1#': 3, '2#': 13, '3#': 20, '限定值': 30 },
        //     { '时间': '22', '1#': 3, '2#': 9, '3#': 20, '限定值': 30 },
        //     { '时间': '24', '1#': 13, '2#': 13, '3#': 30, '限定值': 20 },
        //   ]
        // }
        console.log(this.eleDescData, 'columns')
      })

**Comment by maxy612** [comment]
我用settimeout模拟ajax请求改变columns和rows，能够正常变换数据且没有报错，可以参照一下：https://codepen.io/maxycode/pen/GYWeGX
