### ISSUE TITLE
请问是否支持 scatter、effectScatter、lines 和 pictorialBar 四类图表？

### ISSUE THREAD

**Issue by BruceFan-FS71** [ElemeFE/v-charts#55]
1. scatter
2. effectScatter
3. lines
4. pictorialBar

请问是否支付以上四类图表，如果不支持：
1. 是否有可用的临时解决方案？
2. 大概何时可以支持？

多谢！

**Comment by xiguaxigua** [comment]
目前是不支持 散点图 和 pictorialBar 的，预计在10月末可以支持，当然，可以说出你的需求或细节，这样才能让v-charts更好的支持你的项目。目前的话，没有太好的可以借助v-charts实现的临时方案，可以在项目中封装一个组件实现你的功能。

**Comment by BruceFan-FS71** [comment]
@xiguaxigua 非常感谢。

目前最急需的两个场景：
1. 需要使用 map 与 effectScatter 配合，做出类似 http://gallery.echartsjs.com/editor.html?c=effectScatter-map 这样的图表
2. 需要使用 pictorialBar，做出类似 http://gallery.echartsjs.com/editor.html?c=pictorialBar-velocity 这样的图表

**Comment by xiguaxigua** [comment]
写了两个小例子，看看能否满足需求：
https://jsfiddle.net/vue_echarts/1fwe4tt7/8/
https://jsfiddle.net/vue_echarts/1Le0wps5/35/

**Comment by BruceFan-FS71** [comment]
@xiguaxigua 完全可以满足我的需求，非常感谢。
