### ISSUE TITLE
父组件根据屏幕自适应，子组件v-chart如何更好地处理宽度自适应问题？

### ISSUE THREAD

**Issue by hefeng1208** [ElemeFE/v-charts#550]
### Summary 简述
![image](https://user-images.githubusercontent.com/24466340/46731069-519d9580-ccbc-11e8-958f-b700cf455266.png)

* 如果菜单加载慢于右侧内容，会出现echart重叠问题，我知道可以通过获取父组件的宽度来适配处理，但是会带来另一个问题，就是如果我一个页面有多个图标，我需要获取每一个父组件的宽度，再去watch,虽然可以实现，感觉不太优雅。请教一下，可否在v-charts这个子组件中通过某种方式实现

### Expect 期望结果
* **父组件宽度变化，v-charts自适应显示，而不会重叠**

**Comment by maxy612** [comment]
vcharts不会根据父组件宽度的变化而自动调整，暂时只能通过手动调用echarts的resize实现。

**Comment by hefeng1208** [comment]
如果手动调用echart的resize，是否意味着需要，获取每一个父元素的宽度，监听父元素（多个dom的）宽度的变化？

**Comment by hefeng1208** [comment]
已解决，希望在下一个版本中，加上这个，感觉还比较适用，需求量还挺大。thx

**Comment by maxy612** [comment]
好的，下个版本会考虑加入。
