### ISSUE TITLE
环图如何根据宽度自适应 变大或变小

### ISSUE THREAD

**Issue by hikitty2** [ElemeFE/v-charts#551]
### Summary 简述
遇到的问题是
无论怎么去改变宽高  环图显示的大小始终都是这么大
宽度小于200 就被截取了
![123](https://user-images.githubusercontent.com/21003096/46736047-929ca680-ccca-11e8-8946-e889d9818304.jpg)

### Expect 期望结果

希望能像 echarts那样根据宽度会改变大小 麻烦了

**Comment by maxy612** [comment]
vcharts本身不要设置宽度，默认它的width会继承父元素的width。接下来设置用百分比设置 radius，百分比相对于width和height的短边。详见 https://codepen.io/maxycode/pen/ePWmPy

**Comment by hikitty2** [comment]
> vcharts本身不要设置宽度，默认它的宽度会继承父元素的宽度。接下来设置用百分比设置半径，百分比相对于宽度和高度的短边。详见https://codepen.io/maxycode/pen/ePWmPy

谢谢，按照你的例子确实可以完成自适应。还有最后的一个问题 就是 高度改变后 图表如何还是处于居中的状态呢？

**Comment by maxy612** [comment]
vcharts环图是默认水平垂直居中（相对于ve-line,可以打开控制台看看dom）的。高度改变后 ve-pie的高度没有改变，所以在视觉上呈现不居中的情况，但是环图相对于ve-line还是居中的。这个需要根据实际情况进行调整。
