### ISSUE TITLE
v-charts在项目中使用webpack打包后，app.js过大问题

### ISSUE THREAD

**Issue by wsxe9988** [ElemeFE/v-charts#553]
### Summary 简述
v-charts在项目中使用webpack打包后，app.js过大

### Expect 期望结果
如何减小打包后的大小

**Comment by maxy612** [comment]
https://v-charts.js.org/#/start  请先尝试按需引入。如果是按需引入的，vcharts中只有用到的包会被打包进webpack中，此时需要检查自己的webpack配置，从webpack配置上进行相应的打包优化。
