### ISSUE TITLE
地图想去掉那个点和修改颜色图之间的距离

### ISSUE THREAD

**Issue by zhanwen** [ElemeFE/v-charts#554]
### Summary 简述

![image](https://user-images.githubusercontent.com/11382789/46875956-a7ff0580-ce6f-11e8-90ac-bad603e3527b.png)

### Expect 期望结果

去除点，将距离变小。

**Comment by maxy612** [comment]
请在codepen上提供一个在线示例。

**Comment by zhanwen** [comment]
好的，谢谢

**Comment by zhanwen** [comment]
我想改变文字的颜色，设置 textColor无效。
![image](https://user-images.githubusercontent.com/11382789/46902231-0d94d580-cef4-11e8-80b0-e028ad08cd62.png)

```
this.visualMap = [   
{   
   min: 0,   
   max: 200,  
   text:['High','Low'],  
   textColor:'red', //无效
   realtime: false,  
   calculable: true,  
   inRange: {   
   color: ['lightskyblue','yellow', 'orangered']  
  }   
}  
]
```  

[https://codepen.io/Hanwen/pen/YJxVKR
](https://codepen.io/Hanwen/pen/YJxVKR
)

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/ZqJVjQ   textColor配置有问题。应该是 textStyle: { color: ''}

**Comment by maxy612** [comment]
配置项详见 http://echarts.baidu.com/option.html#visualMap-piecewise.textStyle.color

**Comment by zhanwen** [comment]
谢谢，刚才翻文档，没注意到，笔芯
