### ISSUE TITLE
地图添加数据后不显示地名

### ISSUE THREAD

**Issue by fjmiaoxiao** [ElemeFE/v-charts#556]
### Summary 简述
地图添加数据后不显示地名

### Expect 期望结果
地图添加数据后显示地名，或可以选择是否显示地名

### Reproduce 重现示例

![0985f49f2180eaefab3ad5344bd95557](https://user-images.githubusercontent.com/10862042/46925640-7b114500-d05f-11e8-9c77-1a13ca75483b.png)

**Comment by maxy612** [comment]
这个和echart版本有关系。4.0.0及以上版本会存在这个问题，请将echarts的依赖安装为3.8.5版本

**Comment by maxy612** [comment]
详见 https://codepen.io/maxycode/pen/jeaaqB

**Comment by fjmiaoxiao** [comment]
更换版本之后还是有问题，所有的地名都不显示了。我们的使用场景是一个旧项目的改造，市级地图因为没有js文件，只有遗留的json数据，载入方式是这样的，this.chartSettings = {       
        position: 'shenzhen',
        mapOrigin:shenzhen,  
}，json数据好像也和自带的其他json数据不太一样，类似下面这样：
![3a0ded0b0d8c0d4f91cf9574c50d4973](https://user-images.githubusercontent.com/10862042/47126271-49e08100-d2ba-11e8-89ee-569ae9121e2d.png)
![174b24ce89070443a2d9449af99ba283](https://user-images.githubusercontent.com/10862042/47126273-4c42db00-d2ba-11e8-91be-88775312ff6d.png)
是否是因为这个原因造成的？

**Comment by maxy612** [comment]
方便的话把代码示例放在codepen中一份 然后把地址贴出来吧。

**Comment by maxy612** [comment]
尝试一下 echarts4.0.0到4.1.0之间的版本

**Comment by fjmiaoxiao** [comment]
4.1.0可解决，谢谢
