### ISSUE TITLE
柱状图间距和背景

### ISSUE THREAD

**Issue by tangmingming** [ElemeFE/v-charts#557]
### Summary 简述
1、请问柱状图每一行的数据是否可以设置间距  1月1日有5个指标 想让5个指标柱状图间距为0
2、柱状图每个周期是否能设置间距或背景标识  1月1日和1月2号的柱状图有明显的标识   不然只有鼠标放上去后才能判断边缘的数据属于哪个日期

**Comment by maxy612** [comment]
可以这样设置： https://codepen.io/maxycode/pen/aRVwVP

**Comment by tangmingming** [comment]
可以 感谢
