### ISSUE TITLE
某一行某个指标没有数据自动补0

### ISSUE THREAD

**Issue by tangmingming** [ElemeFE/v-charts#562]
### Summary 简述

{
	"data": {
		"columns": ["time", "count_1", "count_2"],
		"rows": [
			{"time": "1.1", "count_1": 19, "count_2": 23},
			{"time": "1.2", "count_1": 19}
			]
	}
}

对于这样的数据 1.2号没有count_2   所以图上就不会显示   请问对于没有的是否支持自动补0

**Comment by maxy612** [comment]
部分图支持。比如折线图，可以通过在settings里配置  nullAddZero: true 实现。详见 https://codepen.io/maxycode/pen/oapqGJ

**Comment by tangmingming** [comment]
OK  3Q
