### ISSUE TITLE
默认的canvas高度400如何去掉？

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/v-charts#563]
### Summary 简述
应用ve-ring组件，绘出的canvas图默认高是400

### Expect 期望结果

希望能够根据父组件高度自适应，或去掉这个默认高度

### Reproduce 重现示例
https://jsfiddle.net/api/post/library/pure/

![image](https://user-images.githubusercontent.com/8478315/47069926-b3ad4c00-d222-11e8-9a61-60905baeb17b.png)

**Comment by maxy612** [comment]
看height的部分 https://v-charts.js.org/#/props。例如： <ve-line height=""></ve-line> height也可以是变量

**Comment by feichangtutu** [comment]
add`height="100%"`
as 
```
         <ve-ring
                  class="dark-row"
                  ref="first"
                  :data="chartData2"
                  :legend-visible="false"
                  :settings="chartSettings"
                  :colors="colors2"
                  :extend="options"
                  height="100%"
                >
                </ve-ring>
```
solved. thanks so much! @maxy612
