### ISSUE TITLE
怎样实现y轴分隔线且为虚线？

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/v-charts#564]
### Summary 简述

希望实现y轴按照横轴数量均分的竖线

### Expect 期望结果

![image](https://user-images.githubusercontent.com/8478315/47080271-2675f180-d23a-11e8-97fb-adc4fa0a5ab1.png)

### Reproduce 重现示例
![image](https://user-images.githubusercontent.com/8478315/47080339-52917280-d23a-11e8-934f-400dc348f356.png)

**Comment by maxy612** [comment]
请将重现实例放在codepen或者其他线上平台上方便帮助调试

**Comment by feichangtutu** [comment]
duplicated
