### ISSUE TITLE
line Chart 中有办法分别设定不同lineStyle的type吗？

### ISSUE THREAD

**Issue by SparkGB** [ElemeFE/v-charts#567]
### Summary 简述
在line chart中想分别为不同线段的lineStyle设置不同type，是否可以做到？

### Expect 期望结果
在同一个line chart 中，不同线段有不同的type，如一条dashed，一条solid

### Reproduce 重现示例
https://jsfiddle.net/gs5f01ok/

![2018-10-19 10 48 35](https://user-images.githubusercontent.com/17466359/47196469-3fde8100-d393-11e8-89dd-ff077e170da1.png)

**Comment by maxy612** [comment]
暂时不支持这么设置。这个在echarts中也没有对应的配置。

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/gs5f01ok/1/

**Comment by SparkGB** [comment]
> https://jsfiddle.net/gs5f01ok/1/

@xiguaxigua 没想到可以这样用！十万分感谢！

**Comment by JonesHuang1992126** [comment]
没用啊  i.lineStyle.type = 'dashed'打印啥undif
