### ISSUE TITLE
柱状堆叠图的X轴数据使用字符串无法渲染图形

### ISSUE THREAD

**Issue by topoadmin** [ElemeFE/v-charts#569]
### Summary 简述
柱状堆叠图的X轴数据不能使用字符串？
虽然有曲线救国的方法，但是不太理想啊

### Expect 期望结果
柱状堆叠图的X轴数据使用字符串

### Reproduce 重现示例
https://codepen.io/topoadmin/pen/OBwZYL?editors=1010

**Comment by maxy612** [comment]
https://v-charts.js.org/#/histogram  文档示例中 堆叠柱状图示例 的x轴数据不就是 string的吗？你说的x轴数据使用字符串是指什么呢？而且你给的示例中 xAxisType设为value，这是设置x轴数据为number类型的，与你要求的string类型的刚好相反。
