### ISSUE TITLE
数据显示不对

### ISSUE THREAD

**Issue by CodeDome** [ElemeFE/v-charts#570]
当绘制一个曲线图时，发现曲线的起点与x轴的点不对齐（x轴对应的点有数据）。 鼠标移到上边有部分显示数据不对

**Comment by maxy612** [comment]
请提供在线demo示例 (codepen或jsfiddle）

**Comment by CodeDome** [comment]
@maxy612  谢谢，已经解决了，问题在于数据的格式不对
