### ISSUE TITLE
x轴不支持数字类型, 折线图数据只能展示一半

### ISSUE THREAD

**Issue by coolucifer** [ElemeFE/v-charts#572]
### Summary 简述
折线图中的数据只展现一半, 后半部分只有x轴的值没有对应的y轴值, 并且数据有重叠部分
x轴不支持数字类型的数据, 修改为字符串之后就正常了

### Expect 期望结果
正常展示全部数据

### Reproduce 重现示例

[jsFiddle](https://jsfiddle.net/coolucifer/9x7Lw2ct/2/)
![image](https://user-images.githubusercontent.com/23123540/47339597-49872200-d6ce-11e8-9f45-320e4046dd6c.png)

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/JmazPz  这样设置试试看

**Comment by coolucifer** [comment]
> https://codepen.io/maxycode/pen/JmazPz 这样设置试试看

可以了 谢谢
