### ISSUE TITLE
ve-line添加theme后，曲线图变成了折线图

### ISSUE THREAD

**Issue by feichangtutu** [ElemeFE/v-charts#575]
### Summary 简述

q1:ve-line添加theme后，曲线图变成了折线图
q2:添加yAxis 无效，希望添加竖向分隔线
### Expect 期望结果

![image](https://user-images.githubusercontent.com/8478315/47404962-fcfd1e80-d781-11e8-8957-b7c886c56e6f.png)
希望仍旧为曲线图，并可以设置横向纵向分隔线
### Reproduce 重现示例
https://jsfiddle.net/Yanni_Jia/h0k9gmpy/

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/GYYBEZ   q2回头我再看看。q1设置下extend中series下的smooth就行了

**Comment by feichangtutu** [comment]
solve Q2:
add theme
```
  chartTheme: {
        valueAxis:{
          axisLabel: {
            color: '#ffffff'
          },
          splitLine: {
            lineStyle: {
              // 使用深浅的间隔色
              color: ['#fff'],
              type: 'dashed'
            }
          }
        },
        categoryAxis:{
          axisLabel: {
            color: '#ffffff'
          },
          splitLine: {
          	show: true,
            lineStyle: {
              // 使用深浅的间隔色
              color: ['#fff'],
              type: 'dashed'
            }
          }
        }
      },
```
原因在于 x轴称为： categoryAxis， y轴为valueAxis,然后根据echarts对应的xAxis以及yAxis作配置项修改
result in fiddle:

https://jsfiddle.net/Yanni_Jia/h0k9gmpy/

**Comment by feichangtutu** [comment]
@maxy612 thank u so much. Happy 1024!
