### ISSUE TITLE
ve-map怎样设置scatter点？

### ISSUE THREAD

**Issue by jeff-fe** [ElemeFE/v-charts#578]
### Summary 简述

Expect 期望结果

希望在地图中增加，散点效果，如果下实例
http://www.echartsjs.com/gallery/editor.html?c=scatter-map

Reproduce 重现示例

**Comment by jeffhuang2086** [comment]
> ve-map在echarts中系列下的类型是map，而scatter是系列的另一个类型。不能直接在ve-map上使用scatter点。如果在ve-map下使用，可以试试设置markPoint

感谢您的回答，markPoint是不能用经纬度标记点吧吗，我后来尝试在after-config函数中去重新写入options，也能实现，如上效果！

`
<template>
      <ve-map  :after-config="afterConfig" />
</template>

<script>
export default {
  data () {
    return {
      config: {
        geo: {
          map: 'china',
          label: {
            emphasis: {
              show: false,
            },
          },
          itemStyle: {
            normal: {
              borderColor: '#006bfa',
              areaColor: '#100072',
            },
            emphasis: {
              areaColor: '#006bfa',
            },
          },
        },
        series: [{
          name: '门店',
          type: 'effectScatter',
          coordinateSystem: 'geo',
          data: [
            {'name': '海门', 'value': [121.15, 31.89, 9]},
            {'name': '大庆', 'value': [125.03, 46.58, 279]},
          ],
          symbolSize: 10,
          showEffectOn: 'render',
          rippleEffect: {
            brushType: 'stroke',
          },
          label: {
            normal: {
              show: false,
            },
            emphasis: {
              show: false,
            },
          },
          itemStyle: {
            normal: {
              color: '#F4E925',
              shadowBlur: 4,
              shadowColor: '#05C3F9',
            },
          },
        }],
      },
    }
  },
  methods: {
    afterConfig (options) {
      options = {...this.config}
      return options
    },
  },
}
</script>

`

**Comment by LiuduZero** [comment]
> > ve-map在echarts中系列下的类型是map，而scatter是系列的另一个类型。不能直接在ve-map上使用scatter点。如果在ve-map下使用，可以试试设置markPoint
> 
> 感谢您的回答，markPoint是不能用经纬度标记点吧，我后来尝试在after-config函数中去重新写入options，也能实现，如下效果！
> 
> ```
> <template>
>   <ve-map :after-config="afterConfig"/>
> </template>
> <script>
> export default {
>   data () {
>     return {
>       config: {
>         geo: {
>           map: 'china',
>           label: {
>             emphasis: {
>               show: false,
>             },
>           },
>           itemStyle: {
>             normal: {
>               borderColor: '#006bfa',
>               areaColor: '#100072',
>             },
>             emphasis: {
>               areaColor: '#006bfa',
>             },
>           },
>         },
>         series: [{
>           name: '门店',
>           type: 'effectScatter',
>           coordinateSystem: 'geo',
>           data: [
>             {'name': '海门', 'value': [121.15, 31.89, 9]},
>             {'name': '大庆', 'value': [125.03, 46.58, 279]},
>           ],
>           symbolSize: 10,
>           showEffectOn: 'render',
>           rippleEffect: {
>             brushType: 'stroke',
>           },
>           label: {
>             normal: {
>               show: false,
>             },
>             emphasis: {
>               show: false,
>             },
>           },
>           itemStyle: {
>             normal: {
>               color: '#F4E925',
>               shadowBlur: 4,
>               shadowColor: '#05C3F9',
>             },
>           },
>         }],
>       },
>     }
>   },
>   methods: {
>     afterConfig (options) {
>       options = {...this.config}
>       return options
>     },
>   },
> }
> </script>
> ```

如果要在省份地图里面去实现显示 scatter 呢

**Comment by LiuduZero** [comment]
楼上的大佬， 如果要在省份地图里面去实现显示 scatter 呢，

**Comment by jeffhuang2086** [comment]
@LiuduZero   刚刚尝试了一下没能实现，地图切换省份需要 echarts.registerMap()，而且现在最新的4.0文档也不再提供地图适量文件了，如果有负责的交互还是建议使用百度地图，ve-bmap

**Comment by LiuduZero** [comment]
@jeffhuang2086 按照你的方法，从后台获取数据的数据，在页面上散点偶尔显示不出来，有时候可以出现有时候出不来

**Comment by jeffhuang2086** [comment]
@LiuduZero   你再ve-map加个v-if处理，每次数据刷新，组件也重新渲染试一试
