### ISSUE TITLE
v-charts 有关系图吗?

### ISSUE THREAD

**Issue by XiaoLuo01** [ElemeFE/v-charts#596]
### Summary 简述
v-charts 有关系图吗?  就是echarts 里面的 graph 图表, 展示节点变化的

### Reproduce 重现示例
链接在这里: http://www.echartsjs.com/gallery/editor.html?c=graph

**Comment by maxy612** [comment]
暂时没有对这个图的封装

**Comment by XiaoLuo01** [comment]
好的, 还是谢谢了
