### ISSUE TITLE
dataZoom怎样用

### ISSUE THREAD

**Issue by guojingwen** [ElemeFE/v-charts#6]
我加了
:dataZoom="chartDataZoom"

this.chartDataZoom = [{
        type: 'inside',
        start: 86,
        end: 100
      }, {
        start: 0,
        end: 7,
        handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
        handleSize: '70%',
        handleStyle: {
          color: '#fff',
          shadowBlur: 3,
          shadowColor: 'rgba(0, 0, 0, 0.6)',
          shadowOffsetX: 2,
          shadowOffsetY: 2
        }
      }]

不起作用

**Comment by xiguaxigua** [comment]
可能是因为你没有引入`dataZoom`模块:
`import 'echarts/lib/component/dataZoom'`
( 这里之前文档上没有写清楚，现在补全了

**Comment by guojingwen** [comment]
dataZoom可以用了
但是
this.$refs.chart.$el.dispatchAction({
        type: 'dataZoom',
        start: start - 1,
        end: 100
      })
会报错
或者说怎么用的

**Comment by guojingwen** [comment]
单纯用echarts我能hot住 各种需求 ,  用你们这个应该更方便一些，但是感觉hot不住
下面是单纯用echarts的需求

<style type='text/scss' lang="scss">
  .page-test {
    #echart-test, #echart-test2, #echart-test3 {
      width: 375px;
      height: 300px;
    }
  }
</style>

<template>
  <div class="page-test">
    <h2>测试echarts</h2>
    <br>
    <div class="am-tab" role="tablist">
      <a class="am-tab-item" role="tab" v-for="(text, index) in chart1" :class="{selected: index1 === index}" @click="getArea(index);">{{text}}</a>
    </div>
    <div id="echart-test" ></div>
    <hr>
    <div class="am-tab" role="tablist">
      <a class="am-tab-item" role="tab" v-for="(text, index) in chart2" :class="{selected: index2 === index}" @click="getArea2(index);">{{text}}</a>
    </div>
    <div id="echart-test2" ></div>
    <hr>
    <div id="echart-test3" ></div>
  </div>
</template>

<script>
import echarts from 'echarts';
/* import 'echarts/lib/chart/bar';
import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/title'; */
let myChart, myChart2, myChart3;
let days1 = 50;
let days2 = 50;
export default {
  name: 'zfb-home',
  
  data () {
    return {
      index1: 0,
      index2: 0,
      chart1: [
        '最近7天',
        '最近30天',
        '所有'
      ],
      chart2: [
        '最近7天',
        '最近30天',
        '所有'
      ]
    };
  },
  
  created () {
    this.mode = this.$route.query.mode || this.mode;
  },
  methods: {
    getArea (index) {
      this.index1 = index;
      let start;
      if (index === 0) { // 七天
        start = 86;
      } else if (index === 1) { // 30天
        start = 40;
      } else {
        start = 0;
      }
      myChart.dispatchAction({
        type: 'dataZoom',
        start: start - 1,
        end: 100
      });
    },
    getArea2 (index) {
      this.index2 = index;
      let start;
      if (index === 0) { // 七天
        start = 86;
      } else if (index === 1) { // 30天
        start = 40;
      } else {
        start = 0;
      }
      myChart2.dispatchAction({
        type: 'dataZoom',
        start: start - 1,
        end: 100
      });
    }
  },
  mounted () {
    myChart = echarts.init(document.getElementById('echart-test'));
  
    let base = +new Date(2017, 5, 0);
    let oneDay = 24 * 3600 * 1000;
    let date = [];
    let data = [Math.random() * 9000];
    for (let i = 1; i < days1; i++) {
      let now = new Date(base += oneDay);
      date.push([now.getMonth() + 1, now.getDate()].join('-'));
      data.push(Math.round((Math.random() - 0.4) * 500 + data[i - 1]));
    }
    myChart.setOption({
      title: {
        left: 'center',
        text: '生活号点击数'
      },
      tooltip: {
        trigger: 'axis'
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: date
      },
      yAxis: {
        position: 'right',
        type: 'value',
        boundaryGap: [0, '100%']
      },
      dataZoom: [{
        type: 'inside',
        start: 86,
        end: 100
      }, {
        start: 0,
        end: 7,
        handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
        handleSize: '70%',
        handleStyle: {
          color: '#fff',
          shadowBlur: 3,
          shadowColor: 'rgba(0, 0, 0, 0.6)',
          shadowOffsetX: 2,
          shadowOffsetY: 2
        }
      }],
      series: [
        {
          name: '点击数',
          type: 'line',
          smooth: false,
          symbol: 'circle',
          sampling: 'average',
          itemStyle: {
            normal: {
              color: 'rgb(17, 129, 227)'
            }
          },
          areaStyle: {
            normal: {
              color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                offset: 0,
                color: 'rgb(221, 240, 249)'
              }, {
                offset: 1,
                color: 'rgb(255, 255, 255)'
              }])
            }
          },
          data: data
        }
      ]
    });
    
    // 图表二
    let base2 = +new Date(2017, 5, 0);
    let oneDay2 = 24 * 3600 * 1000;
    let now = new Date(base2 += oneDay2);
    
    let database2 = [{name: '个税查询', data: [Math.random() * 9000]}, {name: '用户注册', data: [Math.random() * 9000]}],
      times = [[now.getMonth() + 1, now.getDate()].join('-')],
      legendNams = [];
    
    for (let item of database2) {
      legendNams.push(item.name);
    }
    for (let i = 1; i < days2; i++) {
      now = new Date(base2 += oneDay2);
      times.push([now.getMonth() + 1, now.getDate()].join('-'));
      for (let item of database2) {
        item.data.push(Math.round((Math.random() - 0.4) * 500 + item.data[i - 1]));
      }
    }
    
    myChart2 = echarts.init(document.getElementById('echart-test2'));
    myChart2.setOption({
      title: {
        text: '生活号'
      },
      tooltip: {
        trigger: 'axis'
      },
      legend: {
        data: legendNams
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: times
      },
      yAxis: {
        position: 'right',
        type: 'value',
        boundaryGap: [0, '100%']
      },
      dataZoom: [{
        type: 'inside',
        start: 86,
        end: 100
      }, {
        start: 0,
        end: 7,
        handleIcon: 'M10.7,11.9v-1.3H9.3v1.3c-4.9,0.3-8.8,4.4-8.8,9.4c0,5,3.9,9.1,8.8,9.4v1.3h1.3v-1.3c4.9-0.3,8.8-4.4,8.8-9.4C19.5,16.3,15.6,12.2,10.7,11.9z M13.3,24.4H6.7V23h6.6V24.4z M13.3,19.6H6.7v-1.4h6.6V19.6z',
        handleSize: '70%',
        handleStyle: {
          color: '#fff',
          shadowBlur: 3,
          shadowColor: 'rgba(0, 0, 0, 0.6)',
          shadowOffsetX: 2,
          shadowOffsetY: 2
        }
      }],
      series: [
        {
          name: database2[0].name,
          type: 'line',
          stack: '总量',
          areaStyle: {normal: {}},
          data: database2[0].data
        },
        {
          name: database2[1].name,
          type: 'line',
          smooth: false,
          symbol: 'circle',
          sampling: 'average',
          areaStyle: {normal: {}},
          data: database2[1].data
        }
      ]
    });
  
    // 基于准备好的dom，初始化echarts实例
    myChart3 = echarts.init(document.getElementById('echart-test3'));
    myChart3.setOption({
      title: { text: 'ECharts 入门示例' },
      tooltip: {},
      xAxis: {
        data: ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']
      },
      yAxis: {},
      series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
      }]
    });
  }
};
</script>

**Comment by xiguaxigua** [comment]
首先回答你的第一个问题，之所以会报错，是由于 `dispatchAction` 这个函数并不是绑定在 DOM 节点上，而是在 `echarts` 对象上，所以可以写成下面的方式：
```js
this.$refs.chart.echarts.dispatchAction({
  type: 'dataZoom',
  start: 40 - 1,
  end: 100
})
```

**Comment by xiguaxigua** [comment]
其次，我看了一下你的 options 中的内容，看上去是有一些现在 V-Charts 中没有提供的属性，这些可以通过在 after-config 拿到生成的 options 单独配置。之所以没有提供所有的可配置项暴露到 settings 内，原因有二：为了使图表的代码体积更小，目前只封装了一部分‘常用’的功能，其他的配置都可以在after-config中实现；在开发 V-Charts 的过程中，遇到的需求并没有涉及到每一方面，所以有些东西可能没有考虑到，当然，这其实是主要原因，也是目前正在主要处理的，解决这个问题最好的方式可能还是通过使用和反馈吧实践出真知嘛。最后，感谢你提供的这个例子，我会想办法优化一下针对你的这个例子中可以增加的配置。
@guojingwen

**Comment by guojingwen** [comment]
我试了下可以的。
哥们，你真牛，问题解决非常迅速，
我在研究研究貌似能hot住了

万分感谢！

**Comment by xiguaxigua** [comment]
不客气😄
