### ISSUE TITLE
请教一个问题，请问自定义主题应该怎么设置？

### ISSUE THREAD

**Issue by Jvaeyhcd** [ElemeFE/v-charts#60]
请教一个问题，请问自定义主题应该怎么设置？我设置了theme-name="dark"但是没有效果

**Comment by xiguaxigua** [comment]
设置主题有两种办法，一种是使用theme直接传主题的内容设置对象，例如
```js
:theme="theme"

this.theme = {
  categoryAxis: {
    axisLine: { show: false },
    axisTick: { show: false },
    splitLine: { show: false }
  },
  valueAxis: {
    axisLine: { show: false }
  }
}
```

第二种就是现在你使用的，通过设置theme-name, 在这之前需要先注册你所使用的主题，例如dark
```js
import echarts from 'echarts/lib/echarts'

echarts.registerTheme('dark', {
  categoryAxis: {
    axisLine: { show: false },
    axisTick: { show: false },
    splitLine: { show: false }
  },
  valueAxis: {
    axisLine: { show: false }
  },
  line: {
    smooth: true
  },
  grid: {
    containLabel: true,
    left: 10,
    right: 10
  }
})
```

**Comment by topoadmin** [comment]
第二种方法暂未测通
```javascript
import echarts from 'echarts'
import { walden } from './echarts-theme/walden'
echarts.registerTheme('walden', walden) // 该主题在使用 echarts.init 渲染时是可用的
import VCharts from 'v-charts'
Vue.use(VCharts)
```
```html
<ve-chart :data="item.data" theme-name="walden"></ve-chart>
```

**Comment by xiguaxigua** [comment]
@topoadmin https://codesandbox.io/s/3vqyx8mzzp 参考示例

**Comment by acodercat** [comment]
通过registerTheme注册的主题`color`不生效，但是通过组件的theme属性设置主题`color`是生效的

**Comment by chouchoui** [comment]
> @topoadmin https://codesandbox.io/s/3vqyx8mzzp 参考示例

这个参考示例里面没有看到theme-name的使用

**Comment by Smurfs-xxl** [comment]
> @topoadmin https://codesandbox.io/s/3vqyx8mzzp 参考示例

您的示例没有设置theme代码，麻烦更新一下。

**Comment by io-o** [comment]
```
:theme="theme"
```
> 在echarts官网下载主题包 导入
![image](https://user-images.githubusercontent.com/22197685/69300294-bbbd9380-0c4d-11ea-920c-de57d8392579.png)

**Comment by jackchoumine** [comment]
> @topoadmin https://codesandbox.io/s/3vqyx8mzzp 参考示例

并没有主题设置啊，麻烦大佬更新一个。

**Comment by jackchoumine** [comment]
> ```
> :theme="theme"
> ```
> 
> > 在echarts官网下载主题包 导入
> > ![image](https://user-images.githubusercontent.com/22197685/69300294-bbbd9380-0c4d-11ea-920c-de57d8392579.png)

完整的设置是怎样的呢？ 麻烦再多些代码
