### ISSUE TITLE
柱状图维度字段显示问题

### ISSUE THREAD

**Issue by amiezhang** [ElemeFE/v-charts#610]
### Summary 简述
维度横坐标，resize后出现一些奇怪的表现
在宽度缩小到一定宽度后，横坐标一些字段会隐藏
但是再resize拉开后，隐藏的字段没有重新出现

### Expect 期望结果
再resize拉开后，隐藏的字段重新出现

#### 例如：[柱状图demo的第一个例子](https://v-charts.js.org/#/histogram)

![image](https://user-images.githubusercontent.com/15716269/48474911-890cde00-e836-11e8-8ece-f9f700e4fbe5.png)
![image](https://user-images.githubusercontent.com/15716269/48474964-b063ab00-e836-11e8-9634-2547d4f1df2b.png)
![image](https://user-images.githubusercontent.com/15716269/48475041-e012b300-e836-11e8-928c-07e14cd2e1b5.png)

**Comment by maxy612** [comment]
http://echarts.baidu.com/examples/editor.html?c=bar-simple   v-charts是基于echarts的，echarts的官方示例中的表现就是这样的

**Comment by amiezhang** [comment]
> http://echarts.baidu.com/examples/editor.html?c=bar-simple v-charts是基于echarts的，echarts的官方示例中的表现就是这样的

好吧，那我去echarts那提issue
