### ISSUE TITLE
设置xAxis或者yAxis的axisLine无效

### ISSUE THREAD

**Issue by Myu1533** [ElemeFE/v-charts#612]
### Summary 简述
设置xAxis或者yAxis的axisLine无效，在extend里也进行了尝试。
想改变坐标轴的颜色和粗细，然而配置以后都没效果
翻了下源码，应该是没有处理

### Reproduce 重现示例

xAxis: {
        type: 'category',
        axisTick: {
          show: false
        },
        axisLabel: {
          show: false
        },
        **axisLine: {
          lineStyle: {
            color: '#0000ff'
          }
        }**
      }

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/xQdYrE?&editors=101   你说的效果是这样么？

**Comment by Myu1533** [comment]
> https://codepen.io/maxycode/pen/xQdYrE?&editors=101 你说的效果是这样么？

对的，xAxis.axisLine.show属性是要显示设置为true的啊，echarts文档默认true，就被我完全忽略了，谢谢
