### ISSUE TITLE
图标横轴最后一位数字未显示完全

### ISSUE THREAD

**Issue by GwYL** [ElemeFE/v-charts#63]
![qq 20171013104114](https://user-images.githubusercontent.com/25656592/31527971-2be00e26-b003-11e7-9a9d-9baaba81754e.png)

如图，最后一位数字就是显示不了。求解决方案

**Comment by xiguaxigua** [comment]
可以把横轴的坐标做一下倾斜，http://jsfiddle.net/vue_echarts/m1hdcmf4/14/

![image](https://user-images.githubusercontent.com/9931685/31529813-46d0d236-afa1-11e7-9a65-96c3cc6eebd3.png)
