### ISSUE TITLE
How to set the font size of the province in the map?

### ISSUE THREAD

**Issue by whirly77cai** [ElemeFE/v-charts#65]
I can not find out the config option in the document...
![5 fagns tjqpol1sp62 v](https://user-images.githubusercontent.com/18453908/31573290-778e9160-b0eb-11e7-80c1-18de801d6d14.png)

**Comment by xiguaxigua** [comment]
By now, you can set font-size by use `after-config` attribute, and there is a simple example https://jsfiddle.net/1fwe4tt7/10/

**Comment by whirly77cai** [comment]
( • ̀ω•́ )✧

**Comment by xiguaxigua** [comment]
😄
