### ISSUE TITLE
element-ui 的 tabs标签切换问题

### ISSUE THREAD

**Issue by dfc12315** [ElemeFE/v-charts#653]
### Summary 简述
在案例里面的 tabs 切换之后图表数据是可以展示出来，但是当多个图表的时候数据就展示不出来了，请问这个可以怎么设置一下，一个 tabs 页里面多个图表的问题

### Expect 期望结果
有解决办法也可以，最好有个例子，谢谢啦

**Comment by pantt** [comment]
同问。循环渲染了多个图表，为每一个图表绑定了settings，点击单个想改变chartSetting的类型，但是没作用
