### ISSUE TITLE
柱状图不支持文字旋转rotate,  不能忍啊

### ISSUE THREAD

**Issue by qiuguixin** [ElemeFE/v-charts#67]
柱状图不支持文字旋转rotate,  不能忍啊
https://elemefe.github.io/v-charts/#/histogram

![image](https://user-images.githubusercontent.com/16093668/31698335-a973597a-b3ef-11e7-91c5-03cca8e0fa2e.png)

**Comment by xiguaxigua** [comment]
写了一了小例子，看下是这个效果吗？ https://jsfiddle.net/vue_echarts/1Le0wps5/40/
