### ISSUE TITLE
怎么去掉环状图的上标

### ISSUE THREAD

**Issue by wty8023** [ElemeFE/v-charts#675]
### Summary 简述
环图的上边的那些提示怎么能不显示啊 文档里貌似是没有这个配置项

### Expect 期望结果
希望可以不显示tu'pian图片中红框的元素

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/27050415/50890702-a83e7b00-1435-11e9-99fc-2f4f37e54933.png)

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/gZjzJd?&editable=true&editors=101

**Comment by wty8023** [comment]
ok 多谢
