### ISSUE TITLE
如果我要设置y轴显示，结果设置yAxis属性，不起作用

### ISSUE THREAD

**Issue by libbGit** [ElemeFE/v-charts#679]
### Summary 简述
`<ve-line :data="chartData"
            width="500px"
            :yAxis="yAxis">
</ve-line>
`
`
yAxis:{
          show: true,
          position:'right',
} 
`
我使用yAxis覆盖，发现没有任何效果

### Expect 期望结果

折线图 左侧出现y轴

### Reproduce 重现示例

![image](https://user-images.githubusercontent.com/23432911/51156954-cd5d3e80-18b8-11e9-81a2-f358f5991621.png)

**Comment by libbGit** [comment]
chartData为下面:
`
chartData: {
        columns: ["日期", "销售额"],
        rows: [
          { 日期: "1月1日", 销售额: 123 },
          { 日期: "1月2日", 销售额: 1223 },
          { 日期: "1月3日", 销售额: 2123 },
          { 日期: "1月4日", 销售额: 4123 },
          { 日期: "1月5日", 销售额: 3123 },
          { 日期: "1月6日", 销售额: 7123 }
        ]
},
`

**Comment by maxy612** [comment]
https://codepen.io/maxycode/pen/GPzxxB?&editable=true&editors=101

**Comment by libbGit** [comment]
> https://codepen.io/maxycode/pen/GPzxxB?&editable=true&editors=101

谢谢，缺少了 axisLine:{show: true}
不过颜色好像和其他的不一致，有些深

**Comment by maxy612** [comment]
自己查一下ECHARTS的文档就知道了 https://echarts.baidu.com/option.html#yAxis.splitLine.lineStyle
