### ISSUE TITLE
文档中示例“柱状图 设置Y双坐标”的例子中出现坐标左右个数不一致，这个问题能解决吗？

### ISSUE THREAD

**Issue by spademan** [ElemeFE/v-charts#69]
文档中示例“柱状图 设置Y双坐标”的例子中出现坐标左右个数不一致，这个问题能解决吗？https://elemefe.github.io/v-charts/#/histogram?id=%e8%ae%be%e7%bd%ae%e5%8f%8cy%e8%bd%b4

**Comment by spademan** [comment]
https://elemefe.github.io/v-charts/#/histogram?id=%e8%ae%be%e7%bd%ae%e5%8f%8cy%e8%bd%b4

**Comment by xiguaxigua** [comment]
没大看懂，可以说的更详细一些吗？

**Comment by spademan** [comment]
如例子所示，左右y轴的数值能不能都分别在一条线上，比如1.00k和10%能不能在同一条线上

**Comment by xiguaxigua** [comment]
按照 echarts 的文档所讲，http://echarts.baidu.com/option.html#yAxis.splitNumber 目前应该是没有办法实现这样的需求的

**Comment by xiguaxigua** [comment]
https://jsfiddle.net/vue_echarts/1Le0wps5/42/  写了一个小例子，可以参考一下。
核心的原理就是通过设置值域及间隔，强行设置分割线。
