### ISSUE TITLE
v-chart 折线图怎么在指标右边加上"全部"按钮

### ISSUE THREAD

**Issue by ccforever0304** [ElemeFE/v-charts#701]
### Summary 简述
在指标边加上"全部"按钮,点击时,切换所有折线的显示状态

### Expect 期望结果

点击时,切换所有折线的显示状态

**Comment by ccforever0304** [comment]
https://jsfiddle.net/pwtb85yj/11/

**Comment by lmk123** [comment]
看来你自己已经做到了 👍
