### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dtboy1995** [ElemeFE/v-charts#71]
照着您的文档引入并测试出现Uncaught (in promise) TypeError: Cannot convert undefined or null to object，是我的vue版本还是什么的问题？vue版本2.0.1 我看了下您用的是webpack2.x，我是1.18和这个有关系吗，谢谢。。。

**Comment by xiguaxigua** [comment]
贴一点代码看看吧

**Comment by xiguaxigua** [comment]
如果方便的话，可以提供一些关于引入方式，如何使用的，还有报错的位置之类的信息，或者如何重现这个问题
