### ISSUE TITLE
请问如何限定柱状图刻度为整数？

### ISSUE THREAD

**Issue by my-yy** [ElemeFE/v-charts#711]
### Summary 简述
请问如何限定柱状图刻度为整数？
![屏幕快照 2019-03-24 下午3 10 49](https://user-images.githubusercontent.com/10362876/54876227-5bb8e800-4e47-11e9-9fc6-4c692d4ee85f.png)
### Expect 期望结果
![屏幕快照 2019-03-24 下午3 12 33](https://user-images.githubusercontent.com/10362876/54876230-64112300-4e47-11e9-8902-2a8904731487.png)

### Reproduce 重现示例
https://jsfiddle.net/ygqxu167/

**Comment by my-yy** [comment]
或者如何将中间的线条去掉？

**Comment by lmk123** [comment]
https://codepen.io/lmk123/pen/oVVXxP

这其实是一个 echarts 本身的配置问题，下次请先查阅 echarts 文档。
