### ISSUE TITLE
[需求]能否支持 y 轴反转

### ISSUE THREAD

**Issue by atjason** [ElemeFE/v-charts#724]
你好，
这不是一个 Bug，还是一个需求：y 轴反转。

比如，y 轴的数值范围是 [0, 100]，正常情况，y 轴下方是 0、上方是 100。有的时侯，希望反转，即下方是 100、上方是 0。

使用场景：比如显示排名变化，自然是数值越小越好，而越好的排名，显示在上面更自然些。

**Comment by atjason** [comment]
可以通过设置 `extend` 设置 `yAxis.0.inverse` 来设置反转：

```js
        extend: {
          'yAxis.0.inverse': true,
        }
```

**Comment by a14528871763** [comment]
没有写进文档，那就是Bug
