### ISSUE TITLE
dimension（维度）的个数是从系统参数里拉来的，metrics的个数也不确定

### ISSUE THREAD

**Issue by Mojie-Wang** [ElemeFE/v-charts#73]
dimension，metrics可以是数组吗？
chartData: {
          columns: ['类型', '销售量'],
          rows: [
            { '类型': '散客', '销售量': 1 },
            { '类型': '散拼', '销售量': 2 },
            { '类型': '商务团', '销售量': 3 },
            { '类型': '研学游', '销售量': 4 },
            { '类型': 'moti端', '销售量': 5 },
            { '类型': '亲子团', '销售量': 6 }
          ]
        },
        chartSettings: {
          dimension: '类型',
          metrics: '销售量',
          selectedMode: 'multiple',
          radius: 100,
          offsetY: 180
        }
类型的个数不定的

**Comment by xiguaxigua** [comment]
使用的是哪种类型的图？

**Comment by xiguaxigua** [comment]
意思是数据的数据可能不确定？
比如可能是
```
{ '类型': '散客', '销售量': 1 },
{ '类型': '散拼', '销售量': 2 },
``,
也可能是
```
{ '类型': '散客', '销售量': 1 },
{ '类型': '散拼', '销售量': 2 },
{ '类型': '商务团', '销售量': 3 },
{ '类型': '研学游', '销售量': 4 },
{ '类型': 'moti端', '销售量': 5 },
```

如果是这样的话，维度和指标其实是确定的（单指标单维度），v-charts 也是支持的。默认 v-charts 以 columns 的第一项为指标，第二项为维度，只要后端处理的时候注意一下这和顺序，是不需要写在 chartSettings 里面的。

如果要显示多指标多维度的话，例如
```
 {
columns: ['类型', '日期', '成本', '销售量'],
rows: [
    { '日期': '2017-10-20','类型': '散客', '成本': 100,'销售量': 1 },
    { '日期': '2017-10-20','类型': '散拼', '成本': 100,'销售量': 2 },
    { '日期': '2017-10-20','类型': '商务团', '成本': 100,'销售量': 3 },
    { '日期': '2017-10-20','类型': '研学游', '成本': 100,'销售量': 4 },
    { '日期': '2017-10-20','类型': 'moti端', '成本': 100,'销售量': 5 },
    { '日期': '2017-10-20','类型': '亲子团', '成本': 100,'销售量': 6 },
    { '日期': '2017-10-21','类型': '散客', '成本': 100,'销售量': 1 },
    { '日期': '2017-10-21','类型': '散拼', '成本': 100,'销售量': 2 },
    { '日期': '2017-10-21','类型': '商务团', '成本': 100,'销售量': 3 },
    { '日期': '2017-10-21','类型': '研学游', '成本': 100,'销售量': 4 },
    { '日期': '2017-10-21','类型': 'moti端', '成本': 100,'销售量': 5 },
    { '日期': '2017-10-21','类型': '亲子团', '成本': 100,'销售量': 6 }
    ]
}
```
此时维度为 日期，类型，指标为 成本 销售量， 则就需要前端设置dimension 和 metrics 了，如果要将数据全部展示出来，需要用多个饼图，然后每个饼图设置不同的指标和维度即可。

**Comment by Mojie-Wang** [comment]
感谢
