### ISSUE TITLE
请问雷达图怎么配置线的颜色？？？

### ISSUE THREAD

**Issue by ghost** [ElemeFE/v-charts#730]
### Summary 简述

eaharts配置的跟v-charts不一样的，我尝试着配置，绑定colors也不行，itemStyle也不行。加到数据列表里面也不行。求解释一下
默认值怎么配置？我现在是数据列表里面加一条，所有值都设置的最大。才撑开的雷达

v-charts官方有点坑。

**Comment by TracyYangg** [comment]
同样有疑问

**Comment by JackChius** [comment]
同样问题，多处设定无效，请问是怎样解决？
