### ISSUE TITLE
x轴间距固定，数据过多时x轴滚动

### ISSUE THREAD

**Issue by RoiSoleil520** [ElemeFE/v-charts#751]
如题，以为这个 issue(https://github.com/ElemeFE/v-charts/issues/205) 是我遇到的问题，但是好像没有。
帅帅的作者大佬，数据过多时怎样实现横坐标间距固定，超出数据滚动查看的效果呀~
![image](https://user-images.githubusercontent.com/17526611/59333563-2a0b3b00-8d2b-11e9-9068-f71a75647f99.png)
![image](https://user-images.githubusercontent.com/17526611/59333578-32fc0c80-8d2b-11e9-9654-c743c0e3bd96.png)

**Comment by RoiSoleil520** [comment]
已解决

**Comment by RoiSoleil520** [comment]
![image](https://user-images.githubusercontent.com/17526611/59335176-a3585d00-8d2e-11e9-8b78-0ec781545851.png)
没有注意这句话。。

**Comment by alexwjj** [comment]
> 如题，以为这个 issue(#205) 是我遇到的问题，但是好像没有。
> 帅帅的作者大佬，数据过多时怎样实现横坐标间距固定，超出数据滚动查看的效果呀~
> ![image](https://user-images.githubusercontent.com/17526611/59333563-2a0b3b00-8d2b-11e9-9068-f71a75647f99.png)
> ![image](https://user-images.githubusercontent.com/17526611/59333578-32fc0c80-8d2b-11e9-9654-c743c0e3bd96.png)

这个是用的什么属性呢，github 图片都看不了了

**Comment by alexwjj** [comment]
> 已解决

大佬大佬，用什么解决的这个滚动问题呢，图片看不了了

**Comment by alexwjj** [comment]
> ![image](https://user-images.githubusercontent.com/17526611/59335176-a3585d00-8d2e-11e9-8b78-0ec781545851.png)
> 没有注意这句话。。

加载出来了，大佬大佬，确实没注意到这句话
