### ISSUE TITLE
地图能否支持自定义地图

### ISSUE THREAD

**Issue by povs2012** [ElemeFE/v-charts#76]
1. 现在的地图是自动根据position获取的，只能支持省市，能否自定义获取地图json的地址，支持到区县；
2. echarts的地图中省市的文字是按照省市的实际位置确定位置的，因此经常出现文字重叠的现象，官方提供的解决办法是在注册地图前处理返回的地图json数据，能否增加一个注册地图前的处理函数。

**Comment by xiguaxigua** [comment]
自定义 json 与注册地图前的处理函数目前是不支持的，稍后会发个版本支持一下。

**Comment by xiguaxigua** [comment]
@povs2012 v1.11.5 新增了两个属性，可以参考文档上面的例子。
