### ISSUE TITLE
多Y轴如何实现不是双轴

### ISSUE THREAD

**Issue by djkloop** [ElemeFE/v-charts#776]
### Summary 简述

多Y轴如何实现?
设置了yAxis但是没有效果

![image](https://user-images.githubusercontent.com/21050914/61371414-3acd4480-a8c7-11e9-84c1-f8aba0236e6c.png)

### Expect 期望结果
https://gallery.echartsjs.com/editor.html?c=multiple-y-axis

**Comment by zhaobinhong** [comment]
同问

**Comment by bolingsun** [comment]
<ve-histogram  :data="chartData" :yAxis="yAxis" :settings="chartSettings"  :extend="extend"></ve-histogram>
 先通过yAxis设置需要显示的几个Y轴，传数组类型，与Echart官方示例一样。

然后通过extend.series(v) 函数形式的配置遍历，设置i.yAxisIndex = 0/1/2等等Y轴的索引。
