### ISSUE TITLE
在区域平面图内，实现热力图的展现，例如：https://echarts.baidu.com/echarts2/doc/example/heatmap.html

### ISSUE THREAD

**Issue by huxianguan** [ElemeFE/v-charts#779]
### Summary 简述

需要根据人流的坐标生成热力图，网站没有相关例子，各种方法都试过了，请问如何配置

### Expect 期望结果

https://echarts.baidu.com/echarts2/doc/example/heatmap.html

**Comment by luichooy** [comment]
> ### Summary 简述
> 需要根据人流的坐标生成热力图，网站没有相关例子，各种方法都试过了，请问如何配置
> 
> ### Expect 期望结果
> https://echarts.baidu.com/echarts2/doc/example/heatmap.html

你好，请问最后是如何实现的呢

**Comment by huxianguan** [comment]
> > ### Summary 简述
> > 需要根据人流的坐标生成热力图，网站没有相关例子，各种方法都试过了，请问如何配置
> > ### Expect 期望结果
> > https://echarts.baidu.com/echarts2/doc/example/heatmap.html
> 
> 你好，请问最后是如何实现的呢

用了个别的组件，heatmapjs-vue
