### ISSUE TITLE
双y轴左右刻度不一致，如何像echarts一样可以分别设置

### ISSUE THREAD

**Issue by MicahZJ** [ElemeFE/v-charts#805]
### Summary 简述
![image](https://user-images.githubusercontent.com/24688222/68182892-c0d7dd00-ffd5-11e9-851f-f2cee7aca8c2.png)
yAxis里面只能修改两侧的刻度为同一标准，无法像原生echarts一样分别修改刻度

### Expect 期望结果
修改两侧的刻度为相同

### Reproduce 重现示例

yAxis: {
          // splitNumber: 5, 
          // interval:10,
          axisLabel: {
            color: 'white'
          },
          nameTextStyle: {
            color: 'white',//正常是不用添加
          },
          splitLine: {
            show: true,
            // 改变轴线颜色
            lineStyle: {
              // 使用深浅的间隔色
              color: ['#3755DA']
            }
          }
        },
        grid: {
          top:'20%',
          left: '3%',
          right: '4%',
          bottom: '2%',
        },
      }

**Comment by MicahZJ** [comment]
yAxis(item) {
          item[0].splitLine = Object.assign({}, {
            lineStyle: {
              color: ['#3755DA'],
            }
          });
          item[0].axisLabel = Object.assign( {},{
            color: 'white'
          });
          item[0].nameTextStyle = Object.assign( {},{
            color: 'white',//正常是不用添加
          });
          item[1].splitLine = Object.assign({}, {
            show: false,
            lineStyle: {
              color: ['#3755DA'],
            }
          });
          item[1].axisLabel = Object.assign( {},{
            color: 'white'
          });
          item[1].nameTextStyle = Object.assign( {},{
            color: 'white',//正常是不用添加
          });
          return item
}
item[0]是左侧，item[1]是右侧，这样改就行了，

**Comment by shenyjsoso** [comment]
想动态修改item[0].interval的值怎么做呢

**Comment by MicahZJ** [comment]
> 想动态修改item[0].interval的值怎么做呢

```
item[0].axisLabel = Object.assign( {},{
  interval: 2
});
```
你试试呢

**Comment by chenjiejing** [comment]
请问我想个根据选择的不同组合动态设置item[0]splitLine的显示和隐藏可以吗?yAxis传入可以不是函数形式吗

**Comment by chenjiejing** [comment]
请问我想个根据选择的不同组合动态设置item[0]splitLine的显示和隐藏可以吗?yAxis传入可以不是函数形式吗
