### ISSUE TITLE
请问一下当柱状图下面的title过长时为什么导致其他的不显示？

### ISSUE THREAD

**Issue by Kian-404** [ElemeFE/v-charts#813]
如图所示，当下面的title输入的文字过长的时候，会导致后面的柱状图的title不显示
![1111111.png](https://i.loli.net/2019/11/21/ABqepvu1lHhGgSK.png)
![TIM图片20191121152857.png](https://i.loli.net/2019/11/21/tG48dKBE7hgmvAI.png)

**Comment by Tsuj100** [comment]
![image](https://user-images.githubusercontent.com/38718810/69411425-ec81f380-0d47-11ea-8264-f75ce51bc268.png)

可以通过extend属性重新配置

**Comment by Kian-404** [comment]
> ![image](https://user-images.githubusercontent.com/38718810/69411425-ec81f380-0d47-11ea-8264-f75ce51bc268.png)
> 
> 可以通过extend属性重新配置

好的，多谢大佬，十分感谢！
