### ISSUE TITLE
为什么动态渲染数据是undefined的

### ISSUE THREAD

**Issue by jifengdehao** [ElemeFE/v-charts#83]
![image](https://user-images.githubusercontent.com/17547658/32485585-925ce8b2-c369-11e7-8ee3-071a35a88f6f.png)

**Comment by xiguaxigua** [comment]
方便抽象出一个例子看看吗？
之前写过一个动态加载的小例子，可以看下能否解决你的问题。
https://jsfiddle.net/vue_echarts/jepw6dy2/80/
