### ISSUE TITLE
指定城市地图图表中，如何解决陕西和山西因为拼音字母相同而导致只显示山西省地图的问题？？？

### ISSUE THREAD

**Issue by dogthirteen** [ElemeFE/v-charts#830]
Summary 简述：

指定城市地图图表中，如何解决陕西和山西因为拼音字母相同而导致只显示山西省地图的问题？？？
this.chartSettings = {
        position: 'province/shanxi',  // 还有别的方式可以区分省市吗，我在官网测试，也是一样的，图片贴不上去
        // selectData: true,
        selectedMode: 'single'
      }

Expect 期望结果：

有一个解决方式，

Reproduce 重现示例：
![image](https://user-images.githubusercontent.com/47291177/72216210-2f4a9580-3559-11ea-866b-c842548d8bff.png)

 官网的地图图表  设置城市  设置shanxi  无法区分是山西还是陕西
https://v-charts.js.org/#/map

**Comment by dogthirteen** [comment]
解决了，在https://unpkg.com/echarts@3.6.2/map/json/province/找到了对应文件

**Comment by androidxu** [comment]
地址有点变化https://unpkg.com/browse/echarts@3.6.2/map/json/province/
