### ISSUE TITLE
visualMap配置无效

### ISSUE THREAD

**Issue by qiyu2580** [ElemeFE/v-charts#835]
### 简介
在本地环境中配置visualMap没有任何反应, 但在jsfiddle中却有效.

### jsfiddle中的代码
https://jsfiddle.net/ghoeawu0/1/

### 本地代码
![image](https://user-images.githubusercontent.com/1301580/76162579-00782680-617a-11ea-86c9-e9cbcf066735.png)

### 想要效果
![image](https://user-images.githubusercontent.com/1301580/76162631-6a90cb80-617a-11ea-8129-01f7673846cb.png)

### 版本
v4.6.0    echarts
v1.19.0  v-charts

**Comment by qiyu2580** [comment]
需要引入

`import "echarts/lib/component/visualMap";`

**Comment by jreeycheng232** [comment]
6666
