### ISSUE TITLE
echarts发布了新版本后报错了

### ISSUE THREAD

**Issue by v2018z** [ElemeFE/v-charts#87]
![image](https://user-images.githubusercontent.com/3415207/32643533-a883237e-c5a1-11e7-8dd3-37e20c34cd0a.png)
能不能帮忙看看什么原因，谢谢 你。

**Comment by xiguaxigua** [comment]
echarts发布了新版本，可以试一试看还会不会有问题

**Comment by joweyoung** [comment]
同样的错误，是不是因为依赖的echarts出现了问题

**Comment by xiguaxigua** [comment]
在 webpack 的配置里面增加一下代码试试看：
```js
plugins: [
    // ...
    new webpack.DefinePlugin({
        'typeof __DEV__': JSON.stringify('boolean'),
        '__DEV__': false
    })
]
```
