### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [ElemeFE/v-charts#876]
Could you tell me the author Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by Rainmen-xia** [comment]
same question

**Comment by liuxiaobina** [comment]
same question

**Comment by liuxiaobina** [comment]
same question

**Comment by ambit-tsai** [comment]
> same question

I've made one [echarts-for-vue](https://github.com/ambit-tsai/echarts-for-vue), it is compatible with Vue 3 and 2.

**Comment by ambit-tsai** [comment]
> same question

I've made one [echarts-for-vue](https://github.com/ambit-tsai/echarts-for-vue), it is compatible with Vue 3 and 2.

**Comment by lloydzhou** [comment]
推荐一个vue3封装的版本

https://github.com/ecomfe/awesome-echarts/pull/41

[vuecharts3](https://github.com/lloydzhou/vuecharts)  以组件方式调用echarts绘制图表（API参考BizCharts）

**Comment by eagle1949** [comment]
https://www.npmjs.com/package/x-echarts 这个插件支持vue2 vue3 echarts5
