### ISSUE TITLE
使用v-charts出现错误

### ISSUE THREAD

**Issue by joweyoung** [ElemeFE/v-charts#88]
v-charts在使用过程中报错，在技术群里面讨论，以为是依赖echarts的问题，但是改换echarts之后仍然有问题，亟待解决，谢谢。
错误为：Uncaught ReferenceError: __DEV__ is not defined
v-charts版本为1.11.7

**Comment by xiguaxigua** [comment]
在 webpack 的配置里面增加一下代码试试看：
```js
plugins: [
    // ...
    new webpack.DefinePlugin({
        'typeof __DEV__': JSON.stringify('boolean'),
        '__DEV__': false
    })
]
```

**Comment by joweyoung** [comment]
可以了，谢谢大神了
