### ISSUE TITLE
啥时候出个基于Vue3.0的？

### ISSUE THREAD

**Issue by xuzhitudev** [ElemeFE/v-charts#891]

**Comment by ambit-tsai** [comment]
推荐 [echarts-for-vue](https://gitee.com/ambit/echarts-for-vue#echarts-for-vue)，同时支持 Vue 3 与 2

**Comment by lloydzhou** [comment]
推荐一个vue3封装的版本

https://github.com/ecomfe/awesome-echarts/pull/41

[vuecharts3](https://github.com/lloydzhou/vuecharts)  以组件方式调用echarts绘制图表（API参考BizCharts）

**Comment by xuzhitudev** [comment]
It's wonderful!
