### ISSUE TITLE
如何更改柱状图和条形图中 row 的颜色

### ISSUE THREAD

**Issue by tonywangcn** [ElemeFE/v-charts#90]
https://jsfiddle.net/vue_echarts/1Le0wps5/23/

这只是更改 columns 颜色，查找了一番貌似没找到更改 row 颜色的办法。

**Comment by xiguaxigua** [comment]
@tonywangcn 写了一个小例子 https://jsfiddle.net/1Le0wps5/48/，可以看看是不是这种效果。
目前 v-charts 没有处理单个数据的样式逻辑，所以需要在数据配置结束后，使用 afterconfig 函数，手动处理一下这部分数据，然后将处理好的 options 返回给 echarts 就可以了。

**Comment by tonywangcn** [comment]
赞！非常感谢，可否方便提供一些详细资料或链接描述解决这个问题的思路么，比如修改 echarts 的某几个属性，通过 v-charts 内部的某几个函数实现的这种效果么？粗略的看了下 v-chart 的源码，并没找到思路。多谢！

**Comment by xiguaxigua** [comment]
v-chart 在 afterConfig 前，将数据处理成了echarts options，如果有 afterConfig 方法，会调用这个方法并将返回的 options 传递给 echarts 用于展示。所以，首先需要了解一点关于 echarts 的[配置项](http://echarts.baidu.com/option.html#series-bar.data)，这个可以从官网上找到，然后，在 afterconfig 里面打印一下参数 options，对应的修改属性就可以了。

**Comment by tonywangcn** [comment]
感谢！
