### ISSUE TITLE
图表的一些长度属性感觉有点乱

### ISSUE THREAD

**Issue by ZJN-Bc** [ElemeFE/v-charts#93]
例如基本属性的 height , 在饼图和条形图里感觉设置的效果不一样， 饼图是整个块的高度，包括上下两块空白，条形图貌似只是图表的高度？图上下有两块空白找不到去除的方法
饼图设置内外径时候假如用数值来设置会出现指示线，文字，动画错乱的情况， 用百分比貌似才会正常？
总得使用后感觉展示效果很不错，问题是这些图很难放到我想放的位置，有些基本展示需求满足不了，希望能优化一下

**Comment by xiguaxigua** [comment]
1. `height` 决定的只是容器的高度，图表的高度由图表自身和 [grid](http://echarts.baidu.com/option.html#grid) 属性共同来控制，折线图没有自身高度配置，所以高度就是 `height - grid.top - grid.bottom`，饼图有[半径](http://echarts.baidu.com/option.html#series-pie.radius)的概念，所以高度就是 `2 * radius`。
2. 图上下的两块空白由 grid 属性来控制，去除方法参考[示例](https://jsfiddle.net/jepw6dy2/99/)。
3.  错位的问题我写了一个[例子](https://jsfiddle.net/tecfxdg9/40/)，没有重现出来，可以把你遇到的问题抽出一个例子看看。
4. 图的位置，可以参考 1 中的规则。如果方便的话，可以把你遇到的需求在下面描述一下，我可以根据需求把可行的配置方法写成例子给你。

**Comment by ZJN-Bc** [comment]
感谢大大的及时回复，
1.错位那个是环形图使用说明那里，“设置环图半径部分”，我以为小的是内径，大的是外径，所以反转了内外径导致错位问题
2.之前不知道grid属性的用法，试了下感觉可以处理基本位置的问题
👍👍👍
