### ISSUE TITLE
能否提供将图表另存为png, jpg, pdf和csv以及打印功能？

### ISSUE THREAD

**Issue by wei-hai** [ElemeFE/v-charts#94]
不胜感激！

**Comment by xiguaxigua** [comment]
图片功能参考 https://github.com/ElemeFE/v-charts/issues/15。

echarts toolbox 支持保存的图片格式有 'png' 和 'jpeg'；pdf、 csv、打印 功能 echarts 暂时不支持，可以到 echarts 的 issues 下提，或者在 v-charts 基础上封装一层；
