### ISSUE TITLE
需要让Y轴不显示，怎么配置啊

### ISSUE THREAD

**Issue by pannysp** [ElemeFE/v-charts#98]
百度echarts的配置是：
yAxis :{    
           show:false,
            type : 'value',
          axisLine : {
                        show : false,
                        onZero : false
                    }
        }

你们这个怎么配置啊

**Comment by xiguaxigua** [comment]
写了一个小例子，可以参考一下： https://jsfiddle.net/vue_echarts/jepw6dy2/105/
