### ISSUE TITLE
No tooltip text with xAxisType = 'time'

### ISSUE THREAD

**Issue by cobaltway** [ElemeFE/v-charts#99]
No tooltip label is displayed for x-axis when its type is set to time.
The x-axis itself is fine.

Demo: https://jsfiddle.net/qc441x6m/

<img width="1469" alt="capture d ecran 2017-12-01 a 15 31 33" src="https://user-images.githubusercontent.com/19687241/33487469-9fde510e-d6ad-11e7-9962-48ffe0603979.png">

I use v-charts version 1.12.0.

**Comment by xiguaxigua** [comment]
This is because in line-chart tooltip handler, it use the `name` prop to display item title by default, but while axisType is time, `name` prop will be empty string `''` and display nothing, and in v 1.12.1, fix this bug.

**Comment by cobaltway** [comment]
Solved indeed, thanks!
